// Package fsx provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fsx

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetEpfsParamsLocation.
const (
	GetEpfsParamsLocationChennai GetEpfsParamsLocation = "Chennai"
	GetEpfsParamsLocationDelhi   GetEpfsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetEpfsParamsLocation enum.
func (e GetEpfsParamsLocation) Valid() bool {
	switch e {
	case GetEpfsParamsLocationChennai:
		return true
	case GetEpfsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PostEpfsParamsLocation.
const (
	PostEpfsParamsLocationChennai PostEpfsParamsLocation = "Chennai"
	PostEpfsParamsLocationDelhi   PostEpfsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostEpfsParamsLocation enum.
func (e PostEpfsParamsLocation) Valid() bool {
	switch e {
	case PostEpfsParamsLocationChennai:
		return true
	case PostEpfsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for DeleteEpfsEpfsIdParamsLocation.
const (
	DeleteEpfsEpfsIdParamsLocationChennai DeleteEpfsEpfsIdParamsLocation = "Chennai"
	DeleteEpfsEpfsIdParamsLocationDelhi   DeleteEpfsEpfsIdParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the DeleteEpfsEpfsIdParamsLocation enum.
func (e DeleteEpfsEpfsIdParamsLocation) Valid() bool {
	switch e {
	case DeleteEpfsEpfsIdParamsLocationChennai:
		return true
	case DeleteEpfsEpfsIdParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetEpfsEpfsIdParamsLocation.
const (
	GetEpfsEpfsIdParamsLocationChennai GetEpfsEpfsIdParamsLocation = "Chennai"
	GetEpfsEpfsIdParamsLocationDelhi   GetEpfsEpfsIdParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetEpfsEpfsIdParamsLocation enum.
func (e GetEpfsEpfsIdParamsLocation) Valid() bool {
	switch e {
	case GetEpfsEpfsIdParamsLocationChennai:
		return true
	case GetEpfsEpfsIdParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutEpfsEpfsIdParamsLocation.
const (
	PutEpfsEpfsIdParamsLocationChennai PutEpfsEpfsIdParamsLocation = "Chennai"
	PutEpfsEpfsIdParamsLocationDelhi   PutEpfsEpfsIdParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PutEpfsEpfsIdParamsLocation enum.
func (e PutEpfsEpfsIdParamsLocation) Valid() bool {
	switch e {
	case PutEpfsEpfsIdParamsLocationChennai:
		return true
	case PutEpfsEpfsIdParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// GetEpfsParams defines parameters for GetEpfs.
type GetEpfsParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetEpfsParamsLocation `form:"location" json:"location"`

	// Page Page No.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Page size
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetEpfsParamsLocation defines parameters for GetEpfs.
type GetEpfsParamsLocation string

// PostEpfsJSONBody defines parameters for PostEpfs.
type PostEpfsJSONBody struct {
	// Name Example: epfs-127
	Name string `json:"name"`

	// NetworkId Example: 34872
	NetworkId int `json:"network_id"`

	// SizeInGb Example: 1000
	SizeInGb int `json:"size_in_gb"`
}

// PostEpfsParams defines parameters for PostEpfs.
type PostEpfsParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostEpfsParamsLocation `form:"location" json:"location"`
}

// PostEpfsParamsLocation defines parameters for PostEpfs.
type PostEpfsParamsLocation string

// DeleteEpfsEpfsIdParams defines parameters for DeleteEpfsEpfsId.
type DeleteEpfsEpfsIdParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location DeleteEpfsEpfsIdParamsLocation `form:"location" json:"location"`
}

// DeleteEpfsEpfsIdParamsLocation defines parameters for DeleteEpfsEpfsId.
type DeleteEpfsEpfsIdParamsLocation string

// GetEpfsEpfsIdParams defines parameters for GetEpfsEpfsId.
type GetEpfsEpfsIdParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetEpfsEpfsIdParamsLocation `form:"location" json:"location"`
}

// GetEpfsEpfsIdParamsLocation defines parameters for GetEpfsEpfsId.
type GetEpfsEpfsIdParamsLocation string

// PutEpfsEpfsIdJSONBody defines parameters for PutEpfsEpfsId.
type PutEpfsEpfsIdJSONBody struct {
	// Name Example: epfs-127
	Name string `json:"name"`

	// NetworkId Example: 34872
	NetworkId int `json:"network_id"`

	// SizeInGb Example: 2000
	SizeInGb int `json:"size_in_gb"`
}

// PutEpfsEpfsIdParams defines parameters for PutEpfsEpfsId.
type PutEpfsEpfsIdParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PutEpfsEpfsIdParamsLocation `form:"location" json:"location"`
}

// PutEpfsEpfsIdParamsLocation defines parameters for PutEpfsEpfsId.
type PutEpfsEpfsIdParamsLocation string

// PostEpfsJSONRequestBody defines body for PostEpfs for application/json ContentType.
type PostEpfsJSONRequestBody PostEpfsJSONBody

// PutEpfsEpfsIdJSONRequestBody defines body for PutEpfsEpfsId for application/json ContentType.
type PutEpfsEpfsIdJSONRequestBody PutEpfsEpfsIdJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetEpfs EPFS Listing
	//
	// Corresponds with GET /api/v1/epfs/ (the `GetEpfs` operationId).
	GetEpfs(ctx context.Context, params *GetEpfsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEpfsWithBody EPFS Creation
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
	PostEpfsWithBody(ctx context.Context, params *PostEpfsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEpfs EPFS Creation
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
	PostEpfs(ctx context.Context, params *PostEpfsParams, body PostEpfsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteEpfsEpfsId Delete EPFS
	//
	// Corresponds with DELETE /api/v1/epfs/{epfs_id}/ (the `DeleteEpfsEpfsId` operationId).
	DeleteEpfsEpfsId(ctx context.Context, epfsId int, params *DeleteEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEpfsEpfsId GET EPFS by Id
	//
	// Corresponds with GET /api/v1/epfs/{epfs_id}/ (the `GetEpfsEpfsId` operationId).
	GetEpfsEpfsId(ctx context.Context, epfsId int, params *GetEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEpfsEpfsIdWithBody Upgrade EPFS
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
	PutEpfsEpfsIdWithBody(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEpfsEpfsId Upgrade EPFS
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
	PutEpfsEpfsId(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, body PutEpfsEpfsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetEpfs EPFS Listing
//
// Corresponds with GET /api/v1/epfs/ (the `GetEpfs` operationId).
func (c *Client) GetEpfs(ctx context.Context, params *GetEpfsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEpfsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostEpfsWithBody EPFS Creation
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
func (c *Client) PostEpfsWithBody(ctx context.Context, params *PostEpfsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEpfsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostEpfs EPFS Creation
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
func (c *Client) PostEpfs(ctx context.Context, params *PostEpfsParams, body PostEpfsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEpfsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteEpfsEpfsId Delete EPFS
//
// Corresponds with DELETE /api/v1/epfs/{epfs_id}/ (the `DeleteEpfsEpfsId` operationId).
func (c *Client) DeleteEpfsEpfsId(ctx context.Context, epfsId int, params *DeleteEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteEpfsEpfsIdRequest(c.Server, epfsId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetEpfsEpfsId GET EPFS by Id
//
// Corresponds with GET /api/v1/epfs/{epfs_id}/ (the `GetEpfsEpfsId` operationId).
func (c *Client) GetEpfsEpfsId(ctx context.Context, epfsId int, params *GetEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEpfsEpfsIdRequest(c.Server, epfsId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEpfsEpfsIdWithBody Upgrade EPFS
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
func (c *Client) PutEpfsEpfsIdWithBody(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEpfsEpfsIdRequestWithBody(c.Server, epfsId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEpfsEpfsId Upgrade EPFS
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
func (c *Client) PutEpfsEpfsId(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, body PutEpfsEpfsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEpfsEpfsIdRequest(c.Server, epfsId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetEpfsRequest constructs an http.Request for the GetEpfs method
func NewGetEpfsRequest(server string, params *GetEpfsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/epfs/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostEpfsRequest calls the generic PostEpfs builder with application/json body
func NewPostEpfsRequest(server string, params *PostEpfsParams, body PostEpfsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEpfsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostEpfsRequestWithBody constructs an http.Request for the PostEpfs method, with any body, and a specified content type
func NewPostEpfsRequestWithBody(server string, params *PostEpfsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/epfs/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteEpfsEpfsIdRequest constructs an http.Request for the DeleteEpfsEpfsId method
func NewDeleteEpfsEpfsIdRequest(server string, epfsId int, params *DeleteEpfsEpfsIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "epfs_id", epfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/epfs/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEpfsEpfsIdRequest constructs an http.Request for the GetEpfsEpfsId method
func NewGetEpfsEpfsIdRequest(server string, epfsId int, params *GetEpfsEpfsIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "epfs_id", epfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/epfs/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutEpfsEpfsIdRequest calls the generic PutEpfsEpfsId builder with application/json body
func NewPutEpfsEpfsIdRequest(server string, epfsId int, params *PutEpfsEpfsIdParams, body PutEpfsEpfsIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutEpfsEpfsIdRequestWithBody(server, epfsId, params, "application/json", bodyReader)
}

// NewPutEpfsEpfsIdRequestWithBody constructs an http.Request for the PutEpfsEpfsId method, with any body, and a specified content type
func NewPutEpfsEpfsIdRequestWithBody(server string, epfsId int, params *PutEpfsEpfsIdParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "epfs_id", epfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/epfs/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetEpfsWithResponse EPFS Listing
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/epfs/ (the `GetEpfs` operationId).
	GetEpfsWithResponse(ctx context.Context, params *GetEpfsParams, reqEditors ...RequestEditorFn) (*GetEpfsResponse, error)

	// PostEpfsWithBodyWithResponse EPFS Creation
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
	PostEpfsWithBodyWithResponse(ctx context.Context, params *PostEpfsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEpfsResponse, error)

	// PostEpfsWithResponse EPFS Creation
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
	PostEpfsWithResponse(ctx context.Context, params *PostEpfsParams, body PostEpfsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEpfsResponse, error)

	// DeleteEpfsEpfsIdWithResponse Delete EPFS
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/epfs/{epfs_id}/ (the `DeleteEpfsEpfsId` operationId).
	DeleteEpfsEpfsIdWithResponse(ctx context.Context, epfsId int, params *DeleteEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*DeleteEpfsEpfsIdResponse, error)

	// GetEpfsEpfsIdWithResponse GET EPFS by Id
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/epfs/{epfs_id}/ (the `GetEpfsEpfsId` operationId).
	GetEpfsEpfsIdWithResponse(ctx context.Context, epfsId int, params *GetEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*GetEpfsEpfsIdResponse, error)

	// PutEpfsEpfsIdWithBodyWithResponse Upgrade EPFS
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
	PutEpfsEpfsIdWithBodyWithResponse(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutEpfsEpfsIdResponse, error)

	// PutEpfsEpfsIdWithResponse Upgrade EPFS
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
	PutEpfsEpfsIdWithResponse(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, body PutEpfsEpfsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutEpfsEpfsIdResponse, error)
}

type GetEpfsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// ClientProjectId Example: 3714414517595
			ClientProjectId *string `json:"client_project_id,omitempty"`

			// CreatedAt Example: 2025-05-26T09:40:25.508756Z
			CreatedAt *time.Time `json:"created_at,omitempty"`

			// Customer Example: 37144
			Customer *int `json:"customer,omitempty"`

			// Deleted Example: false
			Deleted   *bool   `json:"deleted,omitempty"`
			DeletedAt *string `json:"deleted_at,omitempty"`

			// FsId Example: 37144145
			FsId *string `json:"fs_id,omitempty"`

			// FsName Example: pfs0
			FsName *string `json:"fs_name,omitempty"`

			// GatewayIp Example: 10.7.27.254
			GatewayIp *string `json:"gateway_ip,omitempty"`

			// Id Example: 145
			Id *int `json:"id,omitempty"`

			// Location Example: Delhi
			Location *string `json:"location,omitempty"`

			// Name Example: epfs-127
			Name *string `json:"name,omitempty"`

			// Nid Example: 1144
			Nid *int `json:"nid,omitempty"`

			// PlanName Example:
			PlanName *string `json:"plan_name,omitempty"`

			// Project Example: 42347
			Project *int `json:"project,omitempty"`

			// Size Example: 1000
			Size *int `json:"size,omitempty"`

			// Status Example: running
			Status *string `json:"status,omitempty"`

			// UpdatedAt Example: 2025-05-26T09:42:14.054705Z
			UpdatedAt *time.Time `json:"updated_at,omitempty"`
			Vpc       *struct {
				// Dns Example: 8.8.8.8 8.8.4.4
				Dns *string `json:"dns,omitempty"`

				// GatewayIp Example: 10.7.26.1
				GatewayIp *string `json:"gateway_ip,omitempty"`

				// Ipv4Cidr Example: 10.7.26.0/23
				Ipv4Cidr *string `json:"ipv4_cidr,omitempty"`

				// IsActive Example: true
				IsActive *bool `json:"is_active,omitempty"`

				// Name Example: VPC-717
				Name *string `json:"name,omitempty"`

				// NetworkId Example: 34872
				NetworkId *int `json:"network_id,omitempty"`

				// NetworkMask Example: 255.255.254.0
				NetworkMask *string `json:"network_mask,omitempty"`

				// ReserveNetworkId Example: 34873
				ReserveNetworkId *int `json:"reserve_network_id,omitempty"`

				// State Example: Running
				State *string `json:"state,omitempty"`

				// VmCount Example: 0
				VmCount *int `json:"vm_count,omitempty"`
			} `json:"vpc,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`

		// TotalCount Example: 1
		TotalCount *int `json:"total_count,omitempty"`

		// TotalPageNumber Example: 1
		TotalPageNumber *int `json:"total_page_number,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetEpfsResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// ClientProjectId Example: 3714414517595
		ClientProjectId *string `json:"client_project_id,omitempty"`

		// CreatedAt Example: 2025-05-26T09:40:25.508756Z
		CreatedAt *time.Time `json:"created_at,omitempty"`

		// Customer Example: 37144
		Customer *int `json:"customer,omitempty"`

		// Deleted Example: false
		Deleted   *bool   `json:"deleted,omitempty"`
		DeletedAt *string `json:"deleted_at,omitempty"`

		// FsId Example: 37144145
		FsId *string `json:"fs_id,omitempty"`

		// FsName Example: pfs0
		FsName *string `json:"fs_name,omitempty"`

		// GatewayIp Example: 10.7.27.254
		GatewayIp *string `json:"gateway_ip,omitempty"`

		// Id Example: 145
		Id *int `json:"id,omitempty"`

		// Location Example: Delhi
		Location *string `json:"location,omitempty"`

		// Name Example: epfs-127
		Name *string `json:"name,omitempty"`

		// Nid Example: 1144
		Nid *int `json:"nid,omitempty"`

		// PlanName Example:
		PlanName *string `json:"plan_name,omitempty"`

		// Project Example: 42347
		Project *int `json:"project,omitempty"`

		// Size Example: 1000
		Size *int `json:"size,omitempty"`

		// Status Example: running
		Status *string `json:"status,omitempty"`

		// UpdatedAt Example: 2025-05-26T09:42:14.054705Z
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
		Vpc       *struct {
			// Dns Example: 8.8.8.8 8.8.4.4
			Dns *string `json:"dns,omitempty"`

			// GatewayIp Example: 10.7.26.1
			GatewayIp *string `json:"gateway_ip,omitempty"`

			// Ipv4Cidr Example: 10.7.26.0/23
			Ipv4Cidr *string `json:"ipv4_cidr,omitempty"`

			// IsActive Example: true
			IsActive *bool `json:"is_active,omitempty"`

			// Name Example: VPC-717
			Name *string `json:"name,omitempty"`

			// NetworkId Example: 34872
			NetworkId *int `json:"network_id,omitempty"`

			// NetworkMask Example: 255.255.254.0
			NetworkMask *string `json:"network_mask,omitempty"`

			// ReserveNetworkId Example: 34873
			ReserveNetworkId *int `json:"reserve_network_id,omitempty"`

			// State Example: Running
			State *string `json:"state,omitempty"`

			// VmCount Example: 0
			VmCount *int `json:"vm_count,omitempty"`
		} `json:"vpc,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`

	// TotalCount Example: 1
	TotalCount *int `json:"total_count,omitempty"`

	// TotalPageNumber Example: 1
	TotalPageNumber *int `json:"total_page_number,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetEpfsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetEpfsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEpfsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEpfsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostEpfsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *struct {
		// Code Example: 201
		Code *int `json:"code,omitempty"`
		Data *struct {
			// ClusterId Example: 145
			ClusterId *int `json:"cluster_id,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Created Successfully
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PostEpfsResponse) GetJSON201() *struct {
	// Code Example: 201
	Code *int `json:"code,omitempty"`
	Data *struct {
		// ClusterId Example: 145
		ClusterId *int `json:"cluster_id,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Created Successfully
	Message *string `json:"message,omitempty"`
} {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r PostEpfsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostEpfsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEpfsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostEpfsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteEpfsEpfsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`

		// Data Example: Pfs has been deleted.
		Data *string `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteEpfsEpfsIdResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`

	// Data Example: Pfs has been deleted.
	Data *string `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r DeleteEpfsEpfsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteEpfsEpfsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteEpfsEpfsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteEpfsEpfsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetEpfsEpfsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// ClientProjectId Example: 3714414517595
			ClientProjectId *string `json:"client_project_id,omitempty"`

			// CreatedAt Example: 2025-05-26T09:40:25.508756Z
			CreatedAt *time.Time `json:"created_at,omitempty"`

			// Customer Example: 37144
			Customer *int `json:"customer,omitempty"`

			// Deleted Example: false
			Deleted   *bool   `json:"deleted,omitempty"`
			DeletedAt *string `json:"deleted_at,omitempty"`

			// FsId Example: 37144145
			FsId *string `json:"fs_id,omitempty"`

			// FsName Example: pfs0
			FsName *string `json:"fs_name,omitempty"`

			// GatewayIp Example: 10.7.27.254
			GatewayIp *string `json:"gateway_ip,omitempty"`

			// Id Example: 145
			Id *int `json:"id,omitempty"`

			// Location Example: Delhi
			Location *string `json:"location,omitempty"`

			// Name Example: epfs-127
			Name *string `json:"name,omitempty"`

			// Nid Example: 1144
			Nid *int `json:"nid,omitempty"`

			// PlanName Example:
			PlanName *string `json:"plan_name,omitempty"`

			// Project Example: 42347
			Project *int `json:"project,omitempty"`

			// Size Example: 1000
			Size *int `json:"size,omitempty"`

			// Status Example: running
			Status *string `json:"status,omitempty"`

			// UpdatedAt Example: 2025-05-26T09:42:14.054705Z
			UpdatedAt *time.Time `json:"updated_at,omitempty"`
			Vpc       *struct {
				// Dns Example: 8.8.8.8 8.8.4.4
				Dns *string `json:"dns,omitempty"`

				// GatewayIp Example: 10.7.26.1
				GatewayIp *string `json:"gateway_ip,omitempty"`

				// Ipv4Cidr Example: 10.7.26.0/23
				Ipv4Cidr *string `json:"ipv4_cidr,omitempty"`

				// IsActive Example: true
				IsActive *bool `json:"is_active,omitempty"`

				// Name Example: VPC-717
				Name *string `json:"name,omitempty"`

				// NetworkId Example: 34872
				NetworkId *int `json:"network_id,omitempty"`

				// NetworkMask Example: 255.255.254.0
				NetworkMask *string `json:"network_mask,omitempty"`

				// ReserveNetworkId Example: 34873
				ReserveNetworkId *int `json:"reserve_network_id,omitempty"`

				// State Example: Running
				State *string `json:"state,omitempty"`

				// VmCount Example: 0
				VmCount *int `json:"vm_count,omitempty"`
			} `json:"vpc,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetEpfsEpfsIdResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// ClientProjectId Example: 3714414517595
		ClientProjectId *string `json:"client_project_id,omitempty"`

		// CreatedAt Example: 2025-05-26T09:40:25.508756Z
		CreatedAt *time.Time `json:"created_at,omitempty"`

		// Customer Example: 37144
		Customer *int `json:"customer,omitempty"`

		// Deleted Example: false
		Deleted   *bool   `json:"deleted,omitempty"`
		DeletedAt *string `json:"deleted_at,omitempty"`

		// FsId Example: 37144145
		FsId *string `json:"fs_id,omitempty"`

		// FsName Example: pfs0
		FsName *string `json:"fs_name,omitempty"`

		// GatewayIp Example: 10.7.27.254
		GatewayIp *string `json:"gateway_ip,omitempty"`

		// Id Example: 145
		Id *int `json:"id,omitempty"`

		// Location Example: Delhi
		Location *string `json:"location,omitempty"`

		// Name Example: epfs-127
		Name *string `json:"name,omitempty"`

		// Nid Example: 1144
		Nid *int `json:"nid,omitempty"`

		// PlanName Example:
		PlanName *string `json:"plan_name,omitempty"`

		// Project Example: 42347
		Project *int `json:"project,omitempty"`

		// Size Example: 1000
		Size *int `json:"size,omitempty"`

		// Status Example: running
		Status *string `json:"status,omitempty"`

		// UpdatedAt Example: 2025-05-26T09:42:14.054705Z
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
		Vpc       *struct {
			// Dns Example: 8.8.8.8 8.8.4.4
			Dns *string `json:"dns,omitempty"`

			// GatewayIp Example: 10.7.26.1
			GatewayIp *string `json:"gateway_ip,omitempty"`

			// Ipv4Cidr Example: 10.7.26.0/23
			Ipv4Cidr *string `json:"ipv4_cidr,omitempty"`

			// IsActive Example: true
			IsActive *bool `json:"is_active,omitempty"`

			// Name Example: VPC-717
			Name *string `json:"name,omitempty"`

			// NetworkId Example: 34872
			NetworkId *int `json:"network_id,omitempty"`

			// NetworkMask Example: 255.255.254.0
			NetworkMask *string `json:"network_mask,omitempty"`

			// ReserveNetworkId Example: 34873
			ReserveNetworkId *int `json:"reserve_network_id,omitempty"`

			// State Example: Running
			State *string `json:"state,omitempty"`

			// VmCount Example: 0
			VmCount *int `json:"vm_count,omitempty"`
		} `json:"vpc,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetEpfsEpfsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetEpfsEpfsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEpfsEpfsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEpfsEpfsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutEpfsEpfsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`

		// Data Example: Upgrading in process
		Data *string `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutEpfsEpfsIdResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`

	// Data Example: Upgrading in process
	Data *string `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PutEpfsEpfsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutEpfsEpfsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutEpfsEpfsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutEpfsEpfsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetEpfsWithResponse EPFS Listing
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/epfs/ (the `GetEpfs` operationId).
func (c *ClientWithResponses) GetEpfsWithResponse(ctx context.Context, params *GetEpfsParams, reqEditors ...RequestEditorFn) (*GetEpfsResponse, error) {
	rsp, err := c.GetEpfs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEpfsResponse(rsp)
}

// PostEpfsWithBodyWithResponse EPFS Creation
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
func (c *ClientWithResponses) PostEpfsWithBodyWithResponse(ctx context.Context, params *PostEpfsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEpfsResponse, error) {
	rsp, err := c.PostEpfsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEpfsResponse(rsp)
}

// PostEpfsWithResponse EPFS Creation
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/epfs/ (the `PostEpfs` operationId).
func (c *ClientWithResponses) PostEpfsWithResponse(ctx context.Context, params *PostEpfsParams, body PostEpfsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEpfsResponse, error) {
	rsp, err := c.PostEpfs(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEpfsResponse(rsp)
}

// DeleteEpfsEpfsIdWithResponse Delete EPFS
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/epfs/{epfs_id}/ (the `DeleteEpfsEpfsId` operationId).
func (c *ClientWithResponses) DeleteEpfsEpfsIdWithResponse(ctx context.Context, epfsId int, params *DeleteEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*DeleteEpfsEpfsIdResponse, error) {
	rsp, err := c.DeleteEpfsEpfsId(ctx, epfsId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteEpfsEpfsIdResponse(rsp)
}

// GetEpfsEpfsIdWithResponse GET EPFS by Id
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/epfs/{epfs_id}/ (the `GetEpfsEpfsId` operationId).
func (c *ClientWithResponses) GetEpfsEpfsIdWithResponse(ctx context.Context, epfsId int, params *GetEpfsEpfsIdParams, reqEditors ...RequestEditorFn) (*GetEpfsEpfsIdResponse, error) {
	rsp, err := c.GetEpfsEpfsId(ctx, epfsId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEpfsEpfsIdResponse(rsp)
}

// PutEpfsEpfsIdWithBodyWithResponse Upgrade EPFS
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
func (c *ClientWithResponses) PutEpfsEpfsIdWithBodyWithResponse(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutEpfsEpfsIdResponse, error) {
	rsp, err := c.PutEpfsEpfsIdWithBody(ctx, epfsId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEpfsEpfsIdResponse(rsp)
}

// PutEpfsEpfsIdWithResponse Upgrade EPFS
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/epfs/{epfs_id}/ (the `PutEpfsEpfsId` operationId).
func (c *ClientWithResponses) PutEpfsEpfsIdWithResponse(ctx context.Context, epfsId int, params *PutEpfsEpfsIdParams, body PutEpfsEpfsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutEpfsEpfsIdResponse, error) {
	rsp, err := c.PutEpfsEpfsId(ctx, epfsId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEpfsEpfsIdResponse(rsp)
}

// ParseGetEpfsResponse parses an HTTP response from a GetEpfsWithResponse call
func ParseGetEpfsResponse(rsp *http.Response) (*GetEpfsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEpfsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// ClientProjectId Example: 3714414517595
				ClientProjectId *string `json:"client_project_id,omitempty"`

				// CreatedAt Example: 2025-05-26T09:40:25.508756Z
				CreatedAt *time.Time `json:"created_at,omitempty"`

				// Customer Example: 37144
				Customer *int `json:"customer,omitempty"`

				// Deleted Example: false
				Deleted   *bool   `json:"deleted,omitempty"`
				DeletedAt *string `json:"deleted_at,omitempty"`

				// FsId Example: 37144145
				FsId *string `json:"fs_id,omitempty"`

				// FsName Example: pfs0
				FsName *string `json:"fs_name,omitempty"`

				// GatewayIp Example: 10.7.27.254
				GatewayIp *string `json:"gateway_ip,omitempty"`

				// Id Example: 145
				Id *int `json:"id,omitempty"`

				// Location Example: Delhi
				Location *string `json:"location,omitempty"`

				// Name Example: epfs-127
				Name *string `json:"name,omitempty"`

				// Nid Example: 1144
				Nid *int `json:"nid,omitempty"`

				// PlanName Example:
				PlanName *string `json:"plan_name,omitempty"`

				// Project Example: 42347
				Project *int `json:"project,omitempty"`

				// Size Example: 1000
				Size *int `json:"size,omitempty"`

				// Status Example: running
				Status *string `json:"status,omitempty"`

				// UpdatedAt Example: 2025-05-26T09:42:14.054705Z
				UpdatedAt *time.Time `json:"updated_at,omitempty"`
				Vpc       *struct {
					// Dns Example: 8.8.8.8 8.8.4.4
					Dns *string `json:"dns,omitempty"`

					// GatewayIp Example: 10.7.26.1
					GatewayIp *string `json:"gateway_ip,omitempty"`

					// Ipv4Cidr Example: 10.7.26.0/23
					Ipv4Cidr *string `json:"ipv4_cidr,omitempty"`

					// IsActive Example: true
					IsActive *bool `json:"is_active,omitempty"`

					// Name Example: VPC-717
					Name *string `json:"name,omitempty"`

					// NetworkId Example: 34872
					NetworkId *int `json:"network_id,omitempty"`

					// NetworkMask Example: 255.255.254.0
					NetworkMask *string `json:"network_mask,omitempty"`

					// ReserveNetworkId Example: 34873
					ReserveNetworkId *int `json:"reserve_network_id,omitempty"`

					// State Example: Running
					State *string `json:"state,omitempty"`

					// VmCount Example: 0
					VmCount *int `json:"vm_count,omitempty"`
				} `json:"vpc,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`

			// TotalCount Example: 1
			TotalCount *int `json:"total_count,omitempty"`

			// TotalPageNumber Example: 1
			TotalPageNumber *int `json:"total_page_number,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEpfsResponse parses an HTTP response from a PostEpfsWithResponse call
func ParsePostEpfsResponse(rsp *http.Response) (*PostEpfsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEpfsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// Code Example: 201
			Code *int `json:"code,omitempty"`
			Data *struct {
				// ClusterId Example: 145
				ClusterId *int `json:"cluster_id,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Created Successfully
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteEpfsEpfsIdResponse parses an HTTP response from a DeleteEpfsEpfsIdWithResponse call
func ParseDeleteEpfsEpfsIdResponse(rsp *http.Response) (*DeleteEpfsEpfsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteEpfsEpfsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`

			// Data Example: Pfs has been deleted.
			Data *string `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetEpfsEpfsIdResponse parses an HTTP response from a GetEpfsEpfsIdWithResponse call
func ParseGetEpfsEpfsIdResponse(rsp *http.Response) (*GetEpfsEpfsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEpfsEpfsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// ClientProjectId Example: 3714414517595
				ClientProjectId *string `json:"client_project_id,omitempty"`

				// CreatedAt Example: 2025-05-26T09:40:25.508756Z
				CreatedAt *time.Time `json:"created_at,omitempty"`

				// Customer Example: 37144
				Customer *int `json:"customer,omitempty"`

				// Deleted Example: false
				Deleted   *bool   `json:"deleted,omitempty"`
				DeletedAt *string `json:"deleted_at,omitempty"`

				// FsId Example: 37144145
				FsId *string `json:"fs_id,omitempty"`

				// FsName Example: pfs0
				FsName *string `json:"fs_name,omitempty"`

				// GatewayIp Example: 10.7.27.254
				GatewayIp *string `json:"gateway_ip,omitempty"`

				// Id Example: 145
				Id *int `json:"id,omitempty"`

				// Location Example: Delhi
				Location *string `json:"location,omitempty"`

				// Name Example: epfs-127
				Name *string `json:"name,omitempty"`

				// Nid Example: 1144
				Nid *int `json:"nid,omitempty"`

				// PlanName Example:
				PlanName *string `json:"plan_name,omitempty"`

				// Project Example: 42347
				Project *int `json:"project,omitempty"`

				// Size Example: 1000
				Size *int `json:"size,omitempty"`

				// Status Example: running
				Status *string `json:"status,omitempty"`

				// UpdatedAt Example: 2025-05-26T09:42:14.054705Z
				UpdatedAt *time.Time `json:"updated_at,omitempty"`
				Vpc       *struct {
					// Dns Example: 8.8.8.8 8.8.4.4
					Dns *string `json:"dns,omitempty"`

					// GatewayIp Example: 10.7.26.1
					GatewayIp *string `json:"gateway_ip,omitempty"`

					// Ipv4Cidr Example: 10.7.26.0/23
					Ipv4Cidr *string `json:"ipv4_cidr,omitempty"`

					// IsActive Example: true
					IsActive *bool `json:"is_active,omitempty"`

					// Name Example: VPC-717
					Name *string `json:"name,omitempty"`

					// NetworkId Example: 34872
					NetworkId *int `json:"network_id,omitempty"`

					// NetworkMask Example: 255.255.254.0
					NetworkMask *string `json:"network_mask,omitempty"`

					// ReserveNetworkId Example: 34873
					ReserveNetworkId *int `json:"reserve_network_id,omitempty"`

					// State Example: Running
					State *string `json:"state,omitempty"`

					// VmCount Example: 0
					VmCount *int `json:"vm_count,omitempty"`
				} `json:"vpc,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutEpfsEpfsIdResponse parses an HTTP response from a PutEpfsEpfsIdWithResponse call
func ParsePutEpfsEpfsIdResponse(rsp *http.Response) (*PutEpfsEpfsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutEpfsEpfsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`

			// Data Example: Upgrading in process
			Data *string `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
