// Package servicequotas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package servicequotas

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetResourceQuotaDetailsParamsLocation.
const (
	Chennai GetResourceQuotaDetailsParamsLocation = "Chennai"
	Delhi   GetResourceQuotaDetailsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetResourceQuotaDetailsParamsLocation enum.
func (e GetResourceQuotaDetailsParamsLocation) Valid() bool {
	switch e {
	case Chennai:
		return true
	case Delhi:
		return true
	default:
		return false
	}
}

// GetResourceQuotaDetailsParams defines parameters for GetResourceQuotaDetails.
type GetResourceQuotaDetailsParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetResourceQuotaDetailsParamsLocation `form:"location" json:"location"`
}

// GetResourceQuotaDetailsParamsLocation defines parameters for GetResourceQuotaDetails.
type GetResourceQuotaDetailsParamsLocation string

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCustomerResourceLimit Resource Limit
	//
	// Corresponds with GET /api/v1/customer-resource-limit/ (the `GetCustomerResourceLimit` operationId).
	GetCustomerResourceLimit(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetResourceQuotaDetails Resource Details
	//
	// Retrieves the current status of resource quotas.
	//
	// Corresponds with GET /api/v1/resource-quota-details/ (the `GetResourceQuotaDetails` operationId).
	GetResourceQuotaDetails(ctx context.Context, params *GetResourceQuotaDetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCustomerResourceLimit Resource Limit
//
// Corresponds with GET /api/v1/customer-resource-limit/ (the `GetCustomerResourceLimit` operationId).
func (c *Client) GetCustomerResourceLimit(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCustomerResourceLimitRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetResourceQuotaDetails Resource Details
//
// Retrieves the current status of resource quotas.
//
// Corresponds with GET /api/v1/resource-quota-details/ (the `GetResourceQuotaDetails` operationId).
func (c *Client) GetResourceQuotaDetails(ctx context.Context, params *GetResourceQuotaDetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetResourceQuotaDetailsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCustomerResourceLimitRequest constructs an http.Request for the GetCustomerResourceLimit method
func NewGetCustomerResourceLimitRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/customer-resource-limit/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetResourceQuotaDetailsRequest constructs an http.Request for the GetResourceQuotaDetails method
func NewGetResourceQuotaDetailsRequest(server string, params *GetResourceQuotaDetailsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/resource-quota-details/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCustomerResourceLimitWithResponse Resource Limit
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/customer-resource-limit/ (the `GetCustomerResourceLimit` operationId).
	GetCustomerResourceLimitWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCustomerResourceLimitResponse, error)

	// GetResourceQuotaDetailsWithResponse Resource Details
	//
	// Retrieves the current status of resource quotas.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/resource-quota-details/ (the `GetResourceQuotaDetails` operationId).
	GetResourceQuotaDetailsWithResponse(ctx context.Context, params *GetResourceQuotaDetailsParams, reqEditors ...RequestEditorFn) (*GetResourceQuotaDetailsResponse, error)
}

type GetCustomerResourceLimitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// ExistingCustomer Example: false
			ExistingCustomer *bool `json:"existing_customer,omitempty"`

			// IsCustomerResourceLimitUsed Example: false
			IsCustomerResourceLimitUsed *bool `json:"is_customer_resource_limit_used,omitempty"`

			// IsGpuAndHigherPlansEnabled Example: true
			IsGpuAndHigherPlansEnabled *bool `json:"is_gpu_and_higher_plans_enabled,omitempty"`

			// TotalLimit Example: 15
			TotalLimit *int `json:"total_limit,omitempty"`

			// UsedLimit Example: 7
			UsedLimit *int `json:"used_limit,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCustomerResourceLimitResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// ExistingCustomer Example: false
		ExistingCustomer *bool `json:"existing_customer,omitempty"`

		// IsCustomerResourceLimitUsed Example: false
		IsCustomerResourceLimitUsed *bool `json:"is_customer_resource_limit_used,omitempty"`

		// IsGpuAndHigherPlansEnabled Example: true
		IsGpuAndHigherPlansEnabled *bool `json:"is_gpu_and_higher_plans_enabled,omitempty"`

		// TotalLimit Example: 15
		TotalLimit *int `json:"total_limit,omitempty"`

		// UsedLimit Example: 7
		UsedLimit *int `json:"used_limit,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetCustomerResourceLimitResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCustomerResourceLimitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCustomerResourceLimitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCustomerResourceLimitResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetResourceQuotaDetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// CappedResourcesQuota Example: 30
			CappedResourcesQuota *int `json:"capped_resources_quota,omitempty"`
			ConsumedQuotaDetails *struct {
				// Dbaas Example: 0
				Dbaas *int `json:"dbaas,omitempty"`

				// LoadBalancer Example: 1
				LoadBalancer *int `json:"load_balancer,omitempty"`

				// Node Example: 0
				Node *int `json:"node,omitempty"`

				// Vpc Example: 1
				Vpc *int `json:"vpc,omitempty"`
			} `json:"consumed_quota_details,omitempty"`

			// ConsumedResourcesQuota Example: 2
			ConsumedResourcesQuota *int `json:"consumed_resources_quota,omitempty"`

			// GpuAndHigherPlansEnabled Example: true
			GpuAndHigherPlansEnabled *bool `json:"gpu_and_higher_plans_enabled,omitempty"`

			// ResourceQuotaEnabled Example: true
			ResourceQuotaEnabled *bool `json:"resource_quota_enabled,omitempty"`

			// ResourceQuotaUsed Example: false
			ResourceQuotaUsed *bool `json:"resource_quota_used,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetResourceQuotaDetailsResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// CappedResourcesQuota Example: 30
		CappedResourcesQuota *int `json:"capped_resources_quota,omitempty"`
		ConsumedQuotaDetails *struct {
			// Dbaas Example: 0
			Dbaas *int `json:"dbaas,omitempty"`

			// LoadBalancer Example: 1
			LoadBalancer *int `json:"load_balancer,omitempty"`

			// Node Example: 0
			Node *int `json:"node,omitempty"`

			// Vpc Example: 1
			Vpc *int `json:"vpc,omitempty"`
		} `json:"consumed_quota_details,omitempty"`

		// ConsumedResourcesQuota Example: 2
		ConsumedResourcesQuota *int `json:"consumed_resources_quota,omitempty"`

		// GpuAndHigherPlansEnabled Example: true
		GpuAndHigherPlansEnabled *bool `json:"gpu_and_higher_plans_enabled,omitempty"`

		// ResourceQuotaEnabled Example: true
		ResourceQuotaEnabled *bool `json:"resource_quota_enabled,omitempty"`

		// ResourceQuotaUsed Example: false
		ResourceQuotaUsed *bool `json:"resource_quota_used,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetResourceQuotaDetailsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetResourceQuotaDetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetResourceQuotaDetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetResourceQuotaDetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCustomerResourceLimitWithResponse Resource Limit
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/customer-resource-limit/ (the `GetCustomerResourceLimit` operationId).
func (c *ClientWithResponses) GetCustomerResourceLimitWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCustomerResourceLimitResponse, error) {
	rsp, err := c.GetCustomerResourceLimit(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCustomerResourceLimitResponse(rsp)
}

// GetResourceQuotaDetailsWithResponse Resource Details
//
// Retrieves the current status of resource quotas.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/resource-quota-details/ (the `GetResourceQuotaDetails` operationId).
func (c *ClientWithResponses) GetResourceQuotaDetailsWithResponse(ctx context.Context, params *GetResourceQuotaDetailsParams, reqEditors ...RequestEditorFn) (*GetResourceQuotaDetailsResponse, error) {
	rsp, err := c.GetResourceQuotaDetails(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetResourceQuotaDetailsResponse(rsp)
}

// ParseGetCustomerResourceLimitResponse parses an HTTP response from a GetCustomerResourceLimitWithResponse call
func ParseGetCustomerResourceLimitResponse(rsp *http.Response) (*GetCustomerResourceLimitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCustomerResourceLimitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// ExistingCustomer Example: false
				ExistingCustomer *bool `json:"existing_customer,omitempty"`

				// IsCustomerResourceLimitUsed Example: false
				IsCustomerResourceLimitUsed *bool `json:"is_customer_resource_limit_used,omitempty"`

				// IsGpuAndHigherPlansEnabled Example: true
				IsGpuAndHigherPlansEnabled *bool `json:"is_gpu_and_higher_plans_enabled,omitempty"`

				// TotalLimit Example: 15
				TotalLimit *int `json:"total_limit,omitempty"`

				// UsedLimit Example: 7
				UsedLimit *int `json:"used_limit,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetResourceQuotaDetailsResponse parses an HTTP response from a GetResourceQuotaDetailsWithResponse call
func ParseGetResourceQuotaDetailsResponse(rsp *http.Response) (*GetResourceQuotaDetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetResourceQuotaDetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// CappedResourcesQuota Example: 30
				CappedResourcesQuota *int `json:"capped_resources_quota,omitempty"`
				ConsumedQuotaDetails *struct {
					// Dbaas Example: 0
					Dbaas *int `json:"dbaas,omitempty"`

					// LoadBalancer Example: 1
					LoadBalancer *int `json:"load_balancer,omitempty"`

					// Node Example: 0
					Node *int `json:"node,omitempty"`

					// Vpc Example: 1
					Vpc *int `json:"vpc,omitempty"`
				} `json:"consumed_quota_details,omitempty"`

				// ConsumedResourcesQuota Example: 2
				ConsumedResourcesQuota *int `json:"consumed_resources_quota,omitempty"`

				// GpuAndHigherPlansEnabled Example: true
				GpuAndHigherPlansEnabled *bool `json:"gpu_and_higher_plans_enabled,omitempty"`

				// ResourceQuotaEnabled Example: true
				ResourceQuotaEnabled *bool `json:"resource_quota_enabled,omitempty"`

				// ResourceQuotaUsed Example: false
				ResourceQuotaUsed *bool `json:"resource_quota_used,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
