// Package other provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package other

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PostRequestLicenseParamsLocation.
const (
	Chennai PostRequestLicenseParamsLocation = "Chennai"
	Delhi   PostRequestLicenseParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostRequestLicenseParamsLocation enum.
func (e PostRequestLicenseParamsLocation) Valid() bool {
	switch e {
	case Chennai:
		return true
	case Delhi:
		return true
	default:
		return false
	}
}

// PostRequestLicenseJSONBody defines parameters for PostRequestLicense.
type PostRequestLicenseJSONBody struct {
	// ContactType Example:
	ContactType *string `json:"contact_type,omitempty"`

	// LicenseCount Example: 1
	LicenseCount int `json:"license_count"`

	// LicenseName Example: REMOTE DESKTOP LICENSE
	LicenseName string `json:"license_name"`

	// NodeId Example: 1
	NodeId int `json:"node_id"`

	// NodeOs Example: CentOS
	NodeOs string `json:"node_os"`

	// PrivateIp Example: 172.16.231.6
	PrivateIp string `json:"private_ip"`

	// PublicIp Example: 172.16.231.6
	PublicIp string `json:"public_ip"`

	// SkuId Example: 977
	SkuId string `json:"sku_id"`

	// Vcpus Example:
	Vcpus *string `json:"vcpus,omitempty"`
}

// PostRequestLicenseParams defines parameters for PostRequestLicense.
type PostRequestLicenseParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostRequestLicenseParamsLocation `form:"location" json:"location"`
}

// PostRequestLicenseParamsLocation defines parameters for PostRequestLicense.
type PostRequestLicenseParamsLocation string

// PostRequestLicenseJSONRequestBody defines body for PostRequestLicense for application/json ContentType.
type PostRequestLicenseJSONRequestBody PostRequestLicenseJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostRequestLicenseWithBody Buy New License
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
	PostRequestLicenseWithBody(ctx context.Context, params *PostRequestLicenseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRequestLicense Buy New License
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
	PostRequestLicense(ctx context.Context, params *PostRequestLicenseParams, body PostRequestLicenseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostRequestLicenseWithBody Buy New License
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
func (c *Client) PostRequestLicenseWithBody(ctx context.Context, params *PostRequestLicenseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestLicenseRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostRequestLicense Buy New License
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
func (c *Client) PostRequestLicense(ctx context.Context, params *PostRequestLicenseParams, body PostRequestLicenseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestLicenseRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostRequestLicenseRequest calls the generic PostRequestLicense builder with application/json body
func NewPostRequestLicenseRequest(server string, params *PostRequestLicenseParams, body PostRequestLicenseJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRequestLicenseRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostRequestLicenseRequestWithBody constructs an http.Request for the PostRequestLicense method, with any body, and a specified content type
func NewPostRequestLicenseRequestWithBody(server string, params *PostRequestLicenseParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/request-license/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostRequestLicenseWithBodyWithResponse Buy New License
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
	PostRequestLicenseWithBodyWithResponse(ctx context.Context, params *PostRequestLicenseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestLicenseResponse, error)

	// PostRequestLicenseWithResponse Buy New License
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
	PostRequestLicenseWithResponse(ctx context.Context, params *PostRequestLicenseParams, body PostRequestLicenseJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestLicenseResponse, error)
}

type PostRequestLicenseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// Message Example: Entered Public IP is not valid.
			Message *string `json:"message,omitempty"`

			// PublicIp Example: false
			PublicIp *bool `json:"public_ip,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostRequestLicenseResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// Message Example: Entered Public IP is not valid.
		Message *string `json:"message,omitempty"`

		// PublicIp Example: false
		PublicIp *bool `json:"public_ip,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostRequestLicenseResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostRequestLicenseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRequestLicenseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostRequestLicenseResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostRequestLicenseWithBodyWithResponse Buy New License
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
func (c *ClientWithResponses) PostRequestLicenseWithBodyWithResponse(ctx context.Context, params *PostRequestLicenseParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestLicenseResponse, error) {
	rsp, err := c.PostRequestLicenseWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestLicenseResponse(rsp)
}

// PostRequestLicenseWithResponse Buy New License
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/request-license/ (the `PostRequestLicense` operationId).
func (c *ClientWithResponses) PostRequestLicenseWithResponse(ctx context.Context, params *PostRequestLicenseParams, body PostRequestLicenseJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestLicenseResponse, error) {
	rsp, err := c.PostRequestLicense(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestLicenseResponse(rsp)
}

// ParsePostRequestLicenseResponse parses an HTTP response from a PostRequestLicenseWithResponse call
func ParsePostRequestLicenseResponse(rsp *http.Response) (*PostRequestLicenseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRequestLicenseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// Message Example: Entered Public IP is not valid.
				Message *string `json:"message,omitempty"`

				// PublicIp Example: false
				PublicIp *bool `json:"public_ip,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
