// Package backup provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backup

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetCdpbackupParamsLocation.
const (
	GetCdpbackupParamsLocationChennai GetCdpbackupParamsLocation = "Chennai"
	GetCdpbackupParamsLocationDelhi   GetCdpbackupParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetCdpbackupParamsLocation enum.
func (e GetCdpbackupParamsLocation) Valid() bool {
	switch e {
	case GetCdpbackupParamsLocationChennai:
		return true
	case GetCdpbackupParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutCdpbackupDeactivateNodeIdParamsLocation.
const (
	PutCdpbackupDeactivateNodeIdParamsLocationChennai PutCdpbackupDeactivateNodeIdParamsLocation = "Chennai"
	PutCdpbackupDeactivateNodeIdParamsLocationDelhi   PutCdpbackupDeactivateNodeIdParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PutCdpbackupDeactivateNodeIdParamsLocation enum.
func (e PutCdpbackupDeactivateNodeIdParamsLocation) Valid() bool {
	switch e {
	case PutCdpbackupDeactivateNodeIdParamsLocationChennai:
		return true
	case PutCdpbackupDeactivateNodeIdParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// GetCdpbackupParams defines parameters for GetCdpbackup.
type GetCdpbackupParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetCdpbackupParamsLocation `form:"location" json:"location"`
}

// GetCdpbackupParamsLocation defines parameters for GetCdpbackup.
type GetCdpbackupParamsLocation string

// ActivateBackupJSONBody defines parameters for ActivateBackup.
type ActivateBackupJSONBody struct {
	// BackupNow Flag to trigger an immediate backup when true.
	//
	// Example: true
	BackupNow *bool `json:"backup_now,omitempty"`

	// CompressionLevel Specifies the desired compression intensity for the backup operation.
	//
	// Example: Low
	CompressionLevel *string `json:"compression_level,omitempty"`

	// CompressionType Specifies the compression algorithm to use for the backup.
	//
	// Example: ZLib
	CompressionType *string `json:"compression_type,omitempty"`

	// DbEnabled Indicates whether the database backup should be enabled
	//
	// Example:
	DbEnabled *string `json:"db_enabled,omitempty"`

	// DbPassword Database password used for backup activation
	//
	// Example:
	DbPassword *string `json:"db_password,omitempty"`

	// DbUsername Database username for authentication
	//
	// Example:
	DbUsername *string `json:"db_username,omitempty"`

	// ExcludeFileFolder Path or pattern of files/folders to exclude from the backup
	//
	// Example:
	ExcludeFileFolder *string `json:"exclude_file_folder,omitempty"`

	// HoursOfDay Hours of the day when the backup should run, expressed as a comma-separated list of 0-23 values
	//
	// Example: 0,6,12,18
	HoursOfDay *string `json:"hoursOfDay,omitempty"`

	// IsEncryptionRequired Indicates whether encryption is required for the backup activation.
	//
	// Example: false
	IsEncryptionRequired *bool `json:"is_encryption_required,omitempty"`

	// PlanId Identifier of the backup plan to activate.
	//
	// Example: 1
	PlanId *int `json:"plan_id,omitempty"`

	// StartingMinute Minute of the hour when backup activation should start
	//
	// Example: 38
	StartingMinute *int `json:"startingMinute,omitempty"`

	// Type Specifies the backup activation schedule type.
	//
	// Example: HOURLY
	Type *string `json:"type,omitempty"`
}

// ActivateBackupParams defines parameters for ActivateBackup.
type ActivateBackupParams struct {
	// ProjectId Identifier of the project to scope the request to. Required integer project ID.
	ProjectId int `form:"project_id" json:"project_id"`

	// Apikey API key used for authentication
	Apikey string `form:"apikey" json:"apikey"`

	// Location Specifies the target location for activating the backup.
	Location string `form:"location" json:"location"`
}

// ConfigureDbBackupJSONBody defines parameters for ConfigureDbBackup.
type ConfigureDbBackupJSONBody struct {
	// DbPassword Database password used for backup configuration
	//
	// Example: admin@1234
	DbPassword *string `json:"db_password,omitempty"`

	// DbUsername Database username for backup configuration
	//
	// Example: admin
	DbUsername *string `json:"db_username,omitempty"`
}

// ConfigureDbBackupParams defines parameters for ConfigureDbBackup.
type ConfigureDbBackupParams struct {
	// ProjectId Identifier of the project to scope the request to. Required integer project ID.
	ProjectId int `form:"project_id" json:"project_id"`

	// Apikey API key used to authenticate the request
	Apikey string `form:"apikey" json:"apikey"`

	// Location Specifies the backup target location.
	Location string `form:"location" json:"location"`
}

// PutCdpbackupDeactivateNodeIdParams defines parameters for PutCdpbackupDeactivateNodeId.
type PutCdpbackupDeactivateNodeIdParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PutCdpbackupDeactivateNodeIdParamsLocation `form:"location" json:"location"`
}

// PutCdpbackupDeactivateNodeIdParamsLocation defines parameters for PutCdpbackupDeactivateNodeId.
type PutCdpbackupDeactivateNodeIdParamsLocation string

// BackupPlansParams defines parameters for BackupPlans.
type BackupPlansParams struct {
	// ProjectId Identifier of the project to scope the request to. Required integer project ID.
	ProjectId int `form:"project_id" json:"project_id"`

	// Apikey API key used to authenticate the request
	Apikey string `form:"apikey" json:"apikey"`

	// Location The geographic location for the backup plan.
	Location string `form:"location" json:"location"`
}

// CheckConnectionParams defines parameters for CheckConnection.
type CheckConnectionParams struct {
	// ProjectId Identifier of the project to scope the request to. Required integer project ID.
	ProjectId int `form:"project_id" json:"project_id"`

	// Apikey API key used to authenticate the request
	Apikey string `form:"apikey" json:"apikey"`

	// Location Location identifier used in the check connection request
	Location string `form:"location" json:"location"`
}

// BackupStatusParams defines parameters for BackupStatus.
type BackupStatusParams struct {
	// ProjectId Identifier of the project to scope the request to. Required integer project ID.
	ProjectId int `form:"project_id" json:"project_id"`

	// Apikey API key used to authenticate the backup status request
	Apikey string `form:"apikey" json:"apikey"`

	// Location Specifies the location for which to retrieve backup status.
	Location string `form:"location" json:"location"`
}

// UsageParams defines parameters for Usage.
type UsageParams struct {
	// ProjectId Identifier of the project to scope the request to. Required integer project ID.
	ProjectId int `form:"project_id" json:"project_id"`

	// Apikey API key used to authenticate the request
	Apikey string `form:"apikey" json:"apikey"`

	// Location Location filter for the usage query
	Location string `form:"location" json:"location"`
}

// ActivateBackupJSONRequestBody defines body for ActivateBackup for application/json ContentType.
type ActivateBackupJSONRequestBody ActivateBackupJSONBody

// ConfigureDbBackupJSONRequestBody defines body for ConfigureDbBackup for application/json ContentType.
type ConfigureDbBackupJSONRequestBody ConfigureDbBackupJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCdpbackup CDP Backup Listing
	//
	// Corresponds with GET /api/v1/cdpbackup/ (the `GetCdpbackup` operationId).
	GetCdpbackup(ctx context.Context, params *GetCdpbackupParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ActivateBackupWithBody Activate Backup
	//
	// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
	ActivateBackupWithBody(ctx context.Context, nodeId string, params *ActivateBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ActivateBackup Activate Backup
	//
	// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
	ActivateBackup(ctx context.Context, nodeId string, params *ActivateBackupParams, body ActivateBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfigureDbBackupWithBody Configure DB Backup
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
	ConfigureDbBackupWithBody(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfigureDbBackup Configure DB Backup
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
	ConfigureDbBackup(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, body ConfigureDbBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutCdpbackupDeactivateNodeId Deactivate CDP Backup
	//
	// Corresponds with PUT /api/v1/cdpbackup/deactivate/{node_id}/ (the `PutCdpbackupDeactivateNodeId` operationId).
	PutCdpbackupDeactivateNodeId(ctx context.Context, nodeId int, params *PutCdpbackupDeactivateNodeIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BackupPlans Backup Plans
	//
	// Corresponds with GET /api/v1/cdpbackup/plans/ (the `BackupPlans` operationId).
	BackupPlans(ctx context.Context, params *BackupPlansParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckConnection Check Connection
	//
	// This path + method also serves **Check Agent Connection** (`get-cdpbackup-node-id-cdp-agent`); select the variant via the request body.
	//
	// Corresponds with GET /api/v1/cdpbackup/{node_id}/cdp-agent/ (the `CheckConnection` operationId).
	CheckConnection(ctx context.Context, nodeId string, params *CheckConnectionParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BackupStatus Backup Status
	//
	// Corresponds with GET /api/v1/cdpbackup/{node_id}/status/ (the `BackupStatus` operationId).
	BackupStatus(ctx context.Context, nodeId string, params *BackupStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Usage Usage
	//
	// Corresponds with GET /api/v1/cdpbackup/{node_id}/usage/ (the `Usage` operationId).
	Usage(ctx context.Context, nodeId string, params *UsageParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCdpbackup CDP Backup Listing
//
// Corresponds with GET /api/v1/cdpbackup/ (the `GetCdpbackup` operationId).
func (c *Client) GetCdpbackup(ctx context.Context, params *GetCdpbackupParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCdpbackupRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ActivateBackupWithBody Activate Backup
//
// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
func (c *Client) ActivateBackupWithBody(ctx context.Context, nodeId string, params *ActivateBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActivateBackupRequestWithBody(c.Server, nodeId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ActivateBackup Activate Backup
//
// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
func (c *Client) ActivateBackup(ctx context.Context, nodeId string, params *ActivateBackupParams, body ActivateBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActivateBackupRequest(c.Server, nodeId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ConfigureDbBackupWithBody Configure DB Backup
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
func (c *Client) ConfigureDbBackupWithBody(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfigureDbBackupRequestWithBody(c.Server, nodeId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ConfigureDbBackup Configure DB Backup
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
func (c *Client) ConfigureDbBackup(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, body ConfigureDbBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfigureDbBackupRequest(c.Server, nodeId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutCdpbackupDeactivateNodeId Deactivate CDP Backup
//
// Corresponds with PUT /api/v1/cdpbackup/deactivate/{node_id}/ (the `PutCdpbackupDeactivateNodeId` operationId).
func (c *Client) PutCdpbackupDeactivateNodeId(ctx context.Context, nodeId int, params *PutCdpbackupDeactivateNodeIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutCdpbackupDeactivateNodeIdRequest(c.Server, nodeId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BackupPlans Backup Plans
//
// Corresponds with GET /api/v1/cdpbackup/plans/ (the `BackupPlans` operationId).
func (c *Client) BackupPlans(ctx context.Context, params *BackupPlansParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBackupPlansRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CheckConnection Check Connection
//
// This path + method also serves **Check Agent Connection** (`get-cdpbackup-node-id-cdp-agent`); select the variant via the request body.
//
// Corresponds with GET /api/v1/cdpbackup/{node_id}/cdp-agent/ (the `CheckConnection` operationId).
func (c *Client) CheckConnection(ctx context.Context, nodeId string, params *CheckConnectionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckConnectionRequest(c.Server, nodeId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BackupStatus Backup Status
//
// Corresponds with GET /api/v1/cdpbackup/{node_id}/status/ (the `BackupStatus` operationId).
func (c *Client) BackupStatus(ctx context.Context, nodeId string, params *BackupStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBackupStatusRequest(c.Server, nodeId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Usage Usage
//
// Corresponds with GET /api/v1/cdpbackup/{node_id}/usage/ (the `Usage` operationId).
func (c *Client) Usage(ctx context.Context, nodeId string, params *UsageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUsageRequest(c.Server, nodeId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCdpbackupRequest constructs an http.Request for the GetCdpbackup method
func NewGetCdpbackupRequest(server string, params *GetCdpbackupParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewActivateBackupRequest calls the generic ActivateBackup builder with application/json body
func NewActivateBackupRequest(server string, nodeId string, params *ActivateBackupParams, body ActivateBackupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewActivateBackupRequestWithBody(server, nodeId, params, "application/json", bodyReader)
}

// NewActivateBackupRequestWithBody constructs an http.Request for the ActivateBackup method, with any body, and a specified content type
func NewActivateBackupRequestWithBody(server string, nodeId string, params *ActivateBackupParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "node_id", nodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/activate/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apikey", params.Apikey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConfigureDbBackupRequest calls the generic ConfigureDbBackup builder with application/json body
func NewConfigureDbBackupRequest(server string, nodeId string, params *ConfigureDbBackupParams, body ConfigureDbBackupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConfigureDbBackupRequestWithBody(server, nodeId, params, "application/json", bodyReader)
}

// NewConfigureDbBackupRequestWithBody constructs an http.Request for the ConfigureDbBackup method, with any body, and a specified content type
func NewConfigureDbBackupRequestWithBody(server string, nodeId string, params *ConfigureDbBackupParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "node_id", nodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/database_update/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apikey", params.Apikey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutCdpbackupDeactivateNodeIdRequest constructs an http.Request for the PutCdpbackupDeactivateNodeId method
func NewPutCdpbackupDeactivateNodeIdRequest(server string, nodeId int, params *PutCdpbackupDeactivateNodeIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "node_id", nodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/deactivate/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBackupPlansRequest constructs an http.Request for the BackupPlans method
func NewBackupPlansRequest(server string, params *BackupPlansParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/plans/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apikey", params.Apikey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCheckConnectionRequest constructs an http.Request for the CheckConnection method
func NewCheckConnectionRequest(server string, nodeId string, params *CheckConnectionParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "node_id", nodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/%s/cdp-agent/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apikey", params.Apikey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBackupStatusRequest constructs an http.Request for the BackupStatus method
func NewBackupStatusRequest(server string, nodeId string, params *BackupStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "node_id", nodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/%s/status/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apikey", params.Apikey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUsageRequest constructs an http.Request for the Usage method
func NewUsageRequest(server string, nodeId string, params *UsageParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "node_id", nodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdpbackup/%s/usage/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "apikey", params.Apikey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCdpbackupWithResponse CDP Backup Listing
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/cdpbackup/ (the `GetCdpbackup` operationId).
	GetCdpbackupWithResponse(ctx context.Context, params *GetCdpbackupParams, reqEditors ...RequestEditorFn) (*GetCdpbackupResponse, error)

	// ActivateBackupWithBodyWithResponse Activate Backup
	//
	// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
	ActivateBackupWithBodyWithResponse(ctx context.Context, nodeId string, params *ActivateBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ActivateBackupResponse, error)

	// ActivateBackupWithResponse Activate Backup
	//
	// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
	ActivateBackupWithResponse(ctx context.Context, nodeId string, params *ActivateBackupParams, body ActivateBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*ActivateBackupResponse, error)

	// ConfigureDbBackupWithBodyWithResponse Configure DB Backup
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
	ConfigureDbBackupWithBodyWithResponse(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfigureDbBackupResponse, error)

	// ConfigureDbBackupWithResponse Configure DB Backup
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
	ConfigureDbBackupWithResponse(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, body ConfigureDbBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfigureDbBackupResponse, error)

	// PutCdpbackupDeactivateNodeIdWithResponse Deactivate CDP Backup
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdpbackup/deactivate/{node_id}/ (the `PutCdpbackupDeactivateNodeId` operationId).
	PutCdpbackupDeactivateNodeIdWithResponse(ctx context.Context, nodeId int, params *PutCdpbackupDeactivateNodeIdParams, reqEditors ...RequestEditorFn) (*PutCdpbackupDeactivateNodeIdResponse, error)

	// BackupPlansWithResponse Backup Plans
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/cdpbackup/plans/ (the `BackupPlans` operationId).
	BackupPlansWithResponse(ctx context.Context, params *BackupPlansParams, reqEditors ...RequestEditorFn) (*BackupPlansResponse, error)

	// CheckConnectionWithResponse Check Connection
	//
	// This path + method also serves **Check Agent Connection** (`get-cdpbackup-node-id-cdp-agent`); select the variant via the request body.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/cdpbackup/{node_id}/cdp-agent/ (the `CheckConnection` operationId).
	CheckConnectionWithResponse(ctx context.Context, nodeId string, params *CheckConnectionParams, reqEditors ...RequestEditorFn) (*CheckConnectionResponse, error)

	// BackupStatusWithResponse Backup Status
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/cdpbackup/{node_id}/status/ (the `BackupStatus` operationId).
	BackupStatusWithResponse(ctx context.Context, nodeId string, params *BackupStatusParams, reqEditors ...RequestEditorFn) (*BackupStatusResponse, error)

	// UsageWithResponse Usage
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/cdpbackup/{node_id}/usage/ (the `Usage` operationId).
	UsageWithResponse(ctx context.Context, nodeId string, params *UsageParams, reqEditors ...RequestEditorFn) (*UsageResponse, error)
}

type GetCdpbackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			AuditLogMessage *string `json:"audit_log_message,omitempty"`

			// BackupDetailId Example: 13886
			BackupDetailId *int `json:"backup_detail_id,omitempty"`
			BackupStatus   *struct {
				// Detail Example: Not Activated
				Detail *string `json:"detail,omitempty"`

				// IsEncryptionEnabled Example: false
				IsEncryptionEnabled *bool `json:"is_encryption_enabled,omitempty"`

				// NodeId Example: 232063
				NodeId *int `json:"node_id,omitempty"`

				// Status Example: backup_not_activated
				Status *string `json:"status,omitempty"`
			} `json:"backup_status,omitempty"`

			// Id Example: 232063
			Id *int `json:"id,omitempty"`

			// Label Example: default
			Label                      *string    `json:"label,omitempty"`
			LastRecoveryPointCreatedOn *time.Time `json:"last_recovery_point_created_on,omitempty"`

			// Name Example: C3-8GB-985
			Name *string `json:"name,omitempty"`

			// NodeId Example: 232063
			NodeId *int `json:"node_id,omitempty"`

			// Plan Example: C3.8GB
			Plan *string `json:"plan,omitempty"`

			// PrivateIpAddress Example: 10.14.168.8
			PrivateIpAddress *string `json:"private_ip_address,omitempty"`

			// ProjectName Example: sdfghj
			ProjectName *string `json:"project_name,omitempty"`

			// PublicIpAddress Example: 164.52.195.207
			PublicIpAddress *string `json:"public_ip_address,omitempty"`
			Region          *string `json:"region,omitempty"`

			// Status Example: Running
			Status *string `json:"status,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCdpbackupResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		AuditLogMessage *string `json:"audit_log_message,omitempty"`

		// BackupDetailId Example: 13886
		BackupDetailId *int `json:"backup_detail_id,omitempty"`
		BackupStatus   *struct {
			// Detail Example: Not Activated
			Detail *string `json:"detail,omitempty"`

			// IsEncryptionEnabled Example: false
			IsEncryptionEnabled *bool `json:"is_encryption_enabled,omitempty"`

			// NodeId Example: 232063
			NodeId *int `json:"node_id,omitempty"`

			// Status Example: backup_not_activated
			Status *string `json:"status,omitempty"`
		} `json:"backup_status,omitempty"`

		// Id Example: 232063
		Id *int `json:"id,omitempty"`

		// Label Example: default
		Label                      *string    `json:"label,omitempty"`
		LastRecoveryPointCreatedOn *time.Time `json:"last_recovery_point_created_on,omitempty"`

		// Name Example: C3-8GB-985
		Name *string `json:"name,omitempty"`

		// NodeId Example: 232063
		NodeId *int `json:"node_id,omitempty"`

		// Plan Example: C3.8GB
		Plan *string `json:"plan,omitempty"`

		// PrivateIpAddress Example: 10.14.168.8
		PrivateIpAddress *string `json:"private_ip_address,omitempty"`

		// ProjectName Example: sdfghj
		ProjectName *string `json:"project_name,omitempty"`

		// PublicIpAddress Example: 164.52.195.207
		PublicIpAddress *string `json:"public_ip_address,omitempty"`
		Region          *string `json:"region,omitempty"`

		// Status Example: Running
		Status *string `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetCdpbackupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCdpbackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCdpbackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCdpbackupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ActivateBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code HTTP status code returned by the Activate Backup operation
		//
		// Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// SupportTicketCreated Indicates whether a support ticket was created during the backup activation
			//
			// Example: true
			SupportTicketCreated *bool `json:"support_ticket_created,omitempty"`
		} `json:"data,omitempty"`
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Human-readable status message confirming activation of backup.
		//
		// Example: Your backups will begin shortly.
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ActivateBackupResponse) GetJSON200() *struct {
	// Code HTTP status code returned by the Activate Backup operation
	//
	// Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// SupportTicketCreated Indicates whether a support ticket was created during the backup activation
		//
		// Example: true
		SupportTicketCreated *bool `json:"support_ticket_created,omitempty"`
	} `json:"data,omitempty"`
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Human-readable status message confirming activation of backup.
	//
	// Example: Your backups will begin shortly.
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ActivateBackupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ActivateBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ActivateBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ActivateBackupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ConfigureDbBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code HTTP status code of the Configure DB Backup response
		//
		// Example: 200
		Code *int `json:"code,omitempty"`

		// Data Result message for the DB backup configuration request.
		//
		// Example: Database settings has been updated successfully.
		Data   *string                 `json:"data,omitempty"`
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Status message indicating the result of the backup configuration request.
		//
		// Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ConfigureDbBackupResponse) GetJSON200() *struct {
	// Code HTTP status code of the Configure DB Backup response
	//
	// Example: 200
	Code *int `json:"code,omitempty"`

	// Data Result message for the DB backup configuration request.
	//
	// Example: Database settings has been updated successfully.
	Data   *string                 `json:"data,omitempty"`
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Status message indicating the result of the backup configuration request.
	//
	// Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ConfigureDbBackupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ConfigureDbBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfigureDbBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConfigureDbBackupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutCdpbackupDeactivateNodeIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PutCdpbackupDeactivateNodeIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutCdpbackupDeactivateNodeIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutCdpbackupDeactivateNodeIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutCdpbackupDeactivateNodeIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BackupPlansResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// CanActivateBackup Indicates whether the backup plan can be activated
		//
		// Example: true
		CanActivateBackup *bool `json:"can_activate_backup,omitempty"`

		// Code HTTP status code indicating the result of the backup plan request
		//
		// Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// HourlyInterval Number of hours between each backup execution
			//
			// Example: 6
			HourlyInterval *int `json:"hourly_interval,omitempty"`

			// PlanId Identifier of the backup plan
			//
			// Example: 1
			PlanId *int `json:"plan_id,omitempty"`

			// PlanName Name of the backup plan
			//
			// Example: Regular Plan
			PlanName *string `json:"plan_name,omitempty"`

			// PlanType type identifier of the backup plan
			//
			// Example: DEFAULT
			PlanType          *string `json:"plan_type,omitempty"`
			RetentionSettings *struct {
				// DailyLimit Maximum number of daily backups to retain
				//
				// Example: 14
				DailyLimit *int `json:"dailyLimit,omitempty"`

				// HourlyLimit Maximum number of hourly backups to retain
				//
				// Example: 12
				HourlyLimit *int `json:"hourlyLimit,omitempty"`

				// MonthlyLimit Maximum number of monthly backups to retain
				//
				// Example: 2
				MonthlyLimit *int `json:"monthlyLimit,omitempty"`

				// WeeklyLimit Maximum number of weekly backups to retain
				//
				// Example: 4
				WeeklyLimit *int `json:"weeklyLimit,omitempty"`

				// YearlyLimit Maximum number of yearly backups to retain
				//
				// Example: 0
				YearlyLimit *int `json:"yearlyLimit,omitempty"`
			} `json:"retention_settings,omitempty"`

			// ScheduleType type of backup schedule (e.g., HOURLY)
			//
			// Example: HOURLY
			ScheduleType *string `json:"schedule_type,omitempty"`
		} `json:"data,omitempty"`
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Status message indicating the result of the backup plan operation
		//
		// Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BackupPlansResponse) GetJSON200() *struct {
	// CanActivateBackup Indicates whether the backup plan can be activated
	//
	// Example: true
	CanActivateBackup *bool `json:"can_activate_backup,omitempty"`

	// Code HTTP status code indicating the result of the backup plan request
	//
	// Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// HourlyInterval Number of hours between each backup execution
		//
		// Example: 6
		HourlyInterval *int `json:"hourly_interval,omitempty"`

		// PlanId Identifier of the backup plan
		//
		// Example: 1
		PlanId *int `json:"plan_id,omitempty"`

		// PlanName Name of the backup plan
		//
		// Example: Regular Plan
		PlanName *string `json:"plan_name,omitempty"`

		// PlanType type identifier of the backup plan
		//
		// Example: DEFAULT
		PlanType          *string `json:"plan_type,omitempty"`
		RetentionSettings *struct {
			// DailyLimit Maximum number of daily backups to retain
			//
			// Example: 14
			DailyLimit *int `json:"dailyLimit,omitempty"`

			// HourlyLimit Maximum number of hourly backups to retain
			//
			// Example: 12
			HourlyLimit *int `json:"hourlyLimit,omitempty"`

			// MonthlyLimit Maximum number of monthly backups to retain
			//
			// Example: 2
			MonthlyLimit *int `json:"monthlyLimit,omitempty"`

			// WeeklyLimit Maximum number of weekly backups to retain
			//
			// Example: 4
			WeeklyLimit *int `json:"weeklyLimit,omitempty"`

			// YearlyLimit Maximum number of yearly backups to retain
			//
			// Example: 0
			YearlyLimit *int `json:"yearlyLimit,omitempty"`
		} `json:"retention_settings,omitempty"`

		// ScheduleType type of backup schedule (e.g., HOURLY)
		//
		// Example: HOURLY
		ScheduleType *string `json:"schedule_type,omitempty"`
	} `json:"data,omitempty"`
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Status message indicating the result of the backup plan operation
	//
	// Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r BackupPlansResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BackupPlansResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BackupPlansResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BackupPlansResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckConnectionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code HTTP status code indicating the result of the connection check
		//
		// Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// ConnectionStatus Indicates whether the connection check succeeded
			//
			// Example: false
			ConnectionStatus *bool `json:"connection_status,omitempty"`

			// Message Human-readable status or error message for the connection check
			//
			// Example: Connecting to agent failed.
			Message *string `json:"message,omitempty"`
		} `json:"data,omitempty"`
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Status message indicating the result of the connection check
		//
		// Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CheckConnectionResponse) GetJSON200() *struct {
	// Code HTTP status code indicating the result of the connection check
	//
	// Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// ConnectionStatus Indicates whether the connection check succeeded
		//
		// Example: false
		ConnectionStatus *bool `json:"connection_status,omitempty"`

		// Message Human-readable status or error message for the connection check
		//
		// Example: Connecting to agent failed.
		Message *string `json:"message,omitempty"`
	} `json:"data,omitempty"`
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Status message indicating the result of the connection check
	//
	// Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r CheckConnectionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CheckConnectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckConnectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckConnectionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BackupStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code HTTP status code for backup operation
		//
		// Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// Detail Backup status detail string
			//
			// Example: Not Activated
			Detail *string `json:"detail,omitempty"`

			// NodeId Unique identifier of the node in the backup status response
			//
			// Example: 12345
			NodeId *int `json:"node_id,omitempty"`

			// Status Indicates the current backup status for the item.
			//
			// Example: backup_not_activated
			Status *string `json:"status,omitempty"`
		} `json:"data,omitempty"`
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Status message indicating the result of the backup operation
		//
		// Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BackupStatusResponse) GetJSON200() *struct {
	// Code HTTP status code for backup operation
	//
	// Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// Detail Backup status detail string
		//
		// Example: Not Activated
		Detail *string `json:"detail,omitempty"`

		// NodeId Unique identifier of the node in the backup status response
		//
		// Example: 12345
		NodeId *int `json:"node_id,omitempty"`

		// Status Indicates the current backup status for the item.
		//
		// Example: backup_not_activated
		Status *string `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Status message indicating the result of the backup operation
	//
	// Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r BackupStatusResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BackupStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BackupStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BackupStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code HTTP status code of the usage response
		//
		// Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			ActivePlanDetails *struct {
				// HourlyInterval Number of hours between each usage reporting interval
				//
				// Example: 6
				HourlyInterval *int `json:"hourly_interval,omitempty"`

				// PlanId Identifier of the active plan
				//
				// Example: 1
				PlanId *int `json:"plan_id,omitempty"`

				// PlanName Name of the active usage plan
				//
				// Example: Regular Plan
				PlanName *string `json:"plan_name,omitempty"`
			} `json:"active_plan_details,omitempty"`

			// CompressionLevel Indicates the level of compression applied to the usage data.
			//
			// Example: LOW
			CompressionLevel *string `json:"compression_level,omitempty"`

			// CompressionType Specifies the compression algorithm applied to the response data.
			//
			// Example: ZLIB
			CompressionType *string `json:"compression_type,omitempty"`

			// DatabaseBackupEnabled Indicates whether database backups are enabled.
			//
			// Example: false
			DatabaseBackupEnabled *bool `json:"database_backup_enabled,omitempty"`

			// ErrorMessage Human-readable error message describing a usage request failure
			//
			// Example:
			ErrorMessage *string `json:"error_message,omitempty"`

			// ExcludeFileFolder Path of a file or folder to be excluded from usage calculations
			//
			// Example:
			ExcludeFileFolder *string `json:"exclude_file_folder,omitempty"`
			Frequency         *struct {
				// Timezone Time zone of the usage frequency
				//
				// Example: UTC
				Timezone *string `json:"timezone,omitempty"`

				// Type Frequency type of the usage data
				//
				// Example: HOURLY
				Type  *string `json:"type,omitempty"`
				Value *struct {
					HoursOfDay *[]int `json:"hoursOfDay,omitempty"`

					// StartingMinute The minute of the hour when the frequency period starts.
					//
					// Example: 38
					StartingMinute *int `json:"startingMinute,omitempty"`
				} `json:"value,omitempty"`
			} `json:"frequency,omitempty"`

			// IsArchivedPolicyActive Indicates whether the archived policy is currently active.
			//
			// Example: false
			IsArchivedPolicyActive *bool `json:"is_archived_policy_active,omitempty"`

			// IsEncryptionApplied Indicates whether encryption was applied to the usage data
			//
			// Example: false
			IsEncryptionApplied *bool `json:"is_encryption_applied,omitempty"`

			// IsWindowPlan Indicates whether the usage plan is a window plan.
			//
			// Example: false
			IsWindowPlan *bool `json:"is_window_plan,omitempty"`

			// LastRunTime Timestamp of the last run in human-readable format
			//
			// Example: 21 July, 2025 14:19
			LastRunTime    *string `json:"last_run_time,omitempty"`
			LastTaskStatus *struct {
				// FailedDate Date when the last task failed
				//
				// Example:
				FailedDate *string `json:"failed_date,omitempty"`

				// Message Human-readable status message for the last task
				//
				// Example: Connecting to agent failed
				Message *string `json:"message,omitempty"`

				// TaskStatus Indicates whether the last task completed successfully
				//
				// Example: false
				TaskStatus *bool `json:"task_status,omitempty"`
			} `json:"last_task_status,omitempty"`
			LocalRetentionPoints *struct {
				// DailyLimit Maximum number of days data is retained locally
				//
				// Example: 14
				DailyLimit *int `json:"daily_limit,omitempty"`

				// HourlyLimit Maximum number of hourly retention points allowed
				//
				// Example: 12
				HourlyLimit *int `json:"hourly_limit,omitempty"`

				// MonthlyLimit Maximum number of local retention points allowed per month.
				//
				// Example: 2
				MonthlyLimit *int `json:"monthly_limit,omitempty"`

				// WeeklyLimit Maximum number of weeks allowed for local retention points
				//
				// Example: 4
				WeeklyLimit *int `json:"weekly_limit,omitempty"`

				// YearlyLimit Annual retention points limit.
				//
				// Example: 0
				YearlyLimit *int `json:"yearly_limit,omitempty"`
			} `json:"local_retention_points,omitempty"`

			// NextRunTime Timestamp of the next scheduled run
			//
			// Example: 21 July, 2025 18:38
			NextRunTime *string `json:"next_run_time,omitempty"`

			// Size Size of the usage data as a human-readable string
			//
			// Example: 6525.0 Bytes
			Size *string `json:"size,omitempty"`

			// Status Indicates the result status of the usage request
			//
			// Example: ERROR
			Status *string `json:"status,omitempty"`
		} `json:"data,omitempty"`
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Status message indicating the result of the request
		//
		// Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UsageResponse) GetJSON200() *struct {
	// Code HTTP status code of the usage response
	//
	// Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		ActivePlanDetails *struct {
			// HourlyInterval Number of hours between each usage reporting interval
			//
			// Example: 6
			HourlyInterval *int `json:"hourly_interval,omitempty"`

			// PlanId Identifier of the active plan
			//
			// Example: 1
			PlanId *int `json:"plan_id,omitempty"`

			// PlanName Name of the active usage plan
			//
			// Example: Regular Plan
			PlanName *string `json:"plan_name,omitempty"`
		} `json:"active_plan_details,omitempty"`

		// CompressionLevel Indicates the level of compression applied to the usage data.
		//
		// Example: LOW
		CompressionLevel *string `json:"compression_level,omitempty"`

		// CompressionType Specifies the compression algorithm applied to the response data.
		//
		// Example: ZLIB
		CompressionType *string `json:"compression_type,omitempty"`

		// DatabaseBackupEnabled Indicates whether database backups are enabled.
		//
		// Example: false
		DatabaseBackupEnabled *bool `json:"database_backup_enabled,omitempty"`

		// ErrorMessage Human-readable error message describing a usage request failure
		//
		// Example:
		ErrorMessage *string `json:"error_message,omitempty"`

		// ExcludeFileFolder Path of a file or folder to be excluded from usage calculations
		//
		// Example:
		ExcludeFileFolder *string `json:"exclude_file_folder,omitempty"`
		Frequency         *struct {
			// Timezone Time zone of the usage frequency
			//
			// Example: UTC
			Timezone *string `json:"timezone,omitempty"`

			// Type Frequency type of the usage data
			//
			// Example: HOURLY
			Type  *string `json:"type,omitempty"`
			Value *struct {
				HoursOfDay *[]int `json:"hoursOfDay,omitempty"`

				// StartingMinute The minute of the hour when the frequency period starts.
				//
				// Example: 38
				StartingMinute *int `json:"startingMinute,omitempty"`
			} `json:"value,omitempty"`
		} `json:"frequency,omitempty"`

		// IsArchivedPolicyActive Indicates whether the archived policy is currently active.
		//
		// Example: false
		IsArchivedPolicyActive *bool `json:"is_archived_policy_active,omitempty"`

		// IsEncryptionApplied Indicates whether encryption was applied to the usage data
		//
		// Example: false
		IsEncryptionApplied *bool `json:"is_encryption_applied,omitempty"`

		// IsWindowPlan Indicates whether the usage plan is a window plan.
		//
		// Example: false
		IsWindowPlan *bool `json:"is_window_plan,omitempty"`

		// LastRunTime Timestamp of the last run in human-readable format
		//
		// Example: 21 July, 2025 14:19
		LastRunTime    *string `json:"last_run_time,omitempty"`
		LastTaskStatus *struct {
			// FailedDate Date when the last task failed
			//
			// Example:
			FailedDate *string `json:"failed_date,omitempty"`

			// Message Human-readable status message for the last task
			//
			// Example: Connecting to agent failed
			Message *string `json:"message,omitempty"`

			// TaskStatus Indicates whether the last task completed successfully
			//
			// Example: false
			TaskStatus *bool `json:"task_status,omitempty"`
		} `json:"last_task_status,omitempty"`
		LocalRetentionPoints *struct {
			// DailyLimit Maximum number of days data is retained locally
			//
			// Example: 14
			DailyLimit *int `json:"daily_limit,omitempty"`

			// HourlyLimit Maximum number of hourly retention points allowed
			//
			// Example: 12
			HourlyLimit *int `json:"hourly_limit,omitempty"`

			// MonthlyLimit Maximum number of local retention points allowed per month.
			//
			// Example: 2
			MonthlyLimit *int `json:"monthly_limit,omitempty"`

			// WeeklyLimit Maximum number of weeks allowed for local retention points
			//
			// Example: 4
			WeeklyLimit *int `json:"weekly_limit,omitempty"`

			// YearlyLimit Annual retention points limit.
			//
			// Example: 0
			YearlyLimit *int `json:"yearly_limit,omitempty"`
		} `json:"local_retention_points,omitempty"`

		// NextRunTime Timestamp of the next scheduled run
		//
		// Example: 21 July, 2025 18:38
		NextRunTime *string `json:"next_run_time,omitempty"`

		// Size Size of the usage data as a human-readable string
		//
		// Example: 6525.0 Bytes
		Size *string `json:"size,omitempty"`

		// Status Indicates the result status of the usage request
		//
		// Example: ERROR
		Status *string `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Status message indicating the result of the request
	//
	// Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r UsageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UsageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCdpbackupWithResponse CDP Backup Listing
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/cdpbackup/ (the `GetCdpbackup` operationId).
func (c *ClientWithResponses) GetCdpbackupWithResponse(ctx context.Context, params *GetCdpbackupParams, reqEditors ...RequestEditorFn) (*GetCdpbackupResponse, error) {
	rsp, err := c.GetCdpbackup(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCdpbackupResponse(rsp)
}

// ActivateBackupWithBodyWithResponse Activate Backup
//
// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
func (c *ClientWithResponses) ActivateBackupWithBodyWithResponse(ctx context.Context, nodeId string, params *ActivateBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ActivateBackupResponse, error) {
	rsp, err := c.ActivateBackupWithBody(ctx, nodeId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActivateBackupResponse(rsp)
}

// ActivateBackupWithResponse Activate Backup
//
// This path + method also serves **Activate CDP Backup** (`put-cdpbackup-activate-node-id`); select the variant via the request body.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdpbackup/activate/{node_id}/ (the `ActivateBackup` operationId).
func (c *ClientWithResponses) ActivateBackupWithResponse(ctx context.Context, nodeId string, params *ActivateBackupParams, body ActivateBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*ActivateBackupResponse, error) {
	rsp, err := c.ActivateBackup(ctx, nodeId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActivateBackupResponse(rsp)
}

// ConfigureDbBackupWithBodyWithResponse Configure DB Backup
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
func (c *ClientWithResponses) ConfigureDbBackupWithBodyWithResponse(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConfigureDbBackupResponse, error) {
	rsp, err := c.ConfigureDbBackupWithBody(ctx, nodeId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfigureDbBackupResponse(rsp)
}

// ConfigureDbBackupWithResponse Configure DB Backup
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdpbackup/database_update/{node_id}/ (the `ConfigureDbBackup` operationId).
func (c *ClientWithResponses) ConfigureDbBackupWithResponse(ctx context.Context, nodeId string, params *ConfigureDbBackupParams, body ConfigureDbBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*ConfigureDbBackupResponse, error) {
	rsp, err := c.ConfigureDbBackup(ctx, nodeId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfigureDbBackupResponse(rsp)
}

// PutCdpbackupDeactivateNodeIdWithResponse Deactivate CDP Backup
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdpbackup/deactivate/{node_id}/ (the `PutCdpbackupDeactivateNodeId` operationId).
func (c *ClientWithResponses) PutCdpbackupDeactivateNodeIdWithResponse(ctx context.Context, nodeId int, params *PutCdpbackupDeactivateNodeIdParams, reqEditors ...RequestEditorFn) (*PutCdpbackupDeactivateNodeIdResponse, error) {
	rsp, err := c.PutCdpbackupDeactivateNodeId(ctx, nodeId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutCdpbackupDeactivateNodeIdResponse(rsp)
}

// BackupPlansWithResponse Backup Plans
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/cdpbackup/plans/ (the `BackupPlans` operationId).
func (c *ClientWithResponses) BackupPlansWithResponse(ctx context.Context, params *BackupPlansParams, reqEditors ...RequestEditorFn) (*BackupPlansResponse, error) {
	rsp, err := c.BackupPlans(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBackupPlansResponse(rsp)
}

// CheckConnectionWithResponse Check Connection
//
// This path + method also serves **Check Agent Connection** (`get-cdpbackup-node-id-cdp-agent`); select the variant via the request body.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/cdpbackup/{node_id}/cdp-agent/ (the `CheckConnection` operationId).
func (c *ClientWithResponses) CheckConnectionWithResponse(ctx context.Context, nodeId string, params *CheckConnectionParams, reqEditors ...RequestEditorFn) (*CheckConnectionResponse, error) {
	rsp, err := c.CheckConnection(ctx, nodeId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckConnectionResponse(rsp)
}

// BackupStatusWithResponse Backup Status
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/cdpbackup/{node_id}/status/ (the `BackupStatus` operationId).
func (c *ClientWithResponses) BackupStatusWithResponse(ctx context.Context, nodeId string, params *BackupStatusParams, reqEditors ...RequestEditorFn) (*BackupStatusResponse, error) {
	rsp, err := c.BackupStatus(ctx, nodeId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBackupStatusResponse(rsp)
}

// UsageWithResponse Usage
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/cdpbackup/{node_id}/usage/ (the `Usage` operationId).
func (c *ClientWithResponses) UsageWithResponse(ctx context.Context, nodeId string, params *UsageParams, reqEditors ...RequestEditorFn) (*UsageResponse, error) {
	rsp, err := c.Usage(ctx, nodeId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUsageResponse(rsp)
}

// ParseGetCdpbackupResponse parses an HTTP response from a GetCdpbackupWithResponse call
func ParseGetCdpbackupResponse(rsp *http.Response) (*GetCdpbackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCdpbackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				AuditLogMessage *string `json:"audit_log_message,omitempty"`

				// BackupDetailId Example: 13886
				BackupDetailId *int `json:"backup_detail_id,omitempty"`
				BackupStatus   *struct {
					// Detail Example: Not Activated
					Detail *string `json:"detail,omitempty"`

					// IsEncryptionEnabled Example: false
					IsEncryptionEnabled *bool `json:"is_encryption_enabled,omitempty"`

					// NodeId Example: 232063
					NodeId *int `json:"node_id,omitempty"`

					// Status Example: backup_not_activated
					Status *string `json:"status,omitempty"`
				} `json:"backup_status,omitempty"`

				// Id Example: 232063
				Id *int `json:"id,omitempty"`

				// Label Example: default
				Label                      *string    `json:"label,omitempty"`
				LastRecoveryPointCreatedOn *time.Time `json:"last_recovery_point_created_on,omitempty"`

				// Name Example: C3-8GB-985
				Name *string `json:"name,omitempty"`

				// NodeId Example: 232063
				NodeId *int `json:"node_id,omitempty"`

				// Plan Example: C3.8GB
				Plan *string `json:"plan,omitempty"`

				// PrivateIpAddress Example: 10.14.168.8
				PrivateIpAddress *string `json:"private_ip_address,omitempty"`

				// ProjectName Example: sdfghj
				ProjectName *string `json:"project_name,omitempty"`

				// PublicIpAddress Example: 164.52.195.207
				PublicIpAddress *string `json:"public_ip_address,omitempty"`
				Region          *string `json:"region,omitempty"`

				// Status Example: Running
				Status *string `json:"status,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseActivateBackupResponse parses an HTTP response from a ActivateBackupWithResponse call
func ParseActivateBackupResponse(rsp *http.Response) (*ActivateBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ActivateBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code HTTP status code returned by the Activate Backup operation
			//
			// Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// SupportTicketCreated Indicates whether a support ticket was created during the backup activation
				//
				// Example: true
				SupportTicketCreated *bool `json:"support_ticket_created,omitempty"`
			} `json:"data,omitempty"`
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Human-readable status message confirming activation of backup.
			//
			// Example: Your backups will begin shortly.
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseConfigureDbBackupResponse parses an HTTP response from a ConfigureDbBackupWithResponse call
func ParseConfigureDbBackupResponse(rsp *http.Response) (*ConfigureDbBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfigureDbBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code HTTP status code of the Configure DB Backup response
			//
			// Example: 200
			Code *int `json:"code,omitempty"`

			// Data Result message for the DB backup configuration request.
			//
			// Example: Database settings has been updated successfully.
			Data   *string                 `json:"data,omitempty"`
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Status message indicating the result of the backup configuration request.
			//
			// Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutCdpbackupDeactivateNodeIdResponse parses an HTTP response from a PutCdpbackupDeactivateNodeIdWithResponse call
func ParsePutCdpbackupDeactivateNodeIdResponse(rsp *http.Response) (*PutCdpbackupDeactivateNodeIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutCdpbackupDeactivateNodeIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseBackupPlansResponse parses an HTTP response from a BackupPlansWithResponse call
func ParseBackupPlansResponse(rsp *http.Response) (*BackupPlansResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BackupPlansResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// CanActivateBackup Indicates whether the backup plan can be activated
			//
			// Example: true
			CanActivateBackup *bool `json:"can_activate_backup,omitempty"`

			// Code HTTP status code indicating the result of the backup plan request
			//
			// Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// HourlyInterval Number of hours between each backup execution
				//
				// Example: 6
				HourlyInterval *int `json:"hourly_interval,omitempty"`

				// PlanId Identifier of the backup plan
				//
				// Example: 1
				PlanId *int `json:"plan_id,omitempty"`

				// PlanName Name of the backup plan
				//
				// Example: Regular Plan
				PlanName *string `json:"plan_name,omitempty"`

				// PlanType type identifier of the backup plan
				//
				// Example: DEFAULT
				PlanType          *string `json:"plan_type,omitempty"`
				RetentionSettings *struct {
					// DailyLimit Maximum number of daily backups to retain
					//
					// Example: 14
					DailyLimit *int `json:"dailyLimit,omitempty"`

					// HourlyLimit Maximum number of hourly backups to retain
					//
					// Example: 12
					HourlyLimit *int `json:"hourlyLimit,omitempty"`

					// MonthlyLimit Maximum number of monthly backups to retain
					//
					// Example: 2
					MonthlyLimit *int `json:"monthlyLimit,omitempty"`

					// WeeklyLimit Maximum number of weekly backups to retain
					//
					// Example: 4
					WeeklyLimit *int `json:"weeklyLimit,omitempty"`

					// YearlyLimit Maximum number of yearly backups to retain
					//
					// Example: 0
					YearlyLimit *int `json:"yearlyLimit,omitempty"`
				} `json:"retention_settings,omitempty"`

				// ScheduleType type of backup schedule (e.g., HOURLY)
				//
				// Example: HOURLY
				ScheduleType *string `json:"schedule_type,omitempty"`
			} `json:"data,omitempty"`
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Status message indicating the result of the backup plan operation
			//
			// Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCheckConnectionResponse parses an HTTP response from a CheckConnectionWithResponse call
func ParseCheckConnectionResponse(rsp *http.Response) (*CheckConnectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckConnectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code HTTP status code indicating the result of the connection check
			//
			// Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// ConnectionStatus Indicates whether the connection check succeeded
				//
				// Example: false
				ConnectionStatus *bool `json:"connection_status,omitempty"`

				// Message Human-readable status or error message for the connection check
				//
				// Example: Connecting to agent failed.
				Message *string `json:"message,omitempty"`
			} `json:"data,omitempty"`
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Status message indicating the result of the connection check
			//
			// Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBackupStatusResponse parses an HTTP response from a BackupStatusWithResponse call
func ParseBackupStatusResponse(rsp *http.Response) (*BackupStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BackupStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code HTTP status code for backup operation
			//
			// Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// Detail Backup status detail string
				//
				// Example: Not Activated
				Detail *string `json:"detail,omitempty"`

				// NodeId Unique identifier of the node in the backup status response
				//
				// Example: 12345
				NodeId *int `json:"node_id,omitempty"`

				// Status Indicates the current backup status for the item.
				//
				// Example: backup_not_activated
				Status *string `json:"status,omitempty"`
			} `json:"data,omitempty"`
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Status message indicating the result of the backup operation
			//
			// Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUsageResponse parses an HTTP response from a UsageWithResponse call
func ParseUsageResponse(rsp *http.Response) (*UsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code HTTP status code of the usage response
			//
			// Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				ActivePlanDetails *struct {
					// HourlyInterval Number of hours between each usage reporting interval
					//
					// Example: 6
					HourlyInterval *int `json:"hourly_interval,omitempty"`

					// PlanId Identifier of the active plan
					//
					// Example: 1
					PlanId *int `json:"plan_id,omitempty"`

					// PlanName Name of the active usage plan
					//
					// Example: Regular Plan
					PlanName *string `json:"plan_name,omitempty"`
				} `json:"active_plan_details,omitempty"`

				// CompressionLevel Indicates the level of compression applied to the usage data.
				//
				// Example: LOW
				CompressionLevel *string `json:"compression_level,omitempty"`

				// CompressionType Specifies the compression algorithm applied to the response data.
				//
				// Example: ZLIB
				CompressionType *string `json:"compression_type,omitempty"`

				// DatabaseBackupEnabled Indicates whether database backups are enabled.
				//
				// Example: false
				DatabaseBackupEnabled *bool `json:"database_backup_enabled,omitempty"`

				// ErrorMessage Human-readable error message describing a usage request failure
				//
				// Example:
				ErrorMessage *string `json:"error_message,omitempty"`

				// ExcludeFileFolder Path of a file or folder to be excluded from usage calculations
				//
				// Example:
				ExcludeFileFolder *string `json:"exclude_file_folder,omitempty"`
				Frequency         *struct {
					// Timezone Time zone of the usage frequency
					//
					// Example: UTC
					Timezone *string `json:"timezone,omitempty"`

					// Type Frequency type of the usage data
					//
					// Example: HOURLY
					Type  *string `json:"type,omitempty"`
					Value *struct {
						HoursOfDay *[]int `json:"hoursOfDay,omitempty"`

						// StartingMinute The minute of the hour when the frequency period starts.
						//
						// Example: 38
						StartingMinute *int `json:"startingMinute,omitempty"`
					} `json:"value,omitempty"`
				} `json:"frequency,omitempty"`

				// IsArchivedPolicyActive Indicates whether the archived policy is currently active.
				//
				// Example: false
				IsArchivedPolicyActive *bool `json:"is_archived_policy_active,omitempty"`

				// IsEncryptionApplied Indicates whether encryption was applied to the usage data
				//
				// Example: false
				IsEncryptionApplied *bool `json:"is_encryption_applied,omitempty"`

				// IsWindowPlan Indicates whether the usage plan is a window plan.
				//
				// Example: false
				IsWindowPlan *bool `json:"is_window_plan,omitempty"`

				// LastRunTime Timestamp of the last run in human-readable format
				//
				// Example: 21 July, 2025 14:19
				LastRunTime    *string `json:"last_run_time,omitempty"`
				LastTaskStatus *struct {
					// FailedDate Date when the last task failed
					//
					// Example:
					FailedDate *string `json:"failed_date,omitempty"`

					// Message Human-readable status message for the last task
					//
					// Example: Connecting to agent failed
					Message *string `json:"message,omitempty"`

					// TaskStatus Indicates whether the last task completed successfully
					//
					// Example: false
					TaskStatus *bool `json:"task_status,omitempty"`
				} `json:"last_task_status,omitempty"`
				LocalRetentionPoints *struct {
					// DailyLimit Maximum number of days data is retained locally
					//
					// Example: 14
					DailyLimit *int `json:"daily_limit,omitempty"`

					// HourlyLimit Maximum number of hourly retention points allowed
					//
					// Example: 12
					HourlyLimit *int `json:"hourly_limit,omitempty"`

					// MonthlyLimit Maximum number of local retention points allowed per month.
					//
					// Example: 2
					MonthlyLimit *int `json:"monthly_limit,omitempty"`

					// WeeklyLimit Maximum number of weeks allowed for local retention points
					//
					// Example: 4
					WeeklyLimit *int `json:"weekly_limit,omitempty"`

					// YearlyLimit Annual retention points limit.
					//
					// Example: 0
					YearlyLimit *int `json:"yearly_limit,omitempty"`
				} `json:"local_retention_points,omitempty"`

				// NextRunTime Timestamp of the next scheduled run
				//
				// Example: 21 July, 2025 18:38
				NextRunTime *string `json:"next_run_time,omitempty"`

				// Size Size of the usage data as a human-readable string
				//
				// Example: 6525.0 Bytes
				Size *string `json:"size,omitempty"`

				// Status Indicates the result status of the usage request
				//
				// Example: ERROR
				Status *string `json:"status,omitempty"`
			} `json:"data,omitempty"`
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Status message indicating the result of the request
			//
			// Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
