// Package cloudfront provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package cloudfront

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DeleteCdnDistributionsParamsLocation.
const (
	DeleteCdnDistributionsParamsLocationChennai DeleteCdnDistributionsParamsLocation = "Chennai"
	DeleteCdnDistributionsParamsLocationDelhi   DeleteCdnDistributionsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the DeleteCdnDistributionsParamsLocation enum.
func (e DeleteCdnDistributionsParamsLocation) Valid() bool {
	switch e {
	case DeleteCdnDistributionsParamsLocationChennai:
		return true
	case DeleteCdnDistributionsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetCdnDistributionsParamsLocation.
const (
	GetCdnDistributionsParamsLocationChennai GetCdnDistributionsParamsLocation = "Chennai"
	GetCdnDistributionsParamsLocationDelhi   GetCdnDistributionsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetCdnDistributionsParamsLocation enum.
func (e GetCdnDistributionsParamsLocation) Valid() bool {
	switch e {
	case GetCdnDistributionsParamsLocationChennai:
		return true
	case GetCdnDistributionsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PostCdnDistributionsParamsLocation.
const (
	PostCdnDistributionsParamsLocationChennai PostCdnDistributionsParamsLocation = "Chennai"
	PostCdnDistributionsParamsLocationDelhi   PostCdnDistributionsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostCdnDistributionsParamsLocation enum.
func (e PostCdnDistributionsParamsLocation) Valid() bool {
	switch e {
	case PostCdnDistributionsParamsLocationChennai:
		return true
	case PostCdnDistributionsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutCdnDistributionsParamsLocation.
const (
	PutCdnDistributionsParamsLocationChennai PutCdnDistributionsParamsLocation = "Chennai"
	PutCdnDistributionsParamsLocationDelhi   PutCdnDistributionsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PutCdnDistributionsParamsLocation enum.
func (e PutCdnDistributionsParamsLocation) Valid() bool {
	switch e {
	case PutCdnDistributionsParamsLocationChennai:
		return true
	case PutCdnDistributionsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutCdnDistributionsJSONBodyIsEnabled.
const (
	False PutCdnDistributionsJSONBodyIsEnabled = false
	True  PutCdnDistributionsJSONBodyIsEnabled = true
)

// Valid indicates whether the value is a known member of the PutCdnDistributionsJSONBodyIsEnabled enum.
func (e PutCdnDistributionsJSONBodyIsEnabled) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// Defines values for PostCdnDomainUsageParamsLocation.
const (
	PostCdnDomainUsageParamsLocationChennai PostCdnDomainUsageParamsLocation = "Chennai"
	PostCdnDomainUsageParamsLocationDelhi   PostCdnDomainUsageParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostCdnDomainUsageParamsLocation enum.
func (e PostCdnDomainUsageParamsLocation) Valid() bool {
	switch e {
	case PostCdnDomainUsageParamsLocationChennai:
		return true
	case PostCdnDomainUsageParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PostCdnRequestForCdnServiceParamsLocation.
const (
	PostCdnRequestForCdnServiceParamsLocationChennai PostCdnRequestForCdnServiceParamsLocation = "Chennai"
	PostCdnRequestForCdnServiceParamsLocationDelhi   PostCdnRequestForCdnServiceParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostCdnRequestForCdnServiceParamsLocation enum.
func (e PostCdnRequestForCdnServiceParamsLocation) Valid() bool {
	switch e {
	case PostCdnRequestForCdnServiceParamsLocationChennai:
		return true
	case PostCdnRequestForCdnServiceParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// DeleteCdnDistributionsParams defines parameters for DeleteCdnDistributions.
type DeleteCdnDistributionsParams struct {
	// DomainId CDN Domain ID
	DomainId string `form:"domain_id" json:"domain_id"`

	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location DeleteCdnDistributionsParamsLocation `form:"location" json:"location"`
}

// DeleteCdnDistributionsParamsLocation defines parameters for DeleteCdnDistributions.
type DeleteCdnDistributionsParamsLocation string

// GetCdnDistributionsParams defines parameters for GetCdnDistributions.
type GetCdnDistributionsParams struct {
	// PageNo The page number from which you want your page search results to be displayed.
	PageNo *int `form:"page_no,omitempty" json:"page_no,omitempty"`

	// PerPage Number of results per page
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetCdnDistributionsParamsLocation `form:"location" json:"location"`
}

// GetCdnDistributionsParamsLocation defines parameters for GetCdnDistributions.
type GetCdnDistributionsParamsLocation string

// PostCdnDistributionsJSONBody defines parameters for PostCdnDistributions.
type PostCdnDistributionsJSONBody struct {
	CacheDetails *struct {
		// AllowedHttpMethods Example: GET|HEAD
		AllowedHttpMethods *string `json:"allowed_http_methods,omitempty"`

		// DefaultTtl Example: 86400
		DefaultTtl *int `json:"default_ttl,omitempty"`

		// MaxTtl Example: 3153000
		MaxTtl *int `json:"max_ttl,omitempty"`

		// MinTtl Example: 0
		MinTtl *int `json:"min_ttl,omitempty"`

		// ViewerProtocolPolicy Example: https-only
		ViewerProtocolPolicy *string `json:"viewer_protocol_policy,omitempty"`
	} `json:"cache_details,omitempty"`
	DomainDetails *struct {
		// HttpVersions Example: http2
		HttpVersions *string `json:"http_versions,omitempty"`

		// IsIpv6Supported Example: false
		IsIpv6Supported *bool `json:"is_ipv6_supported,omitempty"`

		// RootObject Example:
		RootObject *string `json:"root_object,omitempty"`
	} `json:"domain_details,omitempty"`

	// DomainName Example: e2enetworks.com
	DomainName    *string `json:"domain_name,omitempty"`
	OriginDetails *struct {
		// KeepaliveTimeout Example: 5
		KeepaliveTimeout *int `json:"keepalive_timeout,omitempty"`

		// OriginId Example: e2enetworks.com
		OriginId *string `json:"origin_id,omitempty"`

		// OriginPath Example: /static
		OriginPath *string `json:"origin_path,omitempty"`

		// ProtocolPolicy Example: https-only
		ProtocolPolicy *string `json:"protocol_policy,omitempty"`

		// ResponseTimeout Example: 30
		ResponseTimeout *int `json:"response_timeout,omitempty"`

		// SslProtocol Example: TLSv1.2
		SslProtocol *string `json:"ssl_protocol,omitempty"`
	} `json:"origin_details,omitempty"`

	// Source Example: cdn
	Source *string `json:"source,omitempty"`
}

// PostCdnDistributionsParams defines parameters for PostCdnDistributions.
type PostCdnDistributionsParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostCdnDistributionsParamsLocation `form:"location" json:"location"`
}

// PostCdnDistributionsParamsLocation defines parameters for PostCdnDistributions.
type PostCdnDistributionsParamsLocation string

// PutCdnDistributionsJSONBody defines parameters for PutCdnDistributions.
type PutCdnDistributionsJSONBody struct {
	// DomainId Example: ENZYVCZPO9X4L
	DomainId *string `json:"domain_id,omitempty"`

	// IsEnabled Enable CDN set is_enabled True else , To Disable set is_enabled False
	IsEnabled *PutCdnDistributionsJSONBodyIsEnabled `json:"is_enabled,omitempty"`
}

// PutCdnDistributionsParams defines parameters for PutCdnDistributions.
type PutCdnDistributionsParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PutCdnDistributionsParamsLocation `form:"location" json:"location"`
}

// PutCdnDistributionsParamsLocation defines parameters for PutCdnDistributions.
type PutCdnDistributionsParamsLocation string

// PutCdnDistributionsJSONBodyIsEnabled defines parameters for PutCdnDistributions.
type PutCdnDistributionsJSONBodyIsEnabled bool

// PostCdnDomainUsageJSONBody defines parameters for PostCdnDomainUsage.
type PostCdnDomainUsageJSONBody struct {
	// Domain Example: all
	Domain string `json:"domain"`

	// EndDate Example: 2022-05-19
	EndDate openapi_types.Date `json:"end_date"`

	// Granularity Example: daily
	Granularity string `json:"granularity"`

	// StartDate Example: 2022-05-04
	StartDate openapi_types.Date `json:"start_date"`
}

// PostCdnDomainUsageParams defines parameters for PostCdnDomainUsage.
type PostCdnDomainUsageParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostCdnDomainUsageParamsLocation `form:"location" json:"location"`
}

// PostCdnDomainUsageParamsLocation defines parameters for PostCdnDomainUsage.
type PostCdnDomainUsageParamsLocation string

// PostCdnRequestForCdnServiceJSONBody defines parameters for PostCdnRequestForCdnService.
type PostCdnRequestForCdnServiceJSONBody struct {
	// Reason Example: testing
	Reason *string `json:"reason,omitempty"`
}

// PostCdnRequestForCdnServiceParams defines parameters for PostCdnRequestForCdnService.
type PostCdnRequestForCdnServiceParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostCdnRequestForCdnServiceParamsLocation `form:"location" json:"location"`
}

// PostCdnRequestForCdnServiceParamsLocation defines parameters for PostCdnRequestForCdnService.
type PostCdnRequestForCdnServiceParamsLocation string

// PostCdnDistributionsJSONRequestBody defines body for PostCdnDistributions for application/json ContentType.
type PostCdnDistributionsJSONRequestBody PostCdnDistributionsJSONBody

// PutCdnDistributionsJSONRequestBody defines body for PutCdnDistributions for application/json ContentType.
type PutCdnDistributionsJSONRequestBody PutCdnDistributionsJSONBody

// PostCdnDomainUsageJSONRequestBody defines body for PostCdnDomainUsage for application/json ContentType.
type PostCdnDomainUsageJSONRequestBody PostCdnDomainUsageJSONBody

// PostCdnRequestForCdnServiceJSONRequestBody defines body for PostCdnRequestForCdnService for application/json ContentType.
type PostCdnRequestForCdnServiceJSONRequestBody PostCdnRequestForCdnServiceJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// DeleteCdnDistributions Delete CDN
	//
	// Corresponds with DELETE /api/v1/cdn/distributions/ (the `DeleteCdnDistributions` operationId).
	DeleteCdnDistributions(ctx context.Context, params *DeleteCdnDistributionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCdnDistributions Get CDN list
	//
	// Corresponds with GET /api/v1/cdn/distributions/ (the `GetCdnDistributions` operationId).
	GetCdnDistributions(ctx context.Context, params *GetCdnDistributionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCdnDistributionsWithBody Create CDN distribution
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
	PostCdnDistributionsWithBody(ctx context.Context, params *PostCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCdnDistributions Create CDN distribution
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
	PostCdnDistributions(ctx context.Context, params *PostCdnDistributionsParams, body PostCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutCdnDistributionsWithBody Enable/Disable CDN distribuition
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
	PutCdnDistributionsWithBody(ctx context.Context, params *PutCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutCdnDistributions Enable/Disable CDN distribuition
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
	PutCdnDistributions(ctx context.Context, params *PutCdnDistributionsParams, body PutCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCdnDomainUsageWithBody CDN Bandwidth usage
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
	PostCdnDomainUsageWithBody(ctx context.Context, params *PostCdnDomainUsageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCdnDomainUsage CDN Bandwidth usage
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
	PostCdnDomainUsage(ctx context.Context, params *PostCdnDomainUsageParams, body PostCdnDomainUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCdnRequestForCdnServiceWithBody Request for CDN
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
	PostCdnRequestForCdnServiceWithBody(ctx context.Context, params *PostCdnRequestForCdnServiceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCdnRequestForCdnService Request for CDN
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
	PostCdnRequestForCdnService(ctx context.Context, params *PostCdnRequestForCdnServiceParams, body PostCdnRequestForCdnServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// DeleteCdnDistributions Delete CDN
//
// Corresponds with DELETE /api/v1/cdn/distributions/ (the `DeleteCdnDistributions` operationId).
func (c *Client) DeleteCdnDistributions(ctx context.Context, params *DeleteCdnDistributionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCdnDistributionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCdnDistributions Get CDN list
//
// Corresponds with GET /api/v1/cdn/distributions/ (the `GetCdnDistributions` operationId).
func (c *Client) GetCdnDistributions(ctx context.Context, params *GetCdnDistributionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCdnDistributionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCdnDistributionsWithBody Create CDN distribution
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
func (c *Client) PostCdnDistributionsWithBody(ctx context.Context, params *PostCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCdnDistributionsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCdnDistributions Create CDN distribution
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
func (c *Client) PostCdnDistributions(ctx context.Context, params *PostCdnDistributionsParams, body PostCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCdnDistributionsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutCdnDistributionsWithBody Enable/Disable CDN distribuition
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
func (c *Client) PutCdnDistributionsWithBody(ctx context.Context, params *PutCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutCdnDistributionsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutCdnDistributions Enable/Disable CDN distribuition
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
func (c *Client) PutCdnDistributions(ctx context.Context, params *PutCdnDistributionsParams, body PutCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutCdnDistributionsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCdnDomainUsageWithBody CDN Bandwidth usage
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
func (c *Client) PostCdnDomainUsageWithBody(ctx context.Context, params *PostCdnDomainUsageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCdnDomainUsageRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCdnDomainUsage CDN Bandwidth usage
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
func (c *Client) PostCdnDomainUsage(ctx context.Context, params *PostCdnDomainUsageParams, body PostCdnDomainUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCdnDomainUsageRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCdnRequestForCdnServiceWithBody Request for CDN
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
func (c *Client) PostCdnRequestForCdnServiceWithBody(ctx context.Context, params *PostCdnRequestForCdnServiceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCdnRequestForCdnServiceRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCdnRequestForCdnService Request for CDN
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
func (c *Client) PostCdnRequestForCdnService(ctx context.Context, params *PostCdnRequestForCdnServiceParams, body PostCdnRequestForCdnServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCdnRequestForCdnServiceRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteCdnDistributionsRequest constructs an http.Request for the DeleteCdnDistributions method
func NewDeleteCdnDistributionsRequest(server string, params *DeleteCdnDistributionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdn/distributions/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "domain_id", params.DomainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCdnDistributionsRequest constructs an http.Request for the GetCdnDistributions method
func NewGetCdnDistributionsRequest(server string, params *GetCdnDistributionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdn/distributions/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageNo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_no", *params.PageNo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostCdnDistributionsRequest calls the generic PostCdnDistributions builder with application/json body
func NewPostCdnDistributionsRequest(server string, params *PostCdnDistributionsParams, body PostCdnDistributionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCdnDistributionsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCdnDistributionsRequestWithBody constructs an http.Request for the PostCdnDistributions method, with any body, and a specified content type
func NewPostCdnDistributionsRequestWithBody(server string, params *PostCdnDistributionsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdn/distributions/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutCdnDistributionsRequest calls the generic PutCdnDistributions builder with application/json body
func NewPutCdnDistributionsRequest(server string, params *PutCdnDistributionsParams, body PutCdnDistributionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutCdnDistributionsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPutCdnDistributionsRequestWithBody constructs an http.Request for the PutCdnDistributions method, with any body, and a specified content type
func NewPutCdnDistributionsRequestWithBody(server string, params *PutCdnDistributionsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdn/distributions/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCdnDomainUsageRequest calls the generic PostCdnDomainUsage builder with application/json body
func NewPostCdnDomainUsageRequest(server string, params *PostCdnDomainUsageParams, body PostCdnDomainUsageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCdnDomainUsageRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCdnDomainUsageRequestWithBody constructs an http.Request for the PostCdnDomainUsage method, with any body, and a specified content type
func NewPostCdnDomainUsageRequestWithBody(server string, params *PostCdnDomainUsageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdn/domain-usage/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCdnRequestForCdnServiceRequest calls the generic PostCdnRequestForCdnService builder with application/json body
func NewPostCdnRequestForCdnServiceRequest(server string, params *PostCdnRequestForCdnServiceParams, body PostCdnRequestForCdnServiceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCdnRequestForCdnServiceRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCdnRequestForCdnServiceRequestWithBody constructs an http.Request for the PostCdnRequestForCdnService method, with any body, and a specified content type
func NewPostCdnRequestForCdnServiceRequestWithBody(server string, params *PostCdnRequestForCdnServiceParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cdn/request-for-cdn-service/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// DeleteCdnDistributionsWithResponse Delete CDN
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/cdn/distributions/ (the `DeleteCdnDistributions` operationId).
	DeleteCdnDistributionsWithResponse(ctx context.Context, params *DeleteCdnDistributionsParams, reqEditors ...RequestEditorFn) (*DeleteCdnDistributionsResponse, error)

	// GetCdnDistributionsWithResponse Get CDN list
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/cdn/distributions/ (the `GetCdnDistributions` operationId).
	GetCdnDistributionsWithResponse(ctx context.Context, params *GetCdnDistributionsParams, reqEditors ...RequestEditorFn) (*GetCdnDistributionsResponse, error)

	// PostCdnDistributionsWithBodyWithResponse Create CDN distribution
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
	PostCdnDistributionsWithBodyWithResponse(ctx context.Context, params *PostCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCdnDistributionsResponse, error)

	// PostCdnDistributionsWithResponse Create CDN distribution
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
	PostCdnDistributionsWithResponse(ctx context.Context, params *PostCdnDistributionsParams, body PostCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCdnDistributionsResponse, error)

	// PutCdnDistributionsWithBodyWithResponse Enable/Disable CDN distribuition
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
	PutCdnDistributionsWithBodyWithResponse(ctx context.Context, params *PutCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutCdnDistributionsResponse, error)

	// PutCdnDistributionsWithResponse Enable/Disable CDN distribuition
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
	PutCdnDistributionsWithResponse(ctx context.Context, params *PutCdnDistributionsParams, body PutCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PutCdnDistributionsResponse, error)

	// PostCdnDomainUsageWithBodyWithResponse CDN Bandwidth usage
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
	PostCdnDomainUsageWithBodyWithResponse(ctx context.Context, params *PostCdnDomainUsageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCdnDomainUsageResponse, error)

	// PostCdnDomainUsageWithResponse CDN Bandwidth usage
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
	PostCdnDomainUsageWithResponse(ctx context.Context, params *PostCdnDomainUsageParams, body PostCdnDomainUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCdnDomainUsageResponse, error)

	// PostCdnRequestForCdnServiceWithBodyWithResponse Request for CDN
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
	PostCdnRequestForCdnServiceWithBodyWithResponse(ctx context.Context, params *PostCdnRequestForCdnServiceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCdnRequestForCdnServiceResponse, error)

	// PostCdnRequestForCdnServiceWithResponse Request for CDN
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
	PostCdnRequestForCdnServiceWithResponse(ctx context.Context, params *PostCdnRequestForCdnServiceParams, body PostCdnRequestForCdnServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCdnRequestForCdnServiceResponse, error)
}

type DeleteCdnDistributionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DeleteCdnDistributionsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteCdnDistributionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCdnDistributionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteCdnDistributionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCdnDistributionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// CreatedAt Example: 30/Oct/2024 12:48 PM
			CreatedAt *string `json:"created_at,omitempty"`

			// DomainId Example: ENZYVCZPO9X4L
			DomainId *string `json:"domain_id,omitempty"`

			// DomainState Example: Deployed
			DomainState *string `json:"domain_state,omitempty"`

			// E2eDomainName Example: docs1g047zlrhx.cdn.e2enetworks.net
			E2eDomainName *string `json:"e2e_domain_name,omitempty"`

			// Id Example: 1052
			Id *int `json:"id,omitempty"`

			// IsEnabled Example: true
			IsEnabled *bool `json:"is_enabled,omitempty"`

			// UserDomainName Example: docs.e2enetworks.com
			UserDomainName *string `json:"user_domain_name,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]string `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCdnDistributionsResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// CreatedAt Example: 30/Oct/2024 12:48 PM
		CreatedAt *string `json:"created_at,omitempty"`

		// DomainId Example: ENZYVCZPO9X4L
		DomainId *string `json:"domain_id,omitempty"`

		// DomainState Example: Deployed
		DomainState *string `json:"domain_state,omitempty"`

		// E2eDomainName Example: docs1g047zlrhx.cdn.e2enetworks.net
		E2eDomainName *string `json:"e2e_domain_name,omitempty"`

		// Id Example: 1052
		Id *int `json:"id,omitempty"`

		// IsEnabled Example: true
		IsEnabled *bool `json:"is_enabled,omitempty"`

		// UserDomainName Example: docs.e2enetworks.com
		UserDomainName *string `json:"user_domain_name,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]string `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetCdnDistributionsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCdnDistributionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCdnDistributionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCdnDistributionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCdnDistributionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// DomainId Example: ENZYVCZPO9X4L
			DomainId *string `json:"domain_id,omitempty"`
			LabelId  *string `json:"label_id,omitempty"`

			// Message Example: Your Distribution has been created successfully. It will take upto 30 minutes to deploy. Please wait.
			Message      *string `json:"message,omitempty"`
			ResourceType *string `json:"resource_type,omitempty"`

			// ResponseDomain Example: docs1g047zlrhx.cdn.e2enetworks.net
			ResponseDomain *string `json:"response_domain,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]string `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCdnDistributionsResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// DomainId Example: ENZYVCZPO9X4L
		DomainId *string `json:"domain_id,omitempty"`
		LabelId  *string `json:"label_id,omitempty"`

		// Message Example: Your Distribution has been created successfully. It will take upto 30 minutes to deploy. Please wait.
		Message      *string `json:"message,omitempty"`
		ResourceType *string `json:"resource_type,omitempty"`

		// ResponseDomain Example: docs1g047zlrhx.cdn.e2enetworks.net
		ResponseDomain *string `json:"response_domain,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]string `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostCdnDistributionsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCdnDistributionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCdnDistributionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCdnDistributionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutCdnDistributionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// Message Example: Your Distribution has been updated successfully. It will take up to 30 minutes to deploy the new changes. Please wait.
			Message *string `json:"message,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutCdnDistributionsResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// Message Example: Your Distribution has been updated successfully. It will take up to 30 minutes to deploy the new changes. Please wait.
		Message *string `json:"message,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PutCdnDistributionsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutCdnDistributionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutCdnDistributionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutCdnDistributionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCdnDomainUsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`

		// Data Example: []
		Data *[]interface{} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCdnDomainUsageResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`

	// Data Example: []
	Data *[]interface{} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostCdnDomainUsageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCdnDomainUsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCdnDomainUsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCdnDomainUsageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCdnRequestForCdnServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *struct {
		// Code Example: 202
		Code *int `json:"code,omitempty"`

		// Data Example: {}
		Data *map[string]interface{} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]string `json:"errors,omitempty"`

		// Message Example: Request for CDN service created successfully.
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r PostCdnRequestForCdnServiceResponse) GetJSON202() *struct {
	// Code Example: 202
	Code *int `json:"code,omitempty"`

	// Data Example: {}
	Data *map[string]interface{} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]string `json:"errors,omitempty"`

	// Message Example: Request for CDN service created successfully.
	Message *string `json:"message,omitempty"`
} {
	return r.JSON202
}

// GetBody returns the raw response body bytes
func (r PostCdnRequestForCdnServiceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCdnRequestForCdnServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCdnRequestForCdnServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCdnRequestForCdnServiceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DeleteCdnDistributionsWithResponse Delete CDN
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/cdn/distributions/ (the `DeleteCdnDistributions` operationId).
func (c *ClientWithResponses) DeleteCdnDistributionsWithResponse(ctx context.Context, params *DeleteCdnDistributionsParams, reqEditors ...RequestEditorFn) (*DeleteCdnDistributionsResponse, error) {
	rsp, err := c.DeleteCdnDistributions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCdnDistributionsResponse(rsp)
}

// GetCdnDistributionsWithResponse Get CDN list
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/cdn/distributions/ (the `GetCdnDistributions` operationId).
func (c *ClientWithResponses) GetCdnDistributionsWithResponse(ctx context.Context, params *GetCdnDistributionsParams, reqEditors ...RequestEditorFn) (*GetCdnDistributionsResponse, error) {
	rsp, err := c.GetCdnDistributions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCdnDistributionsResponse(rsp)
}

// PostCdnDistributionsWithBodyWithResponse Create CDN distribution
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
func (c *ClientWithResponses) PostCdnDistributionsWithBodyWithResponse(ctx context.Context, params *PostCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCdnDistributionsResponse, error) {
	rsp, err := c.PostCdnDistributionsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCdnDistributionsResponse(rsp)
}

// PostCdnDistributionsWithResponse Create CDN distribution
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/cdn/distributions/ (the `PostCdnDistributions` operationId).
func (c *ClientWithResponses) PostCdnDistributionsWithResponse(ctx context.Context, params *PostCdnDistributionsParams, body PostCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCdnDistributionsResponse, error) {
	rsp, err := c.PostCdnDistributions(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCdnDistributionsResponse(rsp)
}

// PutCdnDistributionsWithBodyWithResponse Enable/Disable CDN distribuition
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
func (c *ClientWithResponses) PutCdnDistributionsWithBodyWithResponse(ctx context.Context, params *PutCdnDistributionsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutCdnDistributionsResponse, error) {
	rsp, err := c.PutCdnDistributionsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutCdnDistributionsResponse(rsp)
}

// PutCdnDistributionsWithResponse Enable/Disable CDN distribuition
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/cdn/distributions/ (the `PutCdnDistributions` operationId).
func (c *ClientWithResponses) PutCdnDistributionsWithResponse(ctx context.Context, params *PutCdnDistributionsParams, body PutCdnDistributionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PutCdnDistributionsResponse, error) {
	rsp, err := c.PutCdnDistributions(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutCdnDistributionsResponse(rsp)
}

// PostCdnDomainUsageWithBodyWithResponse CDN Bandwidth usage
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
func (c *ClientWithResponses) PostCdnDomainUsageWithBodyWithResponse(ctx context.Context, params *PostCdnDomainUsageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCdnDomainUsageResponse, error) {
	rsp, err := c.PostCdnDomainUsageWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCdnDomainUsageResponse(rsp)
}

// PostCdnDomainUsageWithResponse CDN Bandwidth usage
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/cdn/domain-usage/ (the `PostCdnDomainUsage` operationId).
func (c *ClientWithResponses) PostCdnDomainUsageWithResponse(ctx context.Context, params *PostCdnDomainUsageParams, body PostCdnDomainUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCdnDomainUsageResponse, error) {
	rsp, err := c.PostCdnDomainUsage(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCdnDomainUsageResponse(rsp)
}

// PostCdnRequestForCdnServiceWithBodyWithResponse Request for CDN
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
func (c *ClientWithResponses) PostCdnRequestForCdnServiceWithBodyWithResponse(ctx context.Context, params *PostCdnRequestForCdnServiceParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCdnRequestForCdnServiceResponse, error) {
	rsp, err := c.PostCdnRequestForCdnServiceWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCdnRequestForCdnServiceResponse(rsp)
}

// PostCdnRequestForCdnServiceWithResponse Request for CDN
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/cdn/request-for-cdn-service/ (the `PostCdnRequestForCdnService` operationId).
func (c *ClientWithResponses) PostCdnRequestForCdnServiceWithResponse(ctx context.Context, params *PostCdnRequestForCdnServiceParams, body PostCdnRequestForCdnServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCdnRequestForCdnServiceResponse, error) {
	rsp, err := c.PostCdnRequestForCdnService(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCdnRequestForCdnServiceResponse(rsp)
}

// ParseDeleteCdnDistributionsResponse parses an HTTP response from a DeleteCdnDistributionsWithResponse call
func ParseDeleteCdnDistributionsResponse(rsp *http.Response) (*DeleteCdnDistributionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCdnDistributionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetCdnDistributionsResponse parses an HTTP response from a GetCdnDistributionsWithResponse call
func ParseGetCdnDistributionsResponse(rsp *http.Response) (*GetCdnDistributionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCdnDistributionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// CreatedAt Example: 30/Oct/2024 12:48 PM
				CreatedAt *string `json:"created_at,omitempty"`

				// DomainId Example: ENZYVCZPO9X4L
				DomainId *string `json:"domain_id,omitempty"`

				// DomainState Example: Deployed
				DomainState *string `json:"domain_state,omitempty"`

				// E2eDomainName Example: docs1g047zlrhx.cdn.e2enetworks.net
				E2eDomainName *string `json:"e2e_domain_name,omitempty"`

				// Id Example: 1052
				Id *int `json:"id,omitempty"`

				// IsEnabled Example: true
				IsEnabled *bool `json:"is_enabled,omitempty"`

				// UserDomainName Example: docs.e2enetworks.com
				UserDomainName *string `json:"user_domain_name,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]string `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostCdnDistributionsResponse parses an HTTP response from a PostCdnDistributionsWithResponse call
func ParsePostCdnDistributionsResponse(rsp *http.Response) (*PostCdnDistributionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCdnDistributionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// DomainId Example: ENZYVCZPO9X4L
				DomainId *string `json:"domain_id,omitempty"`
				LabelId  *string `json:"label_id,omitempty"`

				// Message Example: Your Distribution has been created successfully. It will take upto 30 minutes to deploy. Please wait.
				Message      *string `json:"message,omitempty"`
				ResourceType *string `json:"resource_type,omitempty"`

				// ResponseDomain Example: docs1g047zlrhx.cdn.e2enetworks.net
				ResponseDomain *string `json:"response_domain,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]string `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutCdnDistributionsResponse parses an HTTP response from a PutCdnDistributionsWithResponse call
func ParsePutCdnDistributionsResponse(rsp *http.Response) (*PutCdnDistributionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutCdnDistributionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// Message Example: Your Distribution has been updated successfully. It will take up to 30 minutes to deploy the new changes. Please wait.
				Message *string `json:"message,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostCdnDomainUsageResponse parses an HTTP response from a PostCdnDomainUsageWithResponse call
func ParsePostCdnDomainUsageResponse(rsp *http.Response) (*PostCdnDomainUsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCdnDomainUsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`

			// Data Example: []
			Data *[]interface{} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostCdnRequestForCdnServiceResponse parses an HTTP response from a PostCdnRequestForCdnServiceWithResponse call
func ParsePostCdnRequestForCdnServiceResponse(rsp *http.Response) (*PostCdnRequestForCdnServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCdnRequestForCdnServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest struct {
			// Code Example: 202
			Code *int `json:"code,omitempty"`

			// Data Example: {}
			Data *map[string]interface{} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]string `json:"errors,omitempty"`

			// Message Example: Request for CDN service created successfully.
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}
