// Package route53 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package route53

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation.
const (
	GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocationChennai GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation = "Chennai"
	GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocationDelhi   GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation enum.
func (e GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation) Valid() bool {
	switch e {
	case GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocationChennai:
		return true
	case GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation.
const (
	GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocationChennai GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation = "Chennai"
	GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocationDelhi   GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation enum.
func (e GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation) Valid() bool {
	switch e {
	case GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocationChennai:
		return true
	case GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation.
const (
	GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocationChennai GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation = "Chennai"
	GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocationDelhi   GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation enum.
func (e GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation) Valid() bool {
	switch e {
	case GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocationChennai:
		return true
	case GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for DeleteE2eDnsForwardParamsLocation.
const (
	DeleteE2eDnsForwardParamsLocationChennai DeleteE2eDnsForwardParamsLocation = "Chennai"
	DeleteE2eDnsForwardParamsLocationDelhi   DeleteE2eDnsForwardParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the DeleteE2eDnsForwardParamsLocation enum.
func (e DeleteE2eDnsForwardParamsLocation) Valid() bool {
	switch e {
	case DeleteE2eDnsForwardParamsLocationChennai:
		return true
	case DeleteE2eDnsForwardParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetE2eDnsForwardParamsLocation.
const (
	GetE2eDnsForwardParamsLocationChennai GetE2eDnsForwardParamsLocation = "Chennai"
	GetE2eDnsForwardParamsLocationDelhi   GetE2eDnsForwardParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetE2eDnsForwardParamsLocation enum.
func (e GetE2eDnsForwardParamsLocation) Valid() bool {
	switch e {
	case GetE2eDnsForwardParamsLocationChennai:
		return true
	case GetE2eDnsForwardParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PostE2eDnsForwardParamsLocation.
const (
	PostE2eDnsForwardParamsLocationChennai PostE2eDnsForwardParamsLocation = "Chennai"
	PostE2eDnsForwardParamsLocationDelhi   PostE2eDnsForwardParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostE2eDnsForwardParamsLocation enum.
func (e PostE2eDnsForwardParamsLocation) Valid() bool {
	switch e {
	case PostE2eDnsForwardParamsLocationChennai:
		return true
	case PostE2eDnsForwardParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetE2eDnsForwardDomainNameParamsLocation.
const (
	GetE2eDnsForwardDomainNameParamsLocationChennai GetE2eDnsForwardDomainNameParamsLocation = "Chennai"
	GetE2eDnsForwardDomainNameParamsLocationDelhi   GetE2eDnsForwardDomainNameParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetE2eDnsForwardDomainNameParamsLocation enum.
func (e GetE2eDnsForwardDomainNameParamsLocation) Valid() bool {
	switch e {
	case GetE2eDnsForwardDomainNameParamsLocationChennai:
		return true
	case GetE2eDnsForwardDomainNameParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// GetE2eDnsDiagnosticsVerifyNsDomainNameParams defines parameters for GetE2eDnsDiagnosticsVerifyNsDomainName.
type GetE2eDnsDiagnosticsVerifyNsDomainNameParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation `form:"location" json:"location"`
}

// GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation defines parameters for GetE2eDnsDiagnosticsVerifyNsDomainName.
type GetE2eDnsDiagnosticsVerifyNsDomainNameParamsLocation string

// GetE2eDnsDiagnosticsVerifyTtlDomainNameParams defines parameters for GetE2eDnsDiagnosticsVerifyTtlDomainName.
type GetE2eDnsDiagnosticsVerifyTtlDomainNameParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation `form:"location" json:"location"`
}

// GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation defines parameters for GetE2eDnsDiagnosticsVerifyTtlDomainName.
type GetE2eDnsDiagnosticsVerifyTtlDomainNameParamsLocation string

// GetE2eDnsDiagnosticsVerifyValidityDomainNameParams defines parameters for GetE2eDnsDiagnosticsVerifyValidityDomainName.
type GetE2eDnsDiagnosticsVerifyValidityDomainNameParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation `form:"location" json:"location"`
}

// GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation defines parameters for GetE2eDnsDiagnosticsVerifyValidityDomainName.
type GetE2eDnsDiagnosticsVerifyValidityDomainNameParamsLocation string

// DeleteE2eDnsForwardParams defines parameters for DeleteE2eDnsForward.
type DeleteE2eDnsForwardParams struct {
	// DomainId CDN Domain ID
	DomainId string `form:"domain_id" json:"domain_id"`

	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location DeleteE2eDnsForwardParamsLocation `form:"location" json:"location"`
}

// DeleteE2eDnsForwardParamsLocation defines parameters for DeleteE2eDnsForward.
type DeleteE2eDnsForwardParamsLocation string

// GetE2eDnsForwardParams defines parameters for GetE2eDnsForward.
type GetE2eDnsForwardParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetE2eDnsForwardParamsLocation `form:"location" json:"location"`
}

// GetE2eDnsForwardParamsLocation defines parameters for GetE2eDnsForward.
type GetE2eDnsForwardParamsLocation string

// PostE2eDnsForwardJSONBody defines parameters for PostE2eDnsForward.
type PostE2eDnsForwardJSONBody struct {
	// DomainName Example: bunty.com
	DomainName string `json:"domain_name"`

	// IpAddr Example: 1.1.1.1
	IpAddr string `json:"ip_addr"`
}

// PostE2eDnsForwardParams defines parameters for PostE2eDnsForward.
type PostE2eDnsForwardParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostE2eDnsForwardParamsLocation `form:"location" json:"location"`
}

// PostE2eDnsForwardParamsLocation defines parameters for PostE2eDnsForward.
type PostE2eDnsForwardParamsLocation string

// GetE2eDnsForwardDomainNameParams defines parameters for GetE2eDnsForwardDomainName.
type GetE2eDnsForwardDomainNameParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetE2eDnsForwardDomainNameParamsLocation `form:"location" json:"location"`
}

// GetE2eDnsForwardDomainNameParamsLocation defines parameters for GetE2eDnsForwardDomainName.
type GetE2eDnsForwardDomainNameParamsLocation string

// PostE2eDnsForwardJSONRequestBody defines body for PostE2eDnsForward for application/json ContentType.
type PostE2eDnsForwardJSONRequestBody PostE2eDnsForwardJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetE2eDnsDiagnosticsVerifyNsDomainName Verify DNS record
	//
	// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ns/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyNsDomainName` operationId).
	GetE2eDnsDiagnosticsVerifyNsDomainName(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyNsDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetE2eDnsDiagnosticsVerifyTtlDomainName Diagnose TTL
	//
	// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ttl/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyTtlDomainName` operationId).
	GetE2eDnsDiagnosticsVerifyTtlDomainName(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyTtlDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetE2eDnsDiagnosticsVerifyValidityDomainName Diagnose DNS validity
	//
	// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_validity/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyValidityDomainName` operationId).
	GetE2eDnsDiagnosticsVerifyValidityDomainName(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyValidityDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteE2eDnsForward Delete DNS
	//
	// Corresponds with DELETE /api/v1/e2e_dns/forward/ (the `DeleteE2eDnsForward` operationId).
	DeleteE2eDnsForward(ctx context.Context, params *DeleteE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetE2eDnsForward Get DNS List
	//
	// Corresponds with GET /api/v1/e2e_dns/forward/ (the `GetE2eDnsForward` operationId).
	GetE2eDnsForward(ctx context.Context, params *GetE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostE2eDnsForwardWithBody Create DNS
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
	PostE2eDnsForwardWithBody(ctx context.Context, params *PostE2eDnsForwardParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostE2eDnsForward Create DNS
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
	PostE2eDnsForward(ctx context.Context, params *PostE2eDnsForwardParams, body PostE2eDnsForwardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetE2eDnsForwardDomainName View DNS record
	//
	// Corresponds with GET /api/v1/e2e_dns/forward/{domain_name}/ (the `GetE2eDnsForwardDomainName` operationId).
	GetE2eDnsForwardDomainName(ctx context.Context, domainName string, params *GetE2eDnsForwardDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetE2eDnsDiagnosticsVerifyNsDomainName Verify DNS record
//
// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ns/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyNsDomainName` operationId).
func (c *Client) GetE2eDnsDiagnosticsVerifyNsDomainName(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyNsDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetE2eDnsDiagnosticsVerifyNsDomainNameRequest(c.Server, domainName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetE2eDnsDiagnosticsVerifyTtlDomainName Diagnose TTL
//
// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ttl/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyTtlDomainName` operationId).
func (c *Client) GetE2eDnsDiagnosticsVerifyTtlDomainName(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyTtlDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetE2eDnsDiagnosticsVerifyTtlDomainNameRequest(c.Server, domainName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetE2eDnsDiagnosticsVerifyValidityDomainName Diagnose DNS validity
//
// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_validity/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyValidityDomainName` operationId).
func (c *Client) GetE2eDnsDiagnosticsVerifyValidityDomainName(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyValidityDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetE2eDnsDiagnosticsVerifyValidityDomainNameRequest(c.Server, domainName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteE2eDnsForward Delete DNS
//
// Corresponds with DELETE /api/v1/e2e_dns/forward/ (the `DeleteE2eDnsForward` operationId).
func (c *Client) DeleteE2eDnsForward(ctx context.Context, params *DeleteE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteE2eDnsForwardRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetE2eDnsForward Get DNS List
//
// Corresponds with GET /api/v1/e2e_dns/forward/ (the `GetE2eDnsForward` operationId).
func (c *Client) GetE2eDnsForward(ctx context.Context, params *GetE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetE2eDnsForwardRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostE2eDnsForwardWithBody Create DNS
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
func (c *Client) PostE2eDnsForwardWithBody(ctx context.Context, params *PostE2eDnsForwardParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostE2eDnsForwardRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostE2eDnsForward Create DNS
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
func (c *Client) PostE2eDnsForward(ctx context.Context, params *PostE2eDnsForwardParams, body PostE2eDnsForwardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostE2eDnsForwardRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetE2eDnsForwardDomainName View DNS record
//
// Corresponds with GET /api/v1/e2e_dns/forward/{domain_name}/ (the `GetE2eDnsForwardDomainName` operationId).
func (c *Client) GetE2eDnsForwardDomainName(ctx context.Context, domainName string, params *GetE2eDnsForwardDomainNameParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetE2eDnsForwardDomainNameRequest(c.Server, domainName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetE2eDnsDiagnosticsVerifyNsDomainNameRequest constructs an http.Request for the GetE2eDnsDiagnosticsVerifyNsDomainName method
func NewGetE2eDnsDiagnosticsVerifyNsDomainNameRequest(server string, domainName string, params *GetE2eDnsDiagnosticsVerifyNsDomainNameParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domain_name", domainName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/diagnostics/verify_ns/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetE2eDnsDiagnosticsVerifyTtlDomainNameRequest constructs an http.Request for the GetE2eDnsDiagnosticsVerifyTtlDomainName method
func NewGetE2eDnsDiagnosticsVerifyTtlDomainNameRequest(server string, domainName string, params *GetE2eDnsDiagnosticsVerifyTtlDomainNameParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domain_name", domainName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/diagnostics/verify_ttl/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetE2eDnsDiagnosticsVerifyValidityDomainNameRequest constructs an http.Request for the GetE2eDnsDiagnosticsVerifyValidityDomainName method
func NewGetE2eDnsDiagnosticsVerifyValidityDomainNameRequest(server string, domainName string, params *GetE2eDnsDiagnosticsVerifyValidityDomainNameParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domain_name", domainName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/diagnostics/verify_validity/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteE2eDnsForwardRequest constructs an http.Request for the DeleteE2eDnsForward method
func NewDeleteE2eDnsForwardRequest(server string, params *DeleteE2eDnsForwardParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/forward/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "domain_id", params.DomainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetE2eDnsForwardRequest constructs an http.Request for the GetE2eDnsForward method
func NewGetE2eDnsForwardRequest(server string, params *GetE2eDnsForwardParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/forward/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostE2eDnsForwardRequest calls the generic PostE2eDnsForward builder with application/json body
func NewPostE2eDnsForwardRequest(server string, params *PostE2eDnsForwardParams, body PostE2eDnsForwardJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostE2eDnsForwardRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostE2eDnsForwardRequestWithBody constructs an http.Request for the PostE2eDnsForward method, with any body, and a specified content type
func NewPostE2eDnsForwardRequestWithBody(server string, params *PostE2eDnsForwardParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/forward/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetE2eDnsForwardDomainNameRequest constructs an http.Request for the GetE2eDnsForwardDomainName method
func NewGetE2eDnsForwardDomainNameRequest(server string, domainName string, params *GetE2eDnsForwardDomainNameParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domain_name", domainName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/e2e_dns/forward/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetE2eDnsDiagnosticsVerifyNsDomainNameWithResponse Verify DNS record
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ns/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyNsDomainName` operationId).
	GetE2eDnsDiagnosticsVerifyNsDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyNsDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsDiagnosticsVerifyNsDomainNameResponse, error)

	// GetE2eDnsDiagnosticsVerifyTtlDomainNameWithResponse Diagnose TTL
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ttl/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyTtlDomainName` operationId).
	GetE2eDnsDiagnosticsVerifyTtlDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyTtlDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse, error)

	// GetE2eDnsDiagnosticsVerifyValidityDomainNameWithResponse Diagnose DNS validity
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_validity/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyValidityDomainName` operationId).
	GetE2eDnsDiagnosticsVerifyValidityDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyValidityDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse, error)

	// DeleteE2eDnsForwardWithResponse Delete DNS
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/e2e_dns/forward/ (the `DeleteE2eDnsForward` operationId).
	DeleteE2eDnsForwardWithResponse(ctx context.Context, params *DeleteE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*DeleteE2eDnsForwardResponse, error)

	// GetE2eDnsForwardWithResponse Get DNS List
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/e2e_dns/forward/ (the `GetE2eDnsForward` operationId).
	GetE2eDnsForwardWithResponse(ctx context.Context, params *GetE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*GetE2eDnsForwardResponse, error)

	// PostE2eDnsForwardWithBodyWithResponse Create DNS
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
	PostE2eDnsForwardWithBodyWithResponse(ctx context.Context, params *PostE2eDnsForwardParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostE2eDnsForwardResponse, error)

	// PostE2eDnsForwardWithResponse Create DNS
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
	PostE2eDnsForwardWithResponse(ctx context.Context, params *PostE2eDnsForwardParams, body PostE2eDnsForwardJSONRequestBody, reqEditors ...RequestEditorFn) (*PostE2eDnsForwardResponse, error)

	// GetE2eDnsForwardDomainNameWithResponse View DNS record
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/e2e_dns/forward/{domain_name}/ (the `GetE2eDnsForwardDomainName` operationId).
	GetE2eDnsForwardDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsForwardDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsForwardDomainNameResponse, error)
}

type GetE2eDnsDiagnosticsVerifyNsDomainNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			Data *struct {
				// Authority Example: false
				Authority *bool `json:"authority,omitempty"`

				// E2eNameservers Example: ["ns50.e2enetworks.net.in.","ns51.e2enetworks.net.in."]
				E2eNameservers *[]string `json:"e2e_nameservers,omitempty"`

				// GlNameservers Example: ["ns2.taipandns.com.","ns1.taipandns.com."]
				GlNameservers *[]string `json:"gl_nameservers,omitempty"`

				// Problem Example: 1
				Problem *int `json:"problem,omitempty"`
			} `json:"data,omitempty"`

			// Message Example: Your nameservers are not setup correctly
			Message *string `json:"message,omitempty"`

			// Status Example: true
			Status *bool `json:"status,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetE2eDnsDiagnosticsVerifyNsDomainNameResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		Data *struct {
			// Authority Example: false
			Authority *bool `json:"authority,omitempty"`

			// E2eNameservers Example: ["ns50.e2enetworks.net.in.","ns51.e2enetworks.net.in."]
			E2eNameservers *[]string `json:"e2e_nameservers,omitempty"`

			// GlNameservers Example: ["ns2.taipandns.com.","ns1.taipandns.com."]
			GlNameservers *[]string `json:"gl_nameservers,omitempty"`

			// Problem Example: 1
			Problem *int `json:"problem,omitempty"`
		} `json:"data,omitempty"`

		// Message Example: Your nameservers are not setup correctly
		Message *string `json:"message,omitempty"`

		// Status Example: true
		Status *bool `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetE2eDnsDiagnosticsVerifyNsDomainNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetE2eDnsDiagnosticsVerifyNsDomainNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetE2eDnsDiagnosticsVerifyNsDomainNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetE2eDnsDiagnosticsVerifyNsDomainNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			Data *[]map[string]interface{} `json:"data,omitempty"`

			// Message Example: Error verifying TTL for your DNS records.
			Message *string `json:"message,omitempty"`

			// Status Example: true
			Status *bool `json:"status,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		Data *[]map[string]interface{} `json:"data,omitempty"`

		// Message Example: Error verifying TTL for your DNS records.
		Message *string `json:"message,omitempty"`

		// Status Example: true
		Status *bool `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON412 the response for an HTTP 412 `application/json` response
	JSON412 *struct {
		// Code Example: 412
		Code *int `json:"code,omitempty"`

		// Data Example: {}
		Data   *map[string]interface{} `json:"data,omitempty"`
		Errors *struct {
			// Message Example: Could not find validity for your domain.
			Message *string `json:"message,omitempty"`

			// Status Example: false
			Status *bool `json:"status,omitempty"`
		} `json:"errors,omitempty"`

		// Message Example: Precondition Failed
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON412 returns the response for an HTTP 412 `application/json` response
func (r GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse) GetJSON412() *struct {
	// Code Example: 412
	Code *int `json:"code,omitempty"`

	// Data Example: {}
	Data   *map[string]interface{} `json:"data,omitempty"`
	Errors *struct {
		// Message Example: Could not find validity for your domain.
		Message *string `json:"message,omitempty"`

		// Status Example: false
		Status *bool `json:"status,omitempty"`
	} `json:"errors,omitempty"`

	// Message Example: Precondition Failed
	Message *string `json:"message,omitempty"`
} {
	return r.JSON412
}

// GetBody returns the raw response body bytes
func (r GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteE2eDnsForwardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// Message Example: The domain was deleted successfully
			Message *string `json:"message,omitempty"`

			// Status Example: true
			Status *bool `json:"status,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteE2eDnsForwardResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// Message Example: The domain was deleted successfully
		Message *string `json:"message,omitempty"`

		// Status Example: true
		Status *bool `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r DeleteE2eDnsForwardResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteE2eDnsForwardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteE2eDnsForwardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteE2eDnsForwardResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetE2eDnsForwardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// CreatedAt Example: 2024-11-04T09:01:30.545588Z
			CreatedAt *time.Time `json:"created_at,omitempty"`

			// Deleted Example: false
			Deleted *bool `json:"deleted,omitempty"`

			// DomainIp Example: 1.1.1.1
			DomainIp *string `json:"domain_ip,omitempty"`

			// DomainName Example: testing098.com.
			DomainName *string `json:"domain_name,omitempty"`

			// Id Example: 10280
			Id       *int    `json:"id,omitempty"`
			Validity *string `json:"validity,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetE2eDnsForwardResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// CreatedAt Example: 2024-11-04T09:01:30.545588Z
		CreatedAt *time.Time `json:"created_at,omitempty"`

		// Deleted Example: false
		Deleted *bool `json:"deleted,omitempty"`

		// DomainIp Example: 1.1.1.1
		DomainIp *string `json:"domain_ip,omitempty"`

		// DomainName Example: testing098.com.
		DomainName *string `json:"domain_name,omitempty"`

		// Id Example: 10280
		Id       *int    `json:"id,omitempty"`
		Validity *string `json:"validity,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetE2eDnsForwardResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetE2eDnsForwardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetE2eDnsForwardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetE2eDnsForwardResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostE2eDnsForwardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// Id Example: 10279
			Id      *int `json:"id,omitempty"`
			LabelId *int `json:"label_id,omitempty"`

			// Message Example: The domain was created successfully!
			Message      *string `json:"message,omitempty"`
			ResourceType *string `json:"resource_type,omitempty"`

			// Status Example: true
			Status *bool `json:"status,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostE2eDnsForwardResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// Id Example: 10279
		Id      *int `json:"id,omitempty"`
		LabelId *int `json:"label_id,omitempty"`

		// Message Example: The domain was created successfully!
		Message      *string `json:"message,omitempty"`
		ResourceType *string `json:"resource_type,omitempty"`

		// Status Example: true
		Status *bool `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostE2eDnsForwardResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostE2eDnsForwardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostE2eDnsForwardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostE2eDnsForwardResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetE2eDnsForwardDomainNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// DOMAINTTL Example: 86400
			DOMAINTTL *int `json:"DOMAIN_TTL,omitempty"`
			Domain    *struct {
				// Account Example:
				Account *string `json:"account,omitempty"`

				// ApiRectify Example: false
				ApiRectify *bool `json:"api_rectify,omitempty"`

				// Dnssec Example: false
				Dnssec *bool `json:"dnssec,omitempty"`

				// Id Example: bunty.com.
				Id *string `json:"id,omitempty"`

				// Kind Example: Native
				Kind *string `json:"kind,omitempty"`

				// LastCheck Example: 0
				LastCheck *int `json:"last_check,omitempty"`

				// Masters Example: []
				Masters *[]string `json:"masters,omitempty"`

				// Name Example: bunty.com.
				Name *string `json:"name,omitempty"`

				// NotifiedSerial Example: 0
				NotifiedSerial *int `json:"notified_serial,omitempty"`

				// Nsec3narrow Example: false
				Nsec3narrow *bool `json:"nsec3narrow,omitempty"`

				// Nsec3param Example:
				Nsec3param *string `json:"nsec3param,omitempty"`
				Rrsets     *[]struct {
					// Comments Example: []
					Comments *[]string `json:"comments,omitempty"`

					// Name Example: bunty.com.
					Name    *string `json:"name,omitempty"`
					Records *[]struct {
						// Content Example: ns50.e2enetworks.net.in. abuse.e2enetworks.net.in. 2024110404 10800 3600 604800 86400
						Content *string `json:"content,omitempty"`

						// Disabled Example: false
						Disabled *bool `json:"disabled,omitempty"`
					} `json:"records,omitempty"`

					// Ttl Example: 86400
					Ttl *int `json:"ttl,omitempty"`

					// Type Example: SOA
					Type *string `json:"type,omitempty"`
				} `json:"rrsets,omitempty"`

				// Serial Example: 2024110404
				Serial *int `json:"serial,omitempty"`

				// SoaEdit Example:
				SoaEdit *string `json:"soa_edit,omitempty"`

				// SoaEditApi Example: DEFAULT
				SoaEditApi *string `json:"soa_edit_api,omitempty"`

				// Url Example: /api/v1/servers/localhost/zones/bunty.com.
				Url *string `json:"url,omitempty"`
			} `json:"domain,omitempty"`

			// DomainIp Example: 1.1.1.1
			DomainIp *string `json:"domain_ip,omitempty"`

			// DomainName Example: bunty.com.
			DomainName *string `json:"domain_name,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetE2eDnsForwardDomainNameResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// DOMAINTTL Example: 86400
		DOMAINTTL *int `json:"DOMAIN_TTL,omitempty"`
		Domain    *struct {
			// Account Example:
			Account *string `json:"account,omitempty"`

			// ApiRectify Example: false
			ApiRectify *bool `json:"api_rectify,omitempty"`

			// Dnssec Example: false
			Dnssec *bool `json:"dnssec,omitempty"`

			// Id Example: bunty.com.
			Id *string `json:"id,omitempty"`

			// Kind Example: Native
			Kind *string `json:"kind,omitempty"`

			// LastCheck Example: 0
			LastCheck *int `json:"last_check,omitempty"`

			// Masters Example: []
			Masters *[]string `json:"masters,omitempty"`

			// Name Example: bunty.com.
			Name *string `json:"name,omitempty"`

			// NotifiedSerial Example: 0
			NotifiedSerial *int `json:"notified_serial,omitempty"`

			// Nsec3narrow Example: false
			Nsec3narrow *bool `json:"nsec3narrow,omitempty"`

			// Nsec3param Example:
			Nsec3param *string `json:"nsec3param,omitempty"`
			Rrsets     *[]struct {
				// Comments Example: []
				Comments *[]string `json:"comments,omitempty"`

				// Name Example: bunty.com.
				Name    *string `json:"name,omitempty"`
				Records *[]struct {
					// Content Example: ns50.e2enetworks.net.in. abuse.e2enetworks.net.in. 2024110404 10800 3600 604800 86400
					Content *string `json:"content,omitempty"`

					// Disabled Example: false
					Disabled *bool `json:"disabled,omitempty"`
				} `json:"records,omitempty"`

				// Ttl Example: 86400
				Ttl *int `json:"ttl,omitempty"`

				// Type Example: SOA
				Type *string `json:"type,omitempty"`
			} `json:"rrsets,omitempty"`

			// Serial Example: 2024110404
			Serial *int `json:"serial,omitempty"`

			// SoaEdit Example:
			SoaEdit *string `json:"soa_edit,omitempty"`

			// SoaEditApi Example: DEFAULT
			SoaEditApi *string `json:"soa_edit_api,omitempty"`

			// Url Example: /api/v1/servers/localhost/zones/bunty.com.
			Url *string `json:"url,omitempty"`
		} `json:"domain,omitempty"`

		// DomainIp Example: 1.1.1.1
		DomainIp *string `json:"domain_ip,omitempty"`

		// DomainName Example: bunty.com.
		DomainName *string `json:"domain_name,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetE2eDnsForwardDomainNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetE2eDnsForwardDomainNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetE2eDnsForwardDomainNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetE2eDnsForwardDomainNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetE2eDnsDiagnosticsVerifyNsDomainNameWithResponse Verify DNS record
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ns/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyNsDomainName` operationId).
func (c *ClientWithResponses) GetE2eDnsDiagnosticsVerifyNsDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyNsDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsDiagnosticsVerifyNsDomainNameResponse, error) {
	rsp, err := c.GetE2eDnsDiagnosticsVerifyNsDomainName(ctx, domainName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetE2eDnsDiagnosticsVerifyNsDomainNameResponse(rsp)
}

// GetE2eDnsDiagnosticsVerifyTtlDomainNameWithResponse Diagnose TTL
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_ttl/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyTtlDomainName` operationId).
func (c *ClientWithResponses) GetE2eDnsDiagnosticsVerifyTtlDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyTtlDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse, error) {
	rsp, err := c.GetE2eDnsDiagnosticsVerifyTtlDomainName(ctx, domainName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetE2eDnsDiagnosticsVerifyTtlDomainNameResponse(rsp)
}

// GetE2eDnsDiagnosticsVerifyValidityDomainNameWithResponse Diagnose DNS validity
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/e2e_dns/diagnostics/verify_validity/{domain_name}/ (the `GetE2eDnsDiagnosticsVerifyValidityDomainName` operationId).
func (c *ClientWithResponses) GetE2eDnsDiagnosticsVerifyValidityDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsDiagnosticsVerifyValidityDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse, error) {
	rsp, err := c.GetE2eDnsDiagnosticsVerifyValidityDomainName(ctx, domainName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetE2eDnsDiagnosticsVerifyValidityDomainNameResponse(rsp)
}

// DeleteE2eDnsForwardWithResponse Delete DNS
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/e2e_dns/forward/ (the `DeleteE2eDnsForward` operationId).
func (c *ClientWithResponses) DeleteE2eDnsForwardWithResponse(ctx context.Context, params *DeleteE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*DeleteE2eDnsForwardResponse, error) {
	rsp, err := c.DeleteE2eDnsForward(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteE2eDnsForwardResponse(rsp)
}

// GetE2eDnsForwardWithResponse Get DNS List
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/e2e_dns/forward/ (the `GetE2eDnsForward` operationId).
func (c *ClientWithResponses) GetE2eDnsForwardWithResponse(ctx context.Context, params *GetE2eDnsForwardParams, reqEditors ...RequestEditorFn) (*GetE2eDnsForwardResponse, error) {
	rsp, err := c.GetE2eDnsForward(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetE2eDnsForwardResponse(rsp)
}

// PostE2eDnsForwardWithBodyWithResponse Create DNS
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
func (c *ClientWithResponses) PostE2eDnsForwardWithBodyWithResponse(ctx context.Context, params *PostE2eDnsForwardParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostE2eDnsForwardResponse, error) {
	rsp, err := c.PostE2eDnsForwardWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostE2eDnsForwardResponse(rsp)
}

// PostE2eDnsForwardWithResponse Create DNS
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/e2e_dns/forward/ (the `PostE2eDnsForward` operationId).
func (c *ClientWithResponses) PostE2eDnsForwardWithResponse(ctx context.Context, params *PostE2eDnsForwardParams, body PostE2eDnsForwardJSONRequestBody, reqEditors ...RequestEditorFn) (*PostE2eDnsForwardResponse, error) {
	rsp, err := c.PostE2eDnsForward(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostE2eDnsForwardResponse(rsp)
}

// GetE2eDnsForwardDomainNameWithResponse View DNS record
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/e2e_dns/forward/{domain_name}/ (the `GetE2eDnsForwardDomainName` operationId).
func (c *ClientWithResponses) GetE2eDnsForwardDomainNameWithResponse(ctx context.Context, domainName string, params *GetE2eDnsForwardDomainNameParams, reqEditors ...RequestEditorFn) (*GetE2eDnsForwardDomainNameResponse, error) {
	rsp, err := c.GetE2eDnsForwardDomainName(ctx, domainName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetE2eDnsForwardDomainNameResponse(rsp)
}

// ParseGetE2eDnsDiagnosticsVerifyNsDomainNameResponse parses an HTTP response from a GetE2eDnsDiagnosticsVerifyNsDomainNameWithResponse call
func ParseGetE2eDnsDiagnosticsVerifyNsDomainNameResponse(rsp *http.Response) (*GetE2eDnsDiagnosticsVerifyNsDomainNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetE2eDnsDiagnosticsVerifyNsDomainNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				Data *struct {
					// Authority Example: false
					Authority *bool `json:"authority,omitempty"`

					// E2eNameservers Example: ["ns50.e2enetworks.net.in.","ns51.e2enetworks.net.in."]
					E2eNameservers *[]string `json:"e2e_nameservers,omitempty"`

					// GlNameservers Example: ["ns2.taipandns.com.","ns1.taipandns.com."]
					GlNameservers *[]string `json:"gl_nameservers,omitempty"`

					// Problem Example: 1
					Problem *int `json:"problem,omitempty"`
				} `json:"data,omitempty"`

				// Message Example: Your nameservers are not setup correctly
				Message *string `json:"message,omitempty"`

				// Status Example: true
				Status *bool `json:"status,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetE2eDnsDiagnosticsVerifyTtlDomainNameResponse parses an HTTP response from a GetE2eDnsDiagnosticsVerifyTtlDomainNameWithResponse call
func ParseGetE2eDnsDiagnosticsVerifyTtlDomainNameResponse(rsp *http.Response) (*GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetE2eDnsDiagnosticsVerifyTtlDomainNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				Data *[]map[string]interface{} `json:"data,omitempty"`

				// Message Example: Error verifying TTL for your DNS records.
				Message *string `json:"message,omitempty"`

				// Status Example: true
				Status *bool `json:"status,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetE2eDnsDiagnosticsVerifyValidityDomainNameResponse parses an HTTP response from a GetE2eDnsDiagnosticsVerifyValidityDomainNameWithResponse call
func ParseGetE2eDnsDiagnosticsVerifyValidityDomainNameResponse(rsp *http.Response) (*GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetE2eDnsDiagnosticsVerifyValidityDomainNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest struct {
			// Code Example: 412
			Code *int `json:"code,omitempty"`

			// Data Example: {}
			Data   *map[string]interface{} `json:"data,omitempty"`
			Errors *struct {
				// Message Example: Could not find validity for your domain.
				Message *string `json:"message,omitempty"`

				// Status Example: false
				Status *bool `json:"status,omitempty"`
			} `json:"errors,omitempty"`

			// Message Example: Precondition Failed
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	}

	return response, nil
}

// ParseDeleteE2eDnsForwardResponse parses an HTTP response from a DeleteE2eDnsForwardWithResponse call
func ParseDeleteE2eDnsForwardResponse(rsp *http.Response) (*DeleteE2eDnsForwardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteE2eDnsForwardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// Message Example: The domain was deleted successfully
				Message *string `json:"message,omitempty"`

				// Status Example: true
				Status *bool `json:"status,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetE2eDnsForwardResponse parses an HTTP response from a GetE2eDnsForwardWithResponse call
func ParseGetE2eDnsForwardResponse(rsp *http.Response) (*GetE2eDnsForwardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetE2eDnsForwardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// CreatedAt Example: 2024-11-04T09:01:30.545588Z
				CreatedAt *time.Time `json:"created_at,omitempty"`

				// Deleted Example: false
				Deleted *bool `json:"deleted,omitempty"`

				// DomainIp Example: 1.1.1.1
				DomainIp *string `json:"domain_ip,omitempty"`

				// DomainName Example: testing098.com.
				DomainName *string `json:"domain_name,omitempty"`

				// Id Example: 10280
				Id       *int    `json:"id,omitempty"`
				Validity *string `json:"validity,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostE2eDnsForwardResponse parses an HTTP response from a PostE2eDnsForwardWithResponse call
func ParsePostE2eDnsForwardResponse(rsp *http.Response) (*PostE2eDnsForwardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostE2eDnsForwardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// Id Example: 10279
				Id      *int `json:"id,omitempty"`
				LabelId *int `json:"label_id,omitempty"`

				// Message Example: The domain was created successfully!
				Message      *string `json:"message,omitempty"`
				ResourceType *string `json:"resource_type,omitempty"`

				// Status Example: true
				Status *bool `json:"status,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetE2eDnsForwardDomainNameResponse parses an HTTP response from a GetE2eDnsForwardDomainNameWithResponse call
func ParseGetE2eDnsForwardDomainNameResponse(rsp *http.Response) (*GetE2eDnsForwardDomainNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetE2eDnsForwardDomainNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// DOMAINTTL Example: 86400
				DOMAINTTL *int `json:"DOMAIN_TTL,omitempty"`
				Domain    *struct {
					// Account Example:
					Account *string `json:"account,omitempty"`

					// ApiRectify Example: false
					ApiRectify *bool `json:"api_rectify,omitempty"`

					// Dnssec Example: false
					Dnssec *bool `json:"dnssec,omitempty"`

					// Id Example: bunty.com.
					Id *string `json:"id,omitempty"`

					// Kind Example: Native
					Kind *string `json:"kind,omitempty"`

					// LastCheck Example: 0
					LastCheck *int `json:"last_check,omitempty"`

					// Masters Example: []
					Masters *[]string `json:"masters,omitempty"`

					// Name Example: bunty.com.
					Name *string `json:"name,omitempty"`

					// NotifiedSerial Example: 0
					NotifiedSerial *int `json:"notified_serial,omitempty"`

					// Nsec3narrow Example: false
					Nsec3narrow *bool `json:"nsec3narrow,omitempty"`

					// Nsec3param Example:
					Nsec3param *string `json:"nsec3param,omitempty"`
					Rrsets     *[]struct {
						// Comments Example: []
						Comments *[]string `json:"comments,omitempty"`

						// Name Example: bunty.com.
						Name    *string `json:"name,omitempty"`
						Records *[]struct {
							// Content Example: ns50.e2enetworks.net.in. abuse.e2enetworks.net.in. 2024110404 10800 3600 604800 86400
							Content *string `json:"content,omitempty"`

							// Disabled Example: false
							Disabled *bool `json:"disabled,omitempty"`
						} `json:"records,omitempty"`

						// Ttl Example: 86400
						Ttl *int `json:"ttl,omitempty"`

						// Type Example: SOA
						Type *string `json:"type,omitempty"`
					} `json:"rrsets,omitempty"`

					// Serial Example: 2024110404
					Serial *int `json:"serial,omitempty"`

					// SoaEdit Example:
					SoaEdit *string `json:"soa_edit,omitempty"`

					// SoaEditApi Example: DEFAULT
					SoaEditApi *string `json:"soa_edit_api,omitempty"`

					// Url Example: /api/v1/servers/localhost/zones/bunty.com.
					Url *string `json:"url,omitempty"`
				} `json:"domain,omitempty"`

				// DomainIp Example: 1.1.1.1
				DomainIp *string `json:"domain_ip,omitempty"`

				// DomainName Example: bunty.com.
				DomainName *string `json:"domain_name,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
