// Package efs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package efs

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetEfsParamsLocation.
const (
	GetEfsParamsLocationChennai GetEfsParamsLocation = "Chennai"
	GetEfsParamsLocationDelhi   GetEfsParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetEfsParamsLocation enum.
func (e GetEfsParamsLocation) Valid() bool {
	switch e {
	case GetEfsParamsLocationChennai:
		return true
	case GetEfsParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutEfsAllowVpcCidrParamsLocation.
const (
	PutEfsAllowVpcCidrParamsLocationChennai PutEfsAllowVpcCidrParamsLocation = "Chennai"
	PutEfsAllowVpcCidrParamsLocationDelhi   PutEfsAllowVpcCidrParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PutEfsAllowVpcCidrParamsLocation enum.
func (e PutEfsAllowVpcCidrParamsLocation) Valid() bool {
	switch e {
	case PutEfsAllowVpcCidrParamsLocationChennai:
		return true
	case PutEfsAllowVpcCidrParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PostEfsCreateParamsLocation.
const (
	PostEfsCreateParamsLocationChennai PostEfsCreateParamsLocation = "Chennai"
	PostEfsCreateParamsLocationDelhi   PostEfsCreateParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PostEfsCreateParamsLocation enum.
func (e PostEfsCreateParamsLocation) Valid() bool {
	switch e {
	case PostEfsCreateParamsLocationChennai:
		return true
	case PostEfsCreateParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for DeleteEfsDeleteSfsIdParamsLocation.
const (
	DeleteEfsDeleteSfsIdParamsLocationChennai DeleteEfsDeleteSfsIdParamsLocation = "Chennai"
	DeleteEfsDeleteSfsIdParamsLocationDelhi   DeleteEfsDeleteSfsIdParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the DeleteEfsDeleteSfsIdParamsLocation enum.
func (e DeleteEfsDeleteSfsIdParamsLocation) Valid() bool {
	switch e {
	case DeleteEfsDeleteSfsIdParamsLocationChennai:
		return true
	case DeleteEfsDeleteSfsIdParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for GetEfsPlansParamsLocation.
const (
	GetEfsPlansParamsLocationChennai GetEfsPlansParamsLocation = "Chennai"
	GetEfsPlansParamsLocationDelhi   GetEfsPlansParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the GetEfsPlansParamsLocation enum.
func (e GetEfsPlansParamsLocation) Valid() bool {
	switch e {
	case GetEfsPlansParamsLocationChennai:
		return true
	case GetEfsPlansParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutEfsSfsIdBackupActivateParamsLocation.
const (
	PutEfsSfsIdBackupActivateParamsLocationChennai PutEfsSfsIdBackupActivateParamsLocation = "Chennai"
	PutEfsSfsIdBackupActivateParamsLocationDelhi   PutEfsSfsIdBackupActivateParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PutEfsSfsIdBackupActivateParamsLocation enum.
func (e PutEfsSfsIdBackupActivateParamsLocation) Valid() bool {
	switch e {
	case PutEfsSfsIdBackupActivateParamsLocationChennai:
		return true
	case PutEfsSfsIdBackupActivateParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for PutEfsSfsIdBackupDeactivateParamsLocation.
const (
	PutEfsSfsIdBackupDeactivateParamsLocationChennai PutEfsSfsIdBackupDeactivateParamsLocation = "Chennai"
	PutEfsSfsIdBackupDeactivateParamsLocationDelhi   PutEfsSfsIdBackupDeactivateParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the PutEfsSfsIdBackupDeactivateParamsLocation enum.
func (e PutEfsSfsIdBackupDeactivateParamsLocation) Valid() bool {
	switch e {
	case PutEfsSfsIdBackupDeactivateParamsLocationChennai:
		return true
	case PutEfsSfsIdBackupDeactivateParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// Defines values for DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType.
const (
	VPC DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType = "VPC"
)

// Valid indicates whether the value is a known member of the DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType enum.
func (e DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType) Valid() bool {
	switch e {
	case VPC:
		return true
	default:
		return false
	}
}

// Defines values for DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation.
const (
	DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocationChennai DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation = "Chennai"
	DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocationDelhi   DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation = "Delhi"
)

// Valid indicates whether the value is a known member of the DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation enum.
func (e DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation) Valid() bool {
	switch e {
	case DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocationChennai:
		return true
	case DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocationDelhi:
		return true
	default:
		return false
	}
}

// GetEfsParams defines parameters for GetEfs.
type GetEfsParams struct {
	// PageNo The page number from which you want your page search results to be displayed.
	PageNo *int `form:"page_no,omitempty" json:"page_no,omitempty"`

	// PerPage Number of results per page
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetEfsParamsLocation `form:"location" json:"location"`
}

// GetEfsParamsLocation defines parameters for GetEfs.
type GetEfsParamsLocation string

// PutEfsAllowVpcCidrJSONBody defines parameters for PutEfsAllowVpcCidr.
type PutEfsAllowVpcCidrJSONBody struct {
	// EfsId Example: 467
	EfsId int `json:"efs_id"`

	// Permissions Example: rw
	Permissions string `json:"permissions"`

	// VpcId Example: 3170
	VpcId int `json:"vpc_id"`
}

// PutEfsAllowVpcCidrParams defines parameters for PutEfsAllowVpcCidr.
type PutEfsAllowVpcCidrParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PutEfsAllowVpcCidrParamsLocation `form:"location" json:"location"`
}

// PutEfsAllowVpcCidrParamsLocation defines parameters for PutEfsAllowVpcCidr.
type PutEfsAllowVpcCidrParamsLocation string

// PostEfsCreateJSONBody defines parameters for PostEfsCreate.
type PostEfsCreateJSONBody struct {
	// EfsDiskIops Example: 3750
	EfsDiskIops int `json:"efs_disk_iops"`

	// EfsDiskSize Example: 250
	EfsDiskSize int `json:"efs_disk_size"`

	// EfsName Example: sfs-993
	EfsName string `json:"efs_name"`

	// EfsPlanName Example: 250 GB
	EfsPlanName string `json:"efs_plan_name"`

	// EncryptionPassphrase Example:
	EncryptionPassphrase *string `json:"encryption_passphrase,omitempty"`

	// IsEncryptionEnabled Example: true
	IsEncryptionEnabled bool `json:"isEncryptionEnabled"`

	// SubnetId Example: 346
	SubnetId *string `json:"subnet_id,omitempty"`

	// VpcId Example: 43429
	VpcId int `json:"vpc_id"`
}

// PostEfsCreateParams defines parameters for PostEfsCreate.
type PostEfsCreateParams struct {
	// PageNo The page number from which you want your page search results to be displayed.
	PageNo *int `form:"page_no,omitempty" json:"page_no,omitempty"`

	// PerPage Number of results per page
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PostEfsCreateParamsLocation `form:"location" json:"location"`
}

// PostEfsCreateParamsLocation defines parameters for PostEfsCreate.
type PostEfsCreateParamsLocation string

// DeleteEfsDeleteSfsIdParams defines parameters for DeleteEfsDeleteSfsId.
type DeleteEfsDeleteSfsIdParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location DeleteEfsDeleteSfsIdParamsLocation `form:"location" json:"location"`
}

// DeleteEfsDeleteSfsIdParamsLocation defines parameters for DeleteEfsDeleteSfsId.
type DeleteEfsDeleteSfsIdParamsLocation string

// GetEfsPlansParams defines parameters for GetEfsPlans.
type GetEfsPlansParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location GetEfsPlansParamsLocation `form:"location" json:"location"`
}

// GetEfsPlansParamsLocation defines parameters for GetEfsPlans.
type GetEfsPlansParamsLocation string

// PutEfsSfsIdBackupActivateJSONBody defines parameters for PutEfsSfsIdBackupActivate.
type PutEfsSfsIdBackupActivateJSONBody struct {
	// BackupNow Example: true
	BackupNow bool `json:"backup_now"`

	// StartingMinute Example: 9
	StartingMinute int `json:"startingMinute"`
}

// PutEfsSfsIdBackupActivateParams defines parameters for PutEfsSfsIdBackupActivate.
type PutEfsSfsIdBackupActivateParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PutEfsSfsIdBackupActivateParamsLocation `form:"location" json:"location"`
}

// PutEfsSfsIdBackupActivateParamsLocation defines parameters for PutEfsSfsIdBackupActivate.
type PutEfsSfsIdBackupActivateParamsLocation string

// PutEfsSfsIdBackupDeactivateParams defines parameters for PutEfsSfsIdBackupDeactivate.
type PutEfsSfsIdBackupDeactivateParams struct {
	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location PutEfsSfsIdBackupDeactivateParamsLocation `form:"location" json:"location"`
}

// PutEfsSfsIdBackupDeactivateParamsLocation defines parameters for PutEfsSfsIdBackupDeactivate.
type PutEfsSfsIdBackupDeactivateParamsLocation string

// DeleteEfsSfsIdNodeVpcNodeIdProhibitParams defines parameters for DeleteEfsSfsIdNodeVpcNodeIdProhibit.
type DeleteEfsSfsIdNodeVpcNodeIdProhibitParams struct {
	// ConnectionType connection type
	ConnectionType DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType `form:"connection_type" json:"connection_type"`

	// ProjectId Project ID [Find your project id here  ](https://myaccount.e2enetworks.com/iam-admin/iam?tab=1)
	ProjectId int `form:"project_id" json:"project_id"`

	// Location Deployment region for the resource. Accepted values: `Delhi`, `Chennai`.
	//
	// **Mumbai region has been discontinued.** Delhi and Chennai are the only supported regions.
	Location DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation `form:"location" json:"location"`
}

// DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType defines parameters for DeleteEfsSfsIdNodeVpcNodeIdProhibit.
type DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsConnectionType string

// DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation defines parameters for DeleteEfsSfsIdNodeVpcNodeIdProhibit.
type DeleteEfsSfsIdNodeVpcNodeIdProhibitParamsLocation string

// PutEfsAllowVpcCidrJSONRequestBody defines body for PutEfsAllowVpcCidr for application/json ContentType.
type PutEfsAllowVpcCidrJSONRequestBody PutEfsAllowVpcCidrJSONBody

// PostEfsCreateJSONRequestBody defines body for PostEfsCreate for application/json ContentType.
type PostEfsCreateJSONRequestBody PostEfsCreateJSONBody

// PutEfsSfsIdBackupActivateJSONRequestBody defines body for PutEfsSfsIdBackupActivate for application/json ContentType.
type PutEfsSfsIdBackupActivateJSONRequestBody PutEfsSfsIdBackupActivateJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetEfs List SFS
	//
	// Corresponds with GET /api/v1/efs/ (the `GetEfs` operationId).
	GetEfs(ctx context.Context, params *GetEfsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEfsAllowVpcCidrWithBody Grant SFS Access
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
	PutEfsAllowVpcCidrWithBody(ctx context.Context, params *PutEfsAllowVpcCidrParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEfsAllowVpcCidr Grant SFS Access
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
	PutEfsAllowVpcCidr(ctx context.Context, params *PutEfsAllowVpcCidrParams, body PutEfsAllowVpcCidrJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEfsCreateWithBody Create SFS
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
	PostEfsCreateWithBody(ctx context.Context, params *PostEfsCreateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEfsCreate Create SFS
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
	PostEfsCreate(ctx context.Context, params *PostEfsCreateParams, body PostEfsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteEfsDeleteSfsId Delete SFS
	//
	// Corresponds with DELETE /api/v1/efs/delete/{sfs_id}/ (the `DeleteEfsDeleteSfsId` operationId).
	DeleteEfsDeleteSfsId(ctx context.Context, sfsId string, params *DeleteEfsDeleteSfsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEfsPlans SFS Plans
	//
	// Corresponds with GET /api/v1/efs/plans/ (the `GetEfsPlans` operationId).
	GetEfsPlans(ctx context.Context, params *GetEfsPlansParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEfsSfsIdBackupActivateWithBody Activate SFS backup
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
	PutEfsSfsIdBackupActivateWithBody(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEfsSfsIdBackupActivate Activate SFS backup
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
	PutEfsSfsIdBackupActivate(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, body PutEfsSfsIdBackupActivateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutEfsSfsIdBackupDeactivate Deactivate SFS backup
	//
	// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/deactivate/ (the `PutEfsSfsIdBackupDeactivate` operationId).
	PutEfsSfsIdBackupDeactivate(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupDeactivateParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteEfsSfsIdNodeVpcNodeIdProhibit Disable all access
	//
	// Corresponds with DELETE /api/v1/efs/{sfs_id}/node/{VPC_NODE_ID}/prohibit/ (the `DeleteEfsSfsIdNodeVpcNodeIdProhibit` operationId).
	DeleteEfsSfsIdNodeVpcNodeIdProhibit(ctx context.Context, sfsId string, vpcnodeid int, params *DeleteEfsSfsIdNodeVpcNodeIdProhibitParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetEfs List SFS
//
// Corresponds with GET /api/v1/efs/ (the `GetEfs` operationId).
func (c *Client) GetEfs(ctx context.Context, params *GetEfsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEfsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEfsAllowVpcCidrWithBody Grant SFS Access
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
func (c *Client) PutEfsAllowVpcCidrWithBody(ctx context.Context, params *PutEfsAllowVpcCidrParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEfsAllowVpcCidrRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEfsAllowVpcCidr Grant SFS Access
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
func (c *Client) PutEfsAllowVpcCidr(ctx context.Context, params *PutEfsAllowVpcCidrParams, body PutEfsAllowVpcCidrJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEfsAllowVpcCidrRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostEfsCreateWithBody Create SFS
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
func (c *Client) PostEfsCreateWithBody(ctx context.Context, params *PostEfsCreateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEfsCreateRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostEfsCreate Create SFS
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
func (c *Client) PostEfsCreate(ctx context.Context, params *PostEfsCreateParams, body PostEfsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEfsCreateRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteEfsDeleteSfsId Delete SFS
//
// Corresponds with DELETE /api/v1/efs/delete/{sfs_id}/ (the `DeleteEfsDeleteSfsId` operationId).
func (c *Client) DeleteEfsDeleteSfsId(ctx context.Context, sfsId string, params *DeleteEfsDeleteSfsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteEfsDeleteSfsIdRequest(c.Server, sfsId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetEfsPlans SFS Plans
//
// Corresponds with GET /api/v1/efs/plans/ (the `GetEfsPlans` operationId).
func (c *Client) GetEfsPlans(ctx context.Context, params *GetEfsPlansParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEfsPlansRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEfsSfsIdBackupActivateWithBody Activate SFS backup
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
func (c *Client) PutEfsSfsIdBackupActivateWithBody(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEfsSfsIdBackupActivateRequestWithBody(c.Server, sfsId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEfsSfsIdBackupActivate Activate SFS backup
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
func (c *Client) PutEfsSfsIdBackupActivate(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, body PutEfsSfsIdBackupActivateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEfsSfsIdBackupActivateRequest(c.Server, sfsId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutEfsSfsIdBackupDeactivate Deactivate SFS backup
//
// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/deactivate/ (the `PutEfsSfsIdBackupDeactivate` operationId).
func (c *Client) PutEfsSfsIdBackupDeactivate(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupDeactivateParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutEfsSfsIdBackupDeactivateRequest(c.Server, sfsId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteEfsSfsIdNodeVpcNodeIdProhibit Disable all access
//
// Corresponds with DELETE /api/v1/efs/{sfs_id}/node/{VPC_NODE_ID}/prohibit/ (the `DeleteEfsSfsIdNodeVpcNodeIdProhibit` operationId).
func (c *Client) DeleteEfsSfsIdNodeVpcNodeIdProhibit(ctx context.Context, sfsId string, vpcnodeid int, params *DeleteEfsSfsIdNodeVpcNodeIdProhibitParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteEfsSfsIdNodeVpcNodeIdProhibitRequest(c.Server, sfsId, vpcnodeid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetEfsRequest constructs an http.Request for the GetEfs method
func NewGetEfsRequest(server string, params *GetEfsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageNo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_no", *params.PageNo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutEfsAllowVpcCidrRequest calls the generic PutEfsAllowVpcCidr builder with application/json body
func NewPutEfsAllowVpcCidrRequest(server string, params *PutEfsAllowVpcCidrParams, body PutEfsAllowVpcCidrJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutEfsAllowVpcCidrRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPutEfsAllowVpcCidrRequestWithBody constructs an http.Request for the PutEfsAllowVpcCidr method, with any body, and a specified content type
func NewPutEfsAllowVpcCidrRequestWithBody(server string, params *PutEfsAllowVpcCidrParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/allow-vpc-cidr/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostEfsCreateRequest calls the generic PostEfsCreate builder with application/json body
func NewPostEfsCreateRequest(server string, params *PostEfsCreateParams, body PostEfsCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEfsCreateRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostEfsCreateRequestWithBody constructs an http.Request for the PostEfsCreate method, with any body, and a specified content type
func NewPostEfsCreateRequestWithBody(server string, params *PostEfsCreateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/create/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageNo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_no", *params.PageNo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteEfsDeleteSfsIdRequest constructs an http.Request for the DeleteEfsDeleteSfsId method
func NewDeleteEfsDeleteSfsIdRequest(server string, sfsId string, params *DeleteEfsDeleteSfsIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sfs_id", sfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/delete/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEfsPlansRequest constructs an http.Request for the GetEfsPlans method
func NewGetEfsPlansRequest(server string, params *GetEfsPlansParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/plans/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutEfsSfsIdBackupActivateRequest calls the generic PutEfsSfsIdBackupActivate builder with application/json body
func NewPutEfsSfsIdBackupActivateRequest(server string, sfsId string, params *PutEfsSfsIdBackupActivateParams, body PutEfsSfsIdBackupActivateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutEfsSfsIdBackupActivateRequestWithBody(server, sfsId, params, "application/json", bodyReader)
}

// NewPutEfsSfsIdBackupActivateRequestWithBody constructs an http.Request for the PutEfsSfsIdBackupActivate method, with any body, and a specified content type
func NewPutEfsSfsIdBackupActivateRequestWithBody(server string, sfsId string, params *PutEfsSfsIdBackupActivateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sfs_id", sfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/%s/backup/activate/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutEfsSfsIdBackupDeactivateRequest constructs an http.Request for the PutEfsSfsIdBackupDeactivate method
func NewPutEfsSfsIdBackupDeactivateRequest(server string, sfsId string, params *PutEfsSfsIdBackupDeactivateParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sfs_id", sfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/%s/backup/deactivate/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteEfsSfsIdNodeVpcNodeIdProhibitRequest constructs an http.Request for the DeleteEfsSfsIdNodeVpcNodeIdProhibit method
func NewDeleteEfsSfsIdNodeVpcNodeIdProhibitRequest(server string, sfsId string, vpcnodeid int, params *DeleteEfsSfsIdNodeVpcNodeIdProhibitParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sfs_id", sfsId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "VPC_NODE_ID", vpcnodeid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/efs/%s/node/%s/prohibit/", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "connection_type", params.ConnectionType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "project_id", params.ProjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "location", params.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetEfsWithResponse List SFS
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/efs/ (the `GetEfs` operationId).
	GetEfsWithResponse(ctx context.Context, params *GetEfsParams, reqEditors ...RequestEditorFn) (*GetEfsResponse, error)

	// PutEfsAllowVpcCidrWithBodyWithResponse Grant SFS Access
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
	PutEfsAllowVpcCidrWithBodyWithResponse(ctx context.Context, params *PutEfsAllowVpcCidrParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutEfsAllowVpcCidrResponse, error)

	// PutEfsAllowVpcCidrWithResponse Grant SFS Access
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
	PutEfsAllowVpcCidrWithResponse(ctx context.Context, params *PutEfsAllowVpcCidrParams, body PutEfsAllowVpcCidrJSONRequestBody, reqEditors ...RequestEditorFn) (*PutEfsAllowVpcCidrResponse, error)

	// PostEfsCreateWithBodyWithResponse Create SFS
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
	PostEfsCreateWithBodyWithResponse(ctx context.Context, params *PostEfsCreateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEfsCreateResponse, error)

	// PostEfsCreateWithResponse Create SFS
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
	PostEfsCreateWithResponse(ctx context.Context, params *PostEfsCreateParams, body PostEfsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEfsCreateResponse, error)

	// DeleteEfsDeleteSfsIdWithResponse Delete SFS
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/efs/delete/{sfs_id}/ (the `DeleteEfsDeleteSfsId` operationId).
	DeleteEfsDeleteSfsIdWithResponse(ctx context.Context, sfsId string, params *DeleteEfsDeleteSfsIdParams, reqEditors ...RequestEditorFn) (*DeleteEfsDeleteSfsIdResponse, error)

	// GetEfsPlansWithResponse SFS Plans
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/efs/plans/ (the `GetEfsPlans` operationId).
	GetEfsPlansWithResponse(ctx context.Context, params *GetEfsPlansParams, reqEditors ...RequestEditorFn) (*GetEfsPlansResponse, error)

	// PutEfsSfsIdBackupActivateWithBodyWithResponse Activate SFS backup
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
	PutEfsSfsIdBackupActivateWithBodyWithResponse(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutEfsSfsIdBackupActivateResponse, error)

	// PutEfsSfsIdBackupActivateWithResponse Activate SFS backup
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
	PutEfsSfsIdBackupActivateWithResponse(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, body PutEfsSfsIdBackupActivateJSONRequestBody, reqEditors ...RequestEditorFn) (*PutEfsSfsIdBackupActivateResponse, error)

	// PutEfsSfsIdBackupDeactivateWithResponse Deactivate SFS backup
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/deactivate/ (the `PutEfsSfsIdBackupDeactivate` operationId).
	PutEfsSfsIdBackupDeactivateWithResponse(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupDeactivateParams, reqEditors ...RequestEditorFn) (*PutEfsSfsIdBackupDeactivateResponse, error)

	// DeleteEfsSfsIdNodeVpcNodeIdProhibitWithResponse Disable all access
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1/efs/{sfs_id}/node/{VPC_NODE_ID}/prohibit/ (the `DeleteEfsSfsIdNodeVpcNodeIdProhibit` operationId).
	DeleteEfsSfsIdNodeVpcNodeIdProhibitWithResponse(ctx context.Context, sfsId string, vpcnodeid int, params *DeleteEfsSfsIdNodeVpcNodeIdProhibitParams, reqEditors ...RequestEditorFn) (*DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse, error)
}

type GetEfsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// BackupState Example:
			BackupState   *string     `json:"backup_state,omitempty"`
			CommittedInfo interface{} `json:"committed_info,omitempty"`

			// EfsDiskSize Example: 250 GB
			EfsDiskSize *string `json:"efs_disk_size,omitempty"`

			// Id Example: 1396
			Id *int `json:"id,omitempty"`

			// Iops Example: 3750
			Iops *int `json:"iops,omitempty"`

			// IsEncryptionEnabled Example: true
			IsEncryptionEnabled *bool `json:"isEncryptionEnabled,omitempty"`

			// IsAllVpcResourcesAllowed Example: false
			IsAllVpcResourcesAllowed *bool `json:"is_all_vpc_resources_allowed,omitempty"`

			// IsBackupEnabled Example: false
			IsBackupEnabled *bool `json:"is_backup_enabled,omitempty"`

			// IsE2eVpc Example: false
			IsE2eVpc *bool `json:"is_e2e_vpc,omitempty"`

			// Name Example: sfs-993
			Name *string `json:"name,omitempty"`

			// PlanName Example: 250 GB
			PlanName *string `json:"plan_name,omitempty"`

			// PricePerHour Example: 4.175
			PricePerHour *float32 `json:"price_per_hour,omitempty"`

			// PricePerMonth Example: 3000
			PricePerMonth *float32 `json:"price_per_month,omitempty"`

			// PrivateEndpoint Example: 10.0.0.19
			PrivateEndpoint *string `json:"private_endpoint,omitempty"`

			// Status Example: Available
			Status *string `json:"status,omitempty"`

			// SubnetName Example: Subnet-137
			SubnetName *string `json:"subnet_name,omitempty"`

			// VpcId Example: 6882
			VpcId *int `json:"vpc_id,omitempty"`

			// VpcName Example: VPC-672
			VpcName *string `json:"vpc_name,omitempty"`

			// VpcNodeId Example: 266626
			VpcNodeId *int `json:"vpc_node_id,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetEfsResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// BackupState Example:
		BackupState   *string     `json:"backup_state,omitempty"`
		CommittedInfo interface{} `json:"committed_info,omitempty"`

		// EfsDiskSize Example: 250 GB
		EfsDiskSize *string `json:"efs_disk_size,omitempty"`

		// Id Example: 1396
		Id *int `json:"id,omitempty"`

		// Iops Example: 3750
		Iops *int `json:"iops,omitempty"`

		// IsEncryptionEnabled Example: true
		IsEncryptionEnabled *bool `json:"isEncryptionEnabled,omitempty"`

		// IsAllVpcResourcesAllowed Example: false
		IsAllVpcResourcesAllowed *bool `json:"is_all_vpc_resources_allowed,omitempty"`

		// IsBackupEnabled Example: false
		IsBackupEnabled *bool `json:"is_backup_enabled,omitempty"`

		// IsE2eVpc Example: false
		IsE2eVpc *bool `json:"is_e2e_vpc,omitempty"`

		// Name Example: sfs-993
		Name *string `json:"name,omitempty"`

		// PlanName Example: 250 GB
		PlanName *string `json:"plan_name,omitempty"`

		// PricePerHour Example: 4.175
		PricePerHour *float32 `json:"price_per_hour,omitempty"`

		// PricePerMonth Example: 3000
		PricePerMonth *float32 `json:"price_per_month,omitempty"`

		// PrivateEndpoint Example: 10.0.0.19
		PrivateEndpoint *string `json:"private_endpoint,omitempty"`

		// Status Example: Available
		Status *string `json:"status,omitempty"`

		// SubnetName Example: Subnet-137
		SubnetName *string `json:"subnet_name,omitempty"`

		// VpcId Example: 6882
		VpcId *int `json:"vpc_id,omitempty"`

		// VpcName Example: VPC-672
		VpcName *string `json:"vpc_name,omitempty"`

		// VpcNodeId Example: 266626
		VpcNodeId *int `json:"vpc_node_id,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetEfsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetEfsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEfsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEfsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutEfsAllowVpcCidrResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// EfsId Example: 636
			EfsId *int `json:"efs_id,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Network Configuration Initiated. Expected completion within 2-3 minutes.
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutEfsAllowVpcCidrResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// EfsId Example: 636
		EfsId *int `json:"efs_id,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Network Configuration Initiated. Expected completion within 2-3 minutes.
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PutEfsAllowVpcCidrResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutEfsAllowVpcCidrResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutEfsAllowVpcCidrResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutEfsAllowVpcCidrResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostEfsCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// EfsId Example: 1148
			EfsId *int `json:"efs_id,omitempty"`

			// Name Example: sfs-993
			Name *string `json:"name,omitempty"`

			// PrivateIp Example: 10.9.218.8
			PrivateIp *string `json:"private_ip,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Setting Up your SFS will take 2-3 minutes.
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostEfsCreateResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// EfsId Example: 1148
		EfsId *int `json:"efs_id,omitempty"`

		// Name Example: sfs-993
		Name *string `json:"name,omitempty"`

		// PrivateIp Example: 10.9.218.8
		PrivateIp *string `json:"private_ip,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Setting Up your SFS will take 2-3 minutes.
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostEfsCreateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostEfsCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEfsCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostEfsCreateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteEfsDeleteSfsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`

		// Data Example: {}
		Data *map[string]interface{} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: We have initiated your SFS deletion request you will be notified using email in a short while
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteEfsDeleteSfsIdResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`

	// Data Example: {}
	Data *map[string]interface{} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: We have initiated your SFS deletion request you will be notified using email in a short while
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r DeleteEfsDeleteSfsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteEfsDeleteSfsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteEfsDeleteSfsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteEfsDeleteSfsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetEfsPlansResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *[]struct {
			// AvailableInventoryStatus Example: true
			AvailableInventoryStatus *bool `json:"available_inventory_status,omitempty"`

			// BsSize Example: 0.25
			BsSize *float32 `json:"bs_size,omitempty"`

			// Currency Example: INR
			Currency *string `json:"currency,omitempty"`

			// Iops Example: 3750
			Iops *int `json:"iops,omitempty"`

			// IsActive Example: true
			IsActive *bool `json:"is_active,omitempty"`

			// Location Example: Delhi
			Location *string `json:"location,omitempty"`

			// Name Example: 250 GB
			Name *string `json:"name,omitempty"`

			// PricePerHour Example: 4.175
			PricePerHour *float32 `json:"price_per_hour,omitempty"`

			// PricePerMonth Example: 3000
			PricePerMonth *float32 `json:"price_per_month,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Success
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetEfsPlansResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *[]struct {
		// AvailableInventoryStatus Example: true
		AvailableInventoryStatus *bool `json:"available_inventory_status,omitempty"`

		// BsSize Example: 0.25
		BsSize *float32 `json:"bs_size,omitempty"`

		// Currency Example: INR
		Currency *string `json:"currency,omitempty"`

		// Iops Example: 3750
		Iops *int `json:"iops,omitempty"`

		// IsActive Example: true
		IsActive *bool `json:"is_active,omitempty"`

		// Location Example: Delhi
		Location *string `json:"location,omitempty"`

		// Name Example: 250 GB
		Name *string `json:"name,omitempty"`

		// PricePerHour Example: 4.175
		PricePerHour *float32 `json:"price_per_hour,omitempty"`

		// PricePerMonth Example: 3000
		PricePerMonth *float32 `json:"price_per_month,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Success
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetEfsPlansResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetEfsPlansResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEfsPlansResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEfsPlansResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutEfsSfsIdBackupActivateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r PutEfsSfsIdBackupActivateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutEfsSfsIdBackupActivateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutEfsSfsIdBackupActivateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutEfsSfsIdBackupActivateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutEfsSfsIdBackupDeactivateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// SfsId Example: 467
			SfsId *int `json:"sfs_id,omitempty"`

			// SfsName Example: sfs-828
			SfsName *string `json:"sfs_name,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Your SFS backup was disabled successfully.
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutEfsSfsIdBackupDeactivateResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// SfsId Example: 467
		SfsId *int `json:"sfs_id,omitempty"`

		// SfsName Example: sfs-828
		SfsName *string `json:"sfs_name,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Your SFS backup was disabled successfully.
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PutEfsSfsIdBackupDeactivateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutEfsSfsIdBackupDeactivateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutEfsSfsIdBackupDeactivateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutEfsSfsIdBackupDeactivateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Code Example: 200
		Code *int `json:"code,omitempty"`
		Data *struct {
			// EfsId Example: 636
			EfsId *string `json:"efs_id,omitempty"`
		} `json:"data,omitempty"`

		// Errors Example: {}
		Errors *map[string]interface{} `json:"errors,omitempty"`

		// Message Example: Network De-configuration Initiated. Expected completion within 2-3 minutes.
		Message *string `json:"message,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse) GetJSON200() *struct {
	// Code Example: 200
	Code *int `json:"code,omitempty"`
	Data *struct {
		// EfsId Example: 636
		EfsId *string `json:"efs_id,omitempty"`
	} `json:"data,omitempty"`

	// Errors Example: {}
	Errors *map[string]interface{} `json:"errors,omitempty"`

	// Message Example: Network De-configuration Initiated. Expected completion within 2-3 minutes.
	Message *string `json:"message,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetEfsWithResponse List SFS
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/efs/ (the `GetEfs` operationId).
func (c *ClientWithResponses) GetEfsWithResponse(ctx context.Context, params *GetEfsParams, reqEditors ...RequestEditorFn) (*GetEfsResponse, error) {
	rsp, err := c.GetEfs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEfsResponse(rsp)
}

// PutEfsAllowVpcCidrWithBodyWithResponse Grant SFS Access
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
func (c *ClientWithResponses) PutEfsAllowVpcCidrWithBodyWithResponse(ctx context.Context, params *PutEfsAllowVpcCidrParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutEfsAllowVpcCidrResponse, error) {
	rsp, err := c.PutEfsAllowVpcCidrWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEfsAllowVpcCidrResponse(rsp)
}

// PutEfsAllowVpcCidrWithResponse Grant SFS Access
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/efs/allow-vpc-cidr/ (the `PutEfsAllowVpcCidr` operationId).
func (c *ClientWithResponses) PutEfsAllowVpcCidrWithResponse(ctx context.Context, params *PutEfsAllowVpcCidrParams, body PutEfsAllowVpcCidrJSONRequestBody, reqEditors ...RequestEditorFn) (*PutEfsAllowVpcCidrResponse, error) {
	rsp, err := c.PutEfsAllowVpcCidr(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEfsAllowVpcCidrResponse(rsp)
}

// PostEfsCreateWithBodyWithResponse Create SFS
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
func (c *ClientWithResponses) PostEfsCreateWithBodyWithResponse(ctx context.Context, params *PostEfsCreateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEfsCreateResponse, error) {
	rsp, err := c.PostEfsCreateWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEfsCreateResponse(rsp)
}

// PostEfsCreateWithResponse Create SFS
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/efs/create/ (the `PostEfsCreate` operationId).
func (c *ClientWithResponses) PostEfsCreateWithResponse(ctx context.Context, params *PostEfsCreateParams, body PostEfsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEfsCreateResponse, error) {
	rsp, err := c.PostEfsCreate(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEfsCreateResponse(rsp)
}

// DeleteEfsDeleteSfsIdWithResponse Delete SFS
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/efs/delete/{sfs_id}/ (the `DeleteEfsDeleteSfsId` operationId).
func (c *ClientWithResponses) DeleteEfsDeleteSfsIdWithResponse(ctx context.Context, sfsId string, params *DeleteEfsDeleteSfsIdParams, reqEditors ...RequestEditorFn) (*DeleteEfsDeleteSfsIdResponse, error) {
	rsp, err := c.DeleteEfsDeleteSfsId(ctx, sfsId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteEfsDeleteSfsIdResponse(rsp)
}

// GetEfsPlansWithResponse SFS Plans
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/efs/plans/ (the `GetEfsPlans` operationId).
func (c *ClientWithResponses) GetEfsPlansWithResponse(ctx context.Context, params *GetEfsPlansParams, reqEditors ...RequestEditorFn) (*GetEfsPlansResponse, error) {
	rsp, err := c.GetEfsPlans(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEfsPlansResponse(rsp)
}

// PutEfsSfsIdBackupActivateWithBodyWithResponse Activate SFS backup
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
func (c *ClientWithResponses) PutEfsSfsIdBackupActivateWithBodyWithResponse(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutEfsSfsIdBackupActivateResponse, error) {
	rsp, err := c.PutEfsSfsIdBackupActivateWithBody(ctx, sfsId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEfsSfsIdBackupActivateResponse(rsp)
}

// PutEfsSfsIdBackupActivateWithResponse Activate SFS backup
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/activate/ (the `PutEfsSfsIdBackupActivate` operationId).
func (c *ClientWithResponses) PutEfsSfsIdBackupActivateWithResponse(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupActivateParams, body PutEfsSfsIdBackupActivateJSONRequestBody, reqEditors ...RequestEditorFn) (*PutEfsSfsIdBackupActivateResponse, error) {
	rsp, err := c.PutEfsSfsIdBackupActivate(ctx, sfsId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEfsSfsIdBackupActivateResponse(rsp)
}

// PutEfsSfsIdBackupDeactivateWithResponse Deactivate SFS backup
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/efs/{sfs_id}/backup/deactivate/ (the `PutEfsSfsIdBackupDeactivate` operationId).
func (c *ClientWithResponses) PutEfsSfsIdBackupDeactivateWithResponse(ctx context.Context, sfsId string, params *PutEfsSfsIdBackupDeactivateParams, reqEditors ...RequestEditorFn) (*PutEfsSfsIdBackupDeactivateResponse, error) {
	rsp, err := c.PutEfsSfsIdBackupDeactivate(ctx, sfsId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutEfsSfsIdBackupDeactivateResponse(rsp)
}

// DeleteEfsSfsIdNodeVpcNodeIdProhibitWithResponse Disable all access
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1/efs/{sfs_id}/node/{VPC_NODE_ID}/prohibit/ (the `DeleteEfsSfsIdNodeVpcNodeIdProhibit` operationId).
func (c *ClientWithResponses) DeleteEfsSfsIdNodeVpcNodeIdProhibitWithResponse(ctx context.Context, sfsId string, vpcnodeid int, params *DeleteEfsSfsIdNodeVpcNodeIdProhibitParams, reqEditors ...RequestEditorFn) (*DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse, error) {
	rsp, err := c.DeleteEfsSfsIdNodeVpcNodeIdProhibit(ctx, sfsId, vpcnodeid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteEfsSfsIdNodeVpcNodeIdProhibitResponse(rsp)
}

// ParseGetEfsResponse parses an HTTP response from a GetEfsWithResponse call
func ParseGetEfsResponse(rsp *http.Response) (*GetEfsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEfsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// BackupState Example:
				BackupState   *string     `json:"backup_state,omitempty"`
				CommittedInfo interface{} `json:"committed_info,omitempty"`

				// EfsDiskSize Example: 250 GB
				EfsDiskSize *string `json:"efs_disk_size,omitempty"`

				// Id Example: 1396
				Id *int `json:"id,omitempty"`

				// Iops Example: 3750
				Iops *int `json:"iops,omitempty"`

				// IsEncryptionEnabled Example: true
				IsEncryptionEnabled *bool `json:"isEncryptionEnabled,omitempty"`

				// IsAllVpcResourcesAllowed Example: false
				IsAllVpcResourcesAllowed *bool `json:"is_all_vpc_resources_allowed,omitempty"`

				// IsBackupEnabled Example: false
				IsBackupEnabled *bool `json:"is_backup_enabled,omitempty"`

				// IsE2eVpc Example: false
				IsE2eVpc *bool `json:"is_e2e_vpc,omitempty"`

				// Name Example: sfs-993
				Name *string `json:"name,omitempty"`

				// PlanName Example: 250 GB
				PlanName *string `json:"plan_name,omitempty"`

				// PricePerHour Example: 4.175
				PricePerHour *float32 `json:"price_per_hour,omitempty"`

				// PricePerMonth Example: 3000
				PricePerMonth *float32 `json:"price_per_month,omitempty"`

				// PrivateEndpoint Example: 10.0.0.19
				PrivateEndpoint *string `json:"private_endpoint,omitempty"`

				// Status Example: Available
				Status *string `json:"status,omitempty"`

				// SubnetName Example: Subnet-137
				SubnetName *string `json:"subnet_name,omitempty"`

				// VpcId Example: 6882
				VpcId *int `json:"vpc_id,omitempty"`

				// VpcName Example: VPC-672
				VpcName *string `json:"vpc_name,omitempty"`

				// VpcNodeId Example: 266626
				VpcNodeId *int `json:"vpc_node_id,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutEfsAllowVpcCidrResponse parses an HTTP response from a PutEfsAllowVpcCidrWithResponse call
func ParsePutEfsAllowVpcCidrResponse(rsp *http.Response) (*PutEfsAllowVpcCidrResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutEfsAllowVpcCidrResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// EfsId Example: 636
				EfsId *int `json:"efs_id,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Network Configuration Initiated. Expected completion within 2-3 minutes.
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEfsCreateResponse parses an HTTP response from a PostEfsCreateWithResponse call
func ParsePostEfsCreateResponse(rsp *http.Response) (*PostEfsCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEfsCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// EfsId Example: 1148
				EfsId *int `json:"efs_id,omitempty"`

				// Name Example: sfs-993
				Name *string `json:"name,omitempty"`

				// PrivateIp Example: 10.9.218.8
				PrivateIp *string `json:"private_ip,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Setting Up your SFS will take 2-3 minutes.
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteEfsDeleteSfsIdResponse parses an HTTP response from a DeleteEfsDeleteSfsIdWithResponse call
func ParseDeleteEfsDeleteSfsIdResponse(rsp *http.Response) (*DeleteEfsDeleteSfsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteEfsDeleteSfsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`

			// Data Example: {}
			Data *map[string]interface{} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: We have initiated your SFS deletion request you will be notified using email in a short while
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetEfsPlansResponse parses an HTTP response from a GetEfsPlansWithResponse call
func ParseGetEfsPlansResponse(rsp *http.Response) (*GetEfsPlansResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEfsPlansResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *[]struct {
				// AvailableInventoryStatus Example: true
				AvailableInventoryStatus *bool `json:"available_inventory_status,omitempty"`

				// BsSize Example: 0.25
				BsSize *float32 `json:"bs_size,omitempty"`

				// Currency Example: INR
				Currency *string `json:"currency,omitempty"`

				// Iops Example: 3750
				Iops *int `json:"iops,omitempty"`

				// IsActive Example: true
				IsActive *bool `json:"is_active,omitempty"`

				// Location Example: Delhi
				Location *string `json:"location,omitempty"`

				// Name Example: 250 GB
				Name *string `json:"name,omitempty"`

				// PricePerHour Example: 4.175
				PricePerHour *float32 `json:"price_per_hour,omitempty"`

				// PricePerMonth Example: 3000
				PricePerMonth *float32 `json:"price_per_month,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Success
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutEfsSfsIdBackupActivateResponse parses an HTTP response from a PutEfsSfsIdBackupActivateWithResponse call
func ParsePutEfsSfsIdBackupActivateResponse(rsp *http.Response) (*PutEfsSfsIdBackupActivateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutEfsSfsIdBackupActivateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutEfsSfsIdBackupDeactivateResponse parses an HTTP response from a PutEfsSfsIdBackupDeactivateWithResponse call
func ParsePutEfsSfsIdBackupDeactivateResponse(rsp *http.Response) (*PutEfsSfsIdBackupDeactivateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutEfsSfsIdBackupDeactivateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// SfsId Example: 467
				SfsId *int `json:"sfs_id,omitempty"`

				// SfsName Example: sfs-828
				SfsName *string `json:"sfs_name,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Your SFS backup was disabled successfully.
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteEfsSfsIdNodeVpcNodeIdProhibitResponse parses an HTTP response from a DeleteEfsSfsIdNodeVpcNodeIdProhibitWithResponse call
func ParseDeleteEfsSfsIdNodeVpcNodeIdProhibitResponse(rsp *http.Response) (*DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteEfsSfsIdNodeVpcNodeIdProhibitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Code Example: 200
			Code *int `json:"code,omitempty"`
			Data *struct {
				// EfsId Example: 636
				EfsId *string `json:"efs_id,omitempty"`
			} `json:"data,omitempty"`

			// Errors Example: {}
			Errors *map[string]interface{} `json:"errors,omitempty"`

			// Message Example: Network De-configuration Initiated. Expected completion within 2-3 minutes.
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
